/**
 * WorldBookAuditService —— 世界书编写智能体审计服务
 *
 * 来源：spec §二 Task 2 / `implement-worldbook-authoring-agent`
 * 决策：自研（spec §三无对应 openclaw 文件）。审计服务复用现有底座：
 *       EmbeddingService（向量化）/ AIService（LLM 语义对比）。
 *
 * 职责：
 *  1. validateCompleteness：必填字段 + 维度覆盖 + 条目数达标（80% 阈值）
 *  2. checkConsistency：关键词冲突（cosine 复验）+ 设定矛盾（LLM 对比）+ 关系图无环（DFS）
 *  3. evaluateConformance：用户提示 + 澄清回答与条目的语义一致性（cosine 相似度）
 *  4. runFullAudit：聚合三维度 + 自动修复建议 + 用户决策项
 *
 * 设计约束：
 *  - 错误隔离：每维度独立 try-catch，单维度失败不阻塞其他维度（降级返回部分报告 + warn 日志）
 *  - 依赖注入：EmbeddingService / LLMCompareFn 可通过构造参数注入，便于测试 mock
 *    （LLM 调用：复用 AIService 的 streamChatAPI；若不便于直接调用，定义 LLMCompareFn 注入点）
 *  - 字段标准：对齐 `worldBookService.migrateEntry` ——
 *    · key: string[]（非空数组，每元素非空字符串）
 *    · content: string（非空）
 *    · comment 或 name: string（至少一个非空）
 *  - 日志前缀：[WorldBookAuditService]
 *
 * 实现说明（向量化策略）：
 *  - 当前实现采用直接 cosine 计算（embeddingService.generateEmbedding + 内联 cosineSimilarity），
 *    而非 vectorStoreService.search，原因：
 *    1) 草稿区条目（autoGenerated=true）可能尚未写入向量库，无法通过 search 检索
 *    2) 直接 cosine 计算更易测试 mock，避免 sqlite-vec post-filter 语义限制
 *    3) 接口预留 IVectorStoreProvider，未来可扩展为优先查向量库、降级重新向量化
 */

import type {
  AuthoringPlan,
  AuthoringDimension,
  CompletenessReport,
  ConsistencyReport,
  ConsistencyIssue,
  ConformanceReport,
  DeviatedEntry,
  AuditReport,
  AuditAutoFix,
  AuditUserDecision,
  MissingField,
  UnderfilledDimension,
  AuditSeverity,
} from '../../../../shared/types/worldbook-authoring.types';
import type { IAuditServices } from './worldbookAuthoringTypes';
import { AgentError, toAgentError } from '../infra/errors';

// ==================== 依赖类型（结构化类型，便于测试 mock） ====================

/**
 * EmbeddingService 接口契约（仅暴露审计服务所需方法）。
 *
 * 通过结构化类型而非导入 EmbeddingService 类，降低耦合并便于测试 mock。
 * 字段对齐 `EmbeddingService.generateEmbedding` 返回值（EmbeddingResult）。
 */
export interface IEmbeddingProvider {
  generateEmbedding(text: string): Promise<{
    success: boolean;
    vector?: number[];
    error?: string;
  }>;
}

/**
 * VectorStoreService 接口契约（仅暴露审计服务所需方法，可选依赖）。
 *
 * 当前实现未使用（采用直接 cosine 计算），保留接口便于未来扩展为优先查向量库。
 */
export interface IVectorStoreProvider {
  search(
    query: number[],
    topK: number,
    filter?: Record<string, unknown>
  ): Promise<Array<{
    id: string;
    score: number;
    metadata: Record<string, unknown>;
  }>>;
}

/**
 * LLM 语义对比函数类型（依赖注入点，便于测试 mock）。
 *
 * 入参：条目列表（uid + content + name）
 * 出参：冲突列表（entryIds + description + severity）
 *
 * 默认实现（defaultLLMCompare）使用 AIService.streamChatAPI 调用 LLM，
 * 测试时可注入 mock 函数避免真实 LLM 调用。
 */
export type LLMCompareFn = (
  entries: Array<{
    uid: string | number;
    name?: string;
    content: string;
  }>
) => Promise<Array<{
  entryIds: Array<string | number>;
  description: string;
  severity: AuditSeverity;
}>>;

/**
 * 审计服务依赖注入容器。
 */
export interface WorldBookAuditServiceDeps {
  embeddingService?: IEmbeddingProvider;
  vectorStoreService?: IVectorStoreProvider;
  llmCompare?: LLMCompareFn;
}

// ==================== 常量 ====================

const LOG_PREFIX = '[WorldBookAuditService]';

/** 关键词冲突 cosine 阈值：< 此值视为矛盾（spec §ADDED Requirements 逻辑一致性检查） */
const KEYWORD_CONFLICT_COSINE_THRESHOLD = 0.3;

/** 符合度偏离 cosine 阈值：< 此值标记为偏离（spec §ADDED Requirements 设定符合度评估，可配置） */
const DEFAULT_CONFORMANCE_DEVIATION_THRESHOLD = 0.4;

/** 符合度整体通过阈值：conformantCount / totalCount >= 此值才通过（对齐 AuthoringConfig.auditThreshold 默认 0.8） */
const DEFAULT_CONFORMANCE_OVERALL_THRESHOLD = 0.8;

/** 条目数达标率阈值（spec §ADDED Requirements 内容完整性校验：80%） */
const DEFAULT_COMPLETENESS_RATIO = 0.8;

// ==================== 工具函数 ====================

/**
 * 计算两个向量的余弦相似度。
 *
 * 对齐 SqliteVecBackend 的 cosineSimilarity 实现：
 *   cosine = (A·B) / (||A|| × ||B||)
 *
 * @returns cosine similarity ∈ [-1, 1]；维度不匹配或零向量返回 0
 */
function cosineSimilarity(a: number[], b: number[]): number {
  if (!Array.isArray(a) || !Array.isArray(b) || a.length === 0 || a.length !== b.length) {
    return 0;
  }
  let dot = 0;
  let normA = 0;
  let normB = 0;
  for (let i = 0; i < a.length; i++) {
    dot += a[i] * b[i];
    normA += a[i] * a[i];
    normB += b[i] * b[i];
  }
  const denom = Math.sqrt(normA) * Math.sqrt(normB);
  return denom === 0 ? 0 : dot / denom;
}

/**
 * 从条目中提取 uid（支持 number / string）。
 * 对齐 worldBookService.migrateEntry：`id: entry.id || entry.uid`。
 */
function getEntryUid(entry: Record<string, unknown>): string | number {
  const uid = entry.uid ?? entry.id;
  if (typeof uid === 'number' || typeof uid === 'string') return uid;
  return -1; // 无 uid 的兜底（不应出现于正规条目）
}

/**
 * 从条目中提取 key 数组（标准化为 string[]）。
 * 对齐 worldBookService.migrateEntry：key 应为 string[]，兼容旧格式 string。
 */
function getEntryKeys(entry: Record<string, unknown>): string[] {
  const raw = entry.key;
  if (Array.isArray(raw)) {
    return raw.filter((k): k is string => typeof k === 'string' && k.trim() !== '');
  }
  if (typeof raw === 'string' && raw.trim() !== '') {
    return [raw];
  }
  return [];
}

/**
 * 从条目中提取 content（标准化为 string）。
 */
function getEntryContent(entry: Record<string, unknown>): string {
  const content = entry.content;
  return typeof content === 'string' ? content : '';
}

/**
 * 从条目中提取 name（标准化为 string）。
 */
function getEntryName(entry: Record<string, unknown>): string {
  const name = entry.name;
  return typeof name === 'string' ? name : '';
}

/**
 * 从条目中提取 comment（标准化为 string）。
 */
function getEntryComment(entry: Record<string, unknown>): string {
  const comment = entry.comment;
  return typeof comment === 'string' ? comment : '';
}

/**
 * 从条目中提取 dimensionId（自定义字段，agent 生成的条目可能携带）。
 */
function getEntryDimensionId(entry: Record<string, unknown>): string | undefined {
  const dimId = entry.dimensionId;
  return typeof dimId === 'string' && dimId.trim() !== '' ? dimId : undefined;
}

/**
 * 从条目中提取 relations（自定义字段，agent 生成的条目可能携带）。
 * 结构：Array<{ targetId: string | number; type?: string }>
 */
function getEntryRelations(
  entry: Record<string, unknown>
): Array<{ targetId: string | number; type?: string }> {
  const raw = entry.relations;
  if (!Array.isArray(raw)) return [];
  const result: Array<{ targetId: string | number; type?: string }> = [];
  for (const r of raw) {
    if (typeof r !== 'object' || r === null) continue;
    const targetId = (r as Record<string, unknown>).targetId;
    if (typeof targetId !== 'string' && typeof targetId !== 'number') continue;
    const type = (r as Record<string, unknown>).type;
    const item: { targetId: string | number; type?: string } = { targetId };
    if (typeof type === 'string') {
      item.type = type;
    }
    result.push(item);
  }
  return result;
}

/**
 * 推断条目归属的维度 ID。
 *
 * 优先级（spec §二 Task 2.1）：
 *  1. entry.dimensionId（agent 显式标注）
 *  2. entry.category 匹配 dimension.category
 *  3. entry 名称/内容关键词匹配 dimension.name / description
 *  4. 无法推断 → undefined（不归属任何维度，记入"其他"）
 *
 * @param entry 条目
 * @param dimensions 编写计划中的维度清单
 * @returns 维度 ID；无法推断时返回 undefined
 */
function inferEntryDimensionId(
  entry: Record<string, unknown>,
  dimensions: AuthoringDimension[]
): string | undefined {
  // 1. 显式 dimensionId
  const explicitDimId = getEntryDimensionId(entry);
  if (explicitDimId) {
    return dimensions.find((d) => d.id === explicitDimId)?.id ?? explicitDimId;
  }

  // 2. category 匹配
  const entryCategory = entry.category;
  if (typeof entryCategory === 'string') {
    const matched = dimensions.find((d) => d.category === entryCategory);
    if (matched) return matched.id;
  }

  // 3. 名称/内容关键词匹配 dimension.name / description
  const name = getEntryName(entry).toLowerCase();
  const content = getEntryContent(entry).toLowerCase();
  for (const dim of dimensions) {
    const dimName = dim.name.toLowerCase();
    if (dimName && (name.includes(dimName) || content.includes(dimName))) {
      return dim.id;
    }
    const dimDesc = (dim.description ?? '').toLowerCase();
    // 用描述前 30 字符作为匹配片段（避免过长描述误匹配）
    if (dimDesc.length > 2) {
      const snippet = dimDesc.slice(0, 30);
      if (content.includes(snippet)) {
        return dim.id;
      }
    }
  }

  // 4. 无法推断 → undefined
  return undefined;
}

/**
 * 安全 JSON 解析：从 LLM 响应中提取 JSON（容忍 markdown code fence 与多余文本）。
 */
function safeParseJSON<T>(text: string): T | null {
  if (!text) return null;
  // 移除 markdown code fence
  const fenceMatch = text.match(/```(?:json)?\s*([\s\S]*?)```/);
  const jsonText = fenceMatch ? fenceMatch[1] : text;
  try {
    return JSON.parse(jsonText.trim()) as T;
  } catch {
    // 尝试截取第一个 { 到最后一个 } 之间的内容
    const start = jsonText.indexOf('{');
    const end = jsonText.lastIndexOf('}');
    if (start >= 0 && end > start) {
      try {
        return JSON.parse(jsonText.slice(start, end + 1)) as T;
      } catch {
        return null;
      }
    }
    return null;
  }
}

// ==================== 默认 LLM 对比实现 ====================

/**
 * 默认 LLM 对比函数：使用 AIService.streamChatAPI 调用 LLM。
 *
 * prompt 要求 LLM 返回 JSON {conflicts: [{entryIds, description, severity}]}。
 * 失败时抛错（由 checkConsistency 的 detectSettingContradictions 捕获并降级为仅关键词冲突检测）。
 */
async function defaultLLMCompare(
  entries: Array<{ uid: string | number; name?: string; content: string }>
): Promise<Array<{ entryIds: Array<string | number>; description: string; severity: AuditSeverity }>> {
  // 动态导入避免循环依赖，且测试环境不注入 llmCompare 时也不会加载 AIService
  const { aiService } = await import('../../AIService');

  const config = await aiService.getConfig();

  if (!config.baseUrl) {
    throw new AgentError('AI 服务地址未配置，无法执行 LLM 设定矛盾检测', {
      category: 'validation',
      retryable: false,
    });
  }

  const entriesText = entries
    .map((e) => `## 条目 UID=${e.uid}${e.name ? ` (${e.name})` : ''}\n${e.content}`)
    .join('\n\n');

  const systemPrompt = `你是一个世界书设定一致性审计员。下面给你若干条目的内容，请检测它们之间的语义矛盾或冲突。

要求：
1. 仅检测明显的语义矛盾（如条目A说"城市在地下"，条目B说"摩天大楼林立"）
2. 每个冲突需给出条目 UID 对、矛盾描述、严重级别
3. 严重级别：info / warning / error / critical
4. 如无冲突，返回空数组

返回 JSON 格式（仅返回 JSON，不要其他文字）：
\`\`\`json
{
  "conflicts": [
    {
      "entryIds": [uid1, uid2],
      "description": "矛盾描述",
      "severity": "error"
    }
  ]
}
\`\`\``;

  const messages = [
    { role: 'system' as const, content: systemPrompt },
    { role: 'user' as const, content: entriesText },
  ];

  const result = await aiService.streamChatAPI(
    messages,
    {
      model: config.model,
      temperature: config.temperature ?? 0.2,
      maxTokens: config.maxTokens ?? 4096,
      maxRetries: 1,
    },
    () => {
      // 不消费流式 chunk，仅使用最终 result.content
    }
  );

  const parsed = safeParseJSON<{
    conflicts?: Array<{
      entryIds: Array<string | number>;
      description: string;
      severity: AuditSeverity;
    }>;
  }>(result.content);

  if (!parsed || !Array.isArray(parsed.conflicts)) {
    console.warn(
      `${LOG_PREFIX} defaultLLMCompare: LLM 返回内容无法解析为 JSON，原文前 200 字符: ${result.content.slice(0, 200)}`
    );
    return [];
  }
  return parsed.conflicts;
}

// ==================== 主服务实现 ====================

/**
 * 世界书编写智能体审计服务。
 *
 * 实现 IAuditServices 接口的 4 个方法：
 *  - validateCompleteness：内容完整性校验
 *  - checkConsistency：逻辑一致性检查
 *  - evaluateConformance：设定符合度评估
 *  - runFullAudit：完整审计聚合
 *
 * 用法：
 * ```ts
 * // 默认单例（运行时使用）
 * import { worldbookAuditService } from './worldbookAuditService';
 * const report = await worldbookAuditService.runFullAudit(plan, entries, prompt, clarifications);
 *
 * // 测试时注入 mock 依赖
 * const service = new WorldBookAuditService({
 *   embeddingService: mockEmbeddingService,
 *   llmCompare: mockLLMCompare,
 * });
 * ```
 */
export class WorldBookAuditService implements IAuditServices {
  private readonly deps: WorldBookAuditServiceDeps;

  constructor(deps: WorldBookAuditServiceDeps = {}) {
    this.deps = deps;
  }

  // ==================== SubTask 2.1: validateCompleteness ====================

  /**
   * 内容完整性校验（spec §ADDED Requirements 内容完整性校验）。
   *
   * 校验三维度：
   *  1. 必填字段：key 非空数组 / content 非空 / comment 或 name 非空
   *     （对齐 `worldBookService.migrateEntry` 字段标准）
   *  2. 维度覆盖：plan.goal.dimensions 中每维度至少有 1 个条目
   *  3. 条目数达标：每维度条目数 >= targetEntryCount * 0.8
   */
  async validateCompleteness(
    plan: AuthoringPlan,
    entries: Array<Record<string, unknown>>
  ): Promise<CompletenessReport> {
    const dimensions = plan.goal.dimensions;
    const missingFields: MissingField[] = [];

    // 1. 必填字段校验
    for (const entry of entries) {
      const uid = getEntryUid(entry);

      // key 非空数组
      const keys = getEntryKeys(entry);
      if (keys.length === 0) {
        missingFields.push({
          entryUid: uid,
          field: 'key',
          reason: 'key is empty array or missing',
        });
      }

      // content 非空字符串
      const content = getEntryContent(entry);
      if (content.trim() === '') {
        missingFields.push({
          entryUid: uid,
          field: 'content',
          reason: 'content is empty string or missing',
        });
      }

      // comment 或 name 非空
      const name = getEntryName(entry);
      const comment = getEntryComment(entry);
      if (name.trim() === '' && comment.trim() === '') {
        missingFields.push({
          entryUid: uid,
          field: 'comment',
          reason: 'both comment and name are empty',
        });
      }
    }

    // 2. 维度覆盖 + 3. 条目数达标
    const uncoveredDimensions: Array<{ dimensionId: string; dimensionName: string }> = [];
    const underfilledDimensions: UnderfilledDimension[] = [];

    // 构建维度 → 条目列表映射
    const dimensionToEntries = new Map<string, Array<Record<string, unknown>>>();
    for (const dim of dimensions) {
      dimensionToEntries.set(dim.id, []);
    }

    // 将每个条目归入对应维度
    for (const entry of entries) {
      const dimId = inferEntryDimensionId(entry, dimensions);
      if (dimId && dimensionToEntries.has(dimId)) {
        dimensionToEntries.get(dimId)!.push(entry);
      }
      // 无法归入任何维度的条目忽略（不影响维度覆盖检查）
    }

    // 检查每个维度的覆盖与达标
    for (const dim of dimensions) {
      const dimEntries = dimensionToEntries.get(dim.id) ?? [];

      // 维度覆盖：至少 1 个条目
      if (dimEntries.length === 0) {
        uncoveredDimensions.push({
          dimensionId: dim.id,
          dimensionName: dim.name,
        });
        continue; // 未覆盖的维度不必检查达标率
      }

      // 条目数达标：>= targetEntryCount * 0.8
      const targetCount = dim.targetEntryCount;
      const actualCount = dimEntries.length;
      const achievementRate = targetCount > 0 ? actualCount / targetCount : 1;

      if (achievementRate < DEFAULT_COMPLETENESS_RATIO) {
        underfilledDimensions.push({
          dimensionId: dim.id,
          dimensionName: dim.name,
          targetCount,
          actualCount,
          achievementRate,
        });
      }
    }

    const passed =
      missingFields.length === 0 &&
      uncoveredDimensions.length === 0 &&
      underfilledDimensions.length === 0;

    return {
      missingFields,
      uncoveredDimensions,
      underfilledDimensions,
      passed,
    };
  }

  // ==================== SubTask 2.2: checkConsistency ====================

  /**
   * 逻辑一致性检查（spec §ADDED Requirements 逻辑一致性检查）。
   *
   * 检测三维度：
   *  1. 关键词冲突：同一 key 触发语义矛盾的条目（cosine 相似度 < 0.3 视为矛盾）
   *  2. 设定矛盾：通过 LLM 对比条目 content 的语义一致性
   *  3. 关系图无环：若条目间有 relations 字段，校验无循环依赖
   */
  async checkConsistency(
    entries: Array<Record<string, unknown>>
  ): Promise<ConsistencyReport> {
    const issues: ConsistencyIssue[] = [];

    // 1. 关键词冲突检测（同 key 字符串的条目对，cosine < 0.3 视为矛盾）
    await this.detectKeywordConflicts(entries, issues);

    // 2. 设定矛盾检测（LLM 对比 content 语义一致性）
    await this.detectSettingContradictions(entries, issues);

    // 3. 关系图无环检测
    this.detectRelationCycles(entries, issues);

    // passed = 无 error / critical 级别问题
    const passed = !issues.some(
      (i) => i.severity === 'error' || i.severity === 'critical'
    );

    return { issues, passed };
  }

  /**
   * 关键词冲突检测（spec §二 Task 2.2）：
   *  - 找出共享至少一个 key 字符串的条目对（字符串匹配快速筛）
   *  - 对每对计算 content 向量的 cosine 相似度（向量复验）
   *  - cosine < 0.3 视为矛盾，标记为 keyword_conflict
   *
   * 降级：embeddingService 未注入或向量化失败时跳过该检测，记 warn 日志
   */
  private async detectKeywordConflicts(
    entries: Array<Record<string, unknown>>,
    issues: ConsistencyIssue[]
  ): Promise<void> {
    // 构建 key → 条目索引列表 的映射
    const keyToEntries = new Map<
      string,
      Array<{ index: number; entry: Record<string, unknown> }>
    >();
    for (let i = 0; i < entries.length; i++) {
      const entry = entries[i];
      const keys = getEntryKeys(entry);
      for (const k of keys) {
        const normalized = k.toLowerCase().trim();
        if (!normalized) continue;
        if (!keyToEntries.has(normalized)) {
          keyToEntries.set(normalized, []);
        }
        keyToEntries.get(normalized)!.push({ index: i, entry });
      }
    }

    // 收集需要计算 cosine 的条目对（去重）
    const pairSet = new Set<string>();
    const pairsToCheck: Array<[number, number]> = [];
    for (const [, group] of keyToEntries) {
      if (group.length < 2) continue;
      for (let i = 0; i < group.length; i++) {
        for (let j = i + 1; j < group.length; j++) {
          const a = group[i].index;
          const b = group[j].index;
          const key = a < b ? `${a}-${b}` : `${b}-${a}`;
          if (!pairSet.has(key)) {
            pairSet.add(key);
            pairsToCheck.push([a, b]);
          }
        }
      }
    }

    if (pairsToCheck.length === 0) return;

    const embeddingService = this.deps.embeddingService;
    if (!embeddingService) {
      console.warn(
        `${LOG_PREFIX} detectKeywordConflicts: embeddingService 未注入，跳过关键词冲突复验`
      );
      return;
    }

    // 收集需要向量化的索引
    const indicesToEmbed = new Set<number>();
    for (const [a, b] of pairsToCheck) {
      indicesToEmbed.add(a);
      indicesToEmbed.add(b);
    }

    // 批量向量化（容错：单个失败不阻塞）
    const vectors = new Map<number, number[]>();
    for (const idx of indicesToEmbed) {
      const content = getEntryContent(entries[idx]);
      if (content.trim() === '') continue;
      try {
        const result = await embeddingService.generateEmbedding(content);
        if (result.success && result.vector) {
          vectors.set(idx, result.vector);
        } else {
          console.warn(
            `${LOG_PREFIX} detectKeywordConflicts: 条目 idx=${idx} 向量化失败: ${result.error ?? 'unknown'}`
          );
        }
      } catch (err) {
        console.warn(
          `${LOG_PREFIX} detectKeywordConflicts: 条目 idx=${idx} 向量化异常:`,
          err
        );
      }
    }

    // 计算每对的 cosine 相似度
    for (const [a, b] of pairsToCheck) {
      const vecA = vectors.get(a);
      const vecB = vectors.get(b);
      if (!vecA || !vecB) continue;

      const similarity = cosineSimilarity(vecA, vecB);
      if (similarity < KEYWORD_CONFLICT_COSINE_THRESHOLD) {
        const entryA = entries[a];
        const entryB = entries[b];
        issues.push({
          entryIds: [getEntryUid(entryA), getEntryUid(entryB)],
          description: `关键词冲突：两条目共享 key 但 content 语义矛盾（cosine=${similarity.toFixed(3)} < ${KEYWORD_CONFLICT_COSINE_THRESHOLD}）`,
          severity: 'error',
          kind: 'keyword_conflict',
        });
      }
    }
  }

  /**
   * 设定矛盾检测（spec §二 Task 2.2）：
   *  - 调用 LLM（复用 AIService）对比条目 content 语义一致性
   *  - prompt 要求 LLM 返回 JSON {conflicts: [{entryIds, description, severity}]}
   *  - LLM 调用失败时降级为仅关键词冲突检测并记 warn 日志
   */
  private async detectSettingContradictions(
    entries: Array<Record<string, unknown>>,
    issues: ConsistencyIssue[]
  ): Promise<void> {
    if (entries.length < 2) return;

    const llmCompare = this.deps.llmCompare ?? defaultLLMCompare;

    // 准备 LLM 入参（仅包含有 content 的条目）
    const llmEntries = entries
      .map((e) => ({
        uid: getEntryUid(e),
        name: getEntryName(e) || undefined,
        content: getEntryContent(e),
      }))
      .filter((e) => e.content.trim() !== '');

    if (llmEntries.length < 2) return;

    try {
      const conflicts = await llmCompare(llmEntries);
      for (const c of conflicts) {
        issues.push({
          entryIds: c.entryIds,
          description: c.description,
          severity: c.severity,
          kind: 'setting_contradiction',
        });
      }
    } catch (err) {
      // 降级：LLM 调用失败时跳过设定矛盾检测，记 warn 日志
      const agentErr = toAgentError(err);
      console.warn(
        `${LOG_PREFIX} detectSettingContradictions: LLM 调用失败，降级为仅关键词冲突检测。原因: ${agentErr.message}`,
        err
      );
    }
  }

  /**
   * 关系图无环检测（spec §二 Task 2.2）：
   *  - 若条目有 relations 字段（数组 of {targetId, type}），用 DFS 检测循环依赖
   *  - 发现环时标记为 relation_cycle（severity: error）
   *
   * 算法：三色标记法（WHITE/GRAY/BLACK）
   *  - WHITE：未访问
   *  - GRAY：正在访问（在递归栈中）
   *  - BLACK：已完成
   *  - 遇到 GRAY 节点表示发现环
   */
  private detectRelationCycles(
    entries: Array<Record<string, unknown>>,
    issues: ConsistencyIssue[]
  ): void {
    // 构建邻接表：uid → [targetId, ...]
    const graph = new Map<string | number, Array<string | number>>();
    const uidSet = new Set<string | number>();

    for (const entry of entries) {
      const uid = getEntryUid(entry);
      uidSet.add(uid);
      const relations = getEntryRelations(entry);
      if (relations.length > 0) {
        graph.set(uid, relations.map((r) => r.targetId));
      }
    }

    if (graph.size === 0) return;

    // DFS 检测环（三色标记法）
    const WHITE = 0;
    const GRAY = 1;
    const BLACK = 2;
    const color = new Map<string | number, number>();
    const inCycle = new Set<string | number>();

    const dfs = (node: string | number, path: Array<string | number>): void => {
      color.set(node, GRAY);
      path.push(node);

      const neighbors = graph.get(node) ?? [];
      for (const next of neighbors) {
        const nextColor = color.get(next) ?? WHITE;
        if (nextColor === GRAY) {
          // 发现环：next 在当前递归栈中，标记环中的所有节点
          const cycleStart = path.indexOf(next);
          if (cycleStart >= 0) {
            for (let i = cycleStart; i < path.length; i++) {
              inCycle.add(path[i]);
            }
          }
          inCycle.add(next);
        } else if (nextColor === WHITE && uidSet.has(next)) {
          // 仅访问图中存在的节点（避免悬挂引用误报）
          dfs(next, path);
        }
      }

      path.pop();
      color.set(node, BLACK);
    };

    for (const entry of entries) {
      const uid = getEntryUid(entry);
      if ((color.get(uid) ?? WHITE) === WHITE) {
        dfs(uid, []);
      }
    }

    if (inCycle.size > 0) {
      issues.push({
        entryIds: Array.from(inCycle),
        description: `关系图存在循环依赖：${Array.from(inCycle).join(' → ')}`,
        severity: 'error',
        kind: 'relation_cycle',
      });
    }
  }

  // ==================== SubTask 2.3: evaluateConformance ====================

  /**
   * 设定符合度评估（spec §ADDED Requirements 设定符合度评估）。
   *
   * 流程：
   *  1. 将 userPrompt + clarifications（用户回答拼接）通过 EmbeddingService 向量化
   *  2. 对每个条目，用其已有向量（或按 content 重新向量化）做 cosine 相似度检索
   *  3. 相似度 < 0.4 标记为偏离，附 score 和 reason
   *
   * 降级：向量化失败时跳过该条目并记 warn，不阻塞审计
   */
  async evaluateConformance(
    userPrompt: string,
    clarifications: Array<{ questionId: string; answer: string }>,
    entries: Array<Record<string, unknown>>
  ): Promise<ConformanceReport> {
    const embeddingService = this.deps.embeddingService;
    if (!embeddingService) {
      console.warn(
        `${LOG_PREFIX} evaluateConformance: embeddingService 未注入，返回默认通过报告（降级）`
      );
      // 降级：无向量化能力时返回默认通过报告（不阻塞审计）
      return {
        conformantCount: entries.length,
        totalCount: entries.length,
        deviatedEntries: [],
        passed: true,
      };
    }

    // 1. 合并用户提示 + 澄清回答为查询文本
    const clarificationText = clarifications
      .map((c) => c.answer)
      .filter((a) => a && a.trim() !== '')
      .join('\n');
    const queryText = [userPrompt, clarificationText]
      .filter((t) => t && t.trim() !== '')
      .join('\n\n');

    if (queryText.trim() === '') {
      console.warn(
        `${LOG_PREFIX} evaluateConformance: 查询文本为空，返回默认通过报告`
      );
      return {
        conformantCount: entries.length,
        totalCount: entries.length,
        deviatedEntries: [],
        passed: true,
      };
    }

    // 2. 向量化查询文本
    let queryVector: number[] | null = null;
    try {
      const queryResult = await embeddingService.generateEmbedding(queryText);
      if (queryResult.success && queryResult.vector) {
        queryVector = queryResult.vector;
      } else {
        console.warn(
          `${LOG_PREFIX} evaluateConformance: 查询文本向量化失败: ${queryResult.error ?? 'unknown'}，降级返回默认通过报告`
        );
        return {
          conformantCount: entries.length,
          totalCount: entries.length,
          deviatedEntries: [],
          passed: true,
        };
      }
    } catch (err) {
      console.warn(
        `${LOG_PREFIX} evaluateConformance: 查询文本向量化异常:`,
        err,
        '降级返回默认通过报告'
      );
      return {
        conformantCount: entries.length,
        totalCount: entries.length,
        deviatedEntries: [],
        passed: true,
      };
    }

    // 3. 对每个条目计算 cosine 相似度
    const deviatedEntries: DeviatedEntry[] = [];
    let conformantCount = 0;
    let processedCount = 0;

    for (const entry of entries) {
      const content = getEntryContent(entry);
      if (content.trim() === '') {
        // 空内容跳过（不阻塞审计）
        console.warn(
          `${LOG_PREFIX} evaluateConformance: 条目 uid=${getEntryUid(entry)} content 为空，跳过`
        );
        continue;
      }

      let entryVector: number[] | null = null;
      try {
        const result = await embeddingService.generateEmbedding(content);
        if (result.success && result.vector) {
          entryVector = result.vector;
        } else {
          console.warn(
            `${LOG_PREFIX} evaluateConformance: 条目 uid=${getEntryUid(entry)} 向量化失败: ${result.error ?? 'unknown'}，跳过`
          );
          continue;
        }
      } catch (err) {
        console.warn(
          `${LOG_PREFIX} evaluateConformance: 条目 uid=${getEntryUid(entry)} 向量化异常:`,
          err,
          '跳过'
        );
        continue;
      }

      processedCount += 1;
      const score = cosineSimilarity(queryVector, entryVector);

      if (score < DEFAULT_CONFORMANCE_DEVIATION_THRESHOLD) {
        deviatedEntries.push({
          entryUid: getEntryUid(entry),
          entryName: getEntryName(entry) || undefined,
          score,
          reason: `cosine 相似度 ${score.toFixed(3)} 低于阈值 ${DEFAULT_CONFORMANCE_DEVIATION_THRESHOLD}`,
        });
      } else {
        conformantCount += 1;
      }
    }

    const totalCount = processedCount;
    // passed = conformantCount / totalCount >= auditThreshold（默认 0.8）
    // 边界：totalCount=0 时视为通过（无可评估条目）
    const passed =
      totalCount === 0
        ? true
        : conformantCount / totalCount >= DEFAULT_CONFORMANCE_OVERALL_THRESHOLD;

    return {
      conformantCount,
      totalCount,
      deviatedEntries,
      passed,
    };
  }

  // ==================== SubTask 2.4: runFullAudit ====================

  /**
   * 完整审计聚合（spec §ADDED Requirements 审计闭环阶段）。
   *
   * 顺序调用三维度（completeness → consistency → conformance），聚合为 AuditReport。
   *  - overallPassed = completeness.passed && consistency.passed && conformance.passed
   *  - 生成 autoFixes（自动修复建议：如缺失字段标"需补充"、未覆盖维度标"需生成条目"）
   *  - 生成 userDecisions（需用户决策项：如严重矛盾标"需用户选择保留哪个条目"）
   *
   * 错误隔离：每维度独立 try-catch，单维度失败不阻塞其他维度（降级返回部分报告 + warn 日志）
   */
  async runFullAudit(
    plan: AuthoringPlan,
    entries: Array<Record<string, unknown>>,
    userPrompt: string,
    clarifications: Array<{ questionId: string; answer: string }>
  ): Promise<AuditReport> {
    // 顺序调用三维度，每维度独立 try-catch（降级返回部分报告 + warn 日志）

    let completeness: CompletenessReport;
    try {
      completeness = await this.validateCompleteness(plan, entries);
    } catch (err) {
      const agentErr = toAgentError(err);
      console.warn(
        `${LOG_PREFIX} runFullAudit: validateCompleteness 失败，降级返回默认报告。原因: ${agentErr.message}`,
        err
      );
      completeness = {
        missingFields: [],
        uncoveredDimensions: [],
        underfilledDimensions: [],
        passed: false,
      };
    }

    let consistency: ConsistencyReport;
    try {
      consistency = await this.checkConsistency(entries);
    } catch (err) {
      const agentErr = toAgentError(err);
      console.warn(
        `${LOG_PREFIX} runFullAudit: checkConsistency 失败，降级返回默认报告。原因: ${agentErr.message}`,
        err
      );
      consistency = {
        issues: [],
        passed: false,
      };
    }

    let conformance: ConformanceReport;
    try {
      conformance = await this.evaluateConformance(
        userPrompt,
        clarifications,
        entries
      );
    } catch (err) {
      const agentErr = toAgentError(err);
      console.warn(
        `${LOG_PREFIX} runFullAudit: evaluateConformance 失败，降级返回默认报告。原因: ${agentErr.message}`,
        err
      );
      conformance = {
        conformantCount: 0,
        totalCount: entries.length,
        deviatedEntries: [],
        passed: false,
      };
    }

    const overallPassed =
      completeness.passed && consistency.passed && conformance.passed;

    // 综合分数：三维度加权平均（completeness 0.4 / consistency 0.4 / conformance 0.2）
    const completenessScore = this.computeCompletenessScore(completeness);
    const consistencyScore = this.computeConsistencyScore(consistency);
    const conformanceScore = this.computeConformanceScore(conformance);
    const overallScore =
      completenessScore * 0.4 + consistencyScore * 0.4 + conformanceScore * 0.2;

    // 生成 autoFixes（自动修复建议）
    const autoFixes = this.generateAutoFixes(completeness, consistency, conformance);

    // 生成 userDecisions（需用户决策项）
    const userDecisions = this.generateUserDecisions(
      completeness,
      consistency,
      conformance
    );

    return {
      completeness,
      consistency,
      conformance,
      overallPassed,
      overallScore,
      autoFixes,
      userDecisions,
      createdAt: Date.now(),
    };
  }

  /**
   * 计算完整性分数 [0, 1]。
   * 每个问题按类型扣分，下限 0。
   */
  private computeCompletenessScore(report: CompletenessReport): number {
    if (report.passed) return 1;
    const deduction =
      report.missingFields.length * 0.1 +
      report.uncoveredDimensions.length * 0.2 +
      report.underfilledDimensions.length * 0.1;
    return Math.max(0, 1 - deduction);
  }

  /**
   * 计算一致性分数 [0, 1]。
   * 按严重级别加权扣分，下限 0。
   */
  private computeConsistencyScore(report: ConsistencyReport): number {
    if (report.issues.length === 0) return 1;
    let deduction = 0;
    for (const issue of report.issues) {
      switch (issue.severity) {
        case 'critical':
          deduction += 0.5;
          break;
        case 'error':
          deduction += 0.3;
          break;
        case 'warning':
          deduction += 0.1;
          break;
        case 'info':
          deduction += 0.02;
          break;
      }
    }
    return Math.max(0, 1 - deduction);
  }

  /**
   * 计算符合度分数 [0, 1]。
   */
  private computeConformanceScore(report: ConformanceReport): number {
    if (report.totalCount === 0) return 1;
    return report.conformantCount / report.totalCount;
  }

  /**
   * 生成自动修复建议（spec §ADDED Requirements 审计闭环阶段自动修复或提示）。
   *
   * 小问题（warning / 部分 error）由智能体自动修复；
   * 修复建议记录到 AuditReport.autoFixes，便于追溯。
   *
   * 生成规则：
   *  - 缺失字段：标"需补充"
   *  - 未覆盖维度：标"需生成条目"
   *  - 未达标维度：标"需补充至目标条目数"
   *  - warning 级别一致性问题：标"需修正"
   *  - 偏离条目：标"需调整以符合用户设定"
   */
  private generateAutoFixes(
    completeness: CompletenessReport,
    consistency: ConsistencyReport,
    conformance: ConformanceReport
  ): AuditAutoFix[] {
    const fixes: AuditAutoFix[] = [];

    // 缺失字段
    for (const missing of completeness.missingFields) {
      fixes.push({
        entryUid: missing.entryUid,
        field: missing.field,
        oldValue: '',
        newValue: '需补充',
        reason: `缺失必填字段：${missing.reason}`,
        severity: 'warning',
        applied: false,
      });
    }

    // 未覆盖维度
    for (const dim of completeness.uncoveredDimensions) {
      fixes.push({
        entryUid: `dim:${dim.dimensionId}`,
        field: 'entries',
        oldValue: '0',
        newValue: '需生成条目',
        reason: `维度未覆盖：${dim.dimensionName}`,
        severity: 'warning',
        applied: false,
      });
    }

    // 未达标维度
    for (const dim of completeness.underfilledDimensions) {
      fixes.push({
        entryUid: `dim:${dim.dimensionId}`,
        field: 'entries',
        oldValue: String(dim.actualCount),
        newValue: `需补充至 ${dim.targetCount}`,
        reason: `条目数未达标：${dim.actualCount}/${dim.targetCount} (${(dim.achievementRate * 100).toFixed(0)}%)`,
        severity: 'warning',
        applied: false,
      });
    }

    // 一致性问题（warning 级别）
    for (const issue of consistency.issues) {
      if (issue.severity === 'warning') {
        for (const uid of issue.entryIds) {
          fixes.push({
            entryUid: uid,
            field: 'content',
            oldValue: '',
            newValue: '需修正',
            reason: `${issue.kind}: ${issue.description}`,
            severity: 'warning',
            applied: false,
          });
        }
      }
    }

    // 偏离条目
    for (const dev of conformance.deviatedEntries) {
      fixes.push({
        entryUid: dev.entryUid,
        field: 'content',
        oldValue: '',
        newValue: '需调整以符合用户设定',
        reason: dev.reason ?? `cosine ${dev.score.toFixed(3)} 低于阈值`,
        severity: 'warning',
        applied: false,
      });
    }

    return fixes;
  }

  /**
   * 生成需用户决策项（spec §ADDED Requirements 审计闭环阶段自动修复或提示）。
   *
   * 大问题（critical / 部分 error）由智能体汇总报告提示用户决策，不自动修复。
   *
   * 生成规则：
   *  - critical / error 级别一致性问题：需用户选择保留哪个条目
   *  - 严重偏离条目（score < 0.2）：需用户确认是否保留
   */
  private generateUserDecisions(
    _completeness: CompletenessReport,
    consistency: ConsistencyReport,
    conformance: ConformanceReport
  ): AuditUserDecision[] {
    const decisions: AuditUserDecision[] = [];

    // 严重一致性问题
    for (const issue of consistency.issues) {
      if (issue.severity === 'critical' || issue.severity === 'error') {
        decisions.push({
          id: `decision_consistency_${decisions.length + 1}`,
          entryIds: issue.entryIds,
          description: `${issue.kind}: ${issue.description}`,
          severity: issue.severity,
          options: ['修改条目A', '修改条目B', '删除其中一个', '忽略'],
        });
      }
    }

    // 严重偏离条目（score < 0.2）
    const severeDeviations = conformance.deviatedEntries.filter(
      (d) => d.score < 0.2
    );
    if (severeDeviations.length > 0) {
      decisions.push({
        id: `decision_conformance_${decisions.length + 1}`,
        entryIds: severeDeviations.map((d) => d.entryUid),
        description: `${severeDeviations.length} 个条目与用户设定严重偏离（cosine < 0.2）`,
        severity: 'error',
        options: ['删除全部偏离条目', '保留但需修改', '忽略'],
      });
    }

    return decisions;
  }
}

// ==================== 单例导出 ====================

/**
 * 审计服务单例。
 *
 * 默认不注入依赖，运行时通过动态导入延迟解析 EmbeddingService / AIService。
 * 测试时直接 `new WorldBookAuditService({ ...mocks })` 创建新实例。
 */
export const worldbookAuditService = new WorldBookAuditService();
