/**
 * WorldBookAuthoringService 类型定义 —— 世界书编写智能体编排层
 *
 * 来源：spec §二 Task 1.2 / `implement-worldbook-authoring-agent`
 * 决策：自研（spec §三无对应 openclaw 文件）。世界书自驱是本项目特有业务，
 *       复用现有底座（agentCore / worldbookTools / MemoryStore / steerEngine /
 *       goalTracker / autoGenerated 草稿区），借鉴 openclaw 任务驱动行为模型。
 *
 * 设计约束（对齐 `agent/writing/writingAgentTypes.ts` re-export 模式）：
 *  - 类型真源：`src/shared/types/worldbook-authoring.types.ts`
 *  - 本文件 re-export 共享类型，附加主进程专用的接口契约（IAuditServices /
 *    IPlanningServices / WorldBookAuthoringConfig）
 *  - 不创建 index.ts（Task 4 编排服务 `worldbookAuthoringService.ts` 会创建）
 *
 * 设计理念（借鉴 openclaw，spec §设计理念）：
 *  1. 任务驱动行为模型：智能体围绕显式 `AuthoringGoal` 行动
 *  2. 多轮对话上下文管理：`AuthoringSession` 持久化到 MemoryStore
 *  3. 自主决策：PLANNING / AUTHORING / AUDITING 三阶段自主决策
 *  4. steer 行为引导：偏离质量标准时注入 steer 消息
 *  5. goal 目标追踪：追踪编写目标完成度
 *  6. 防失控调度：pacing/stagger 钳位
 */

// re-export 共享类型（主进程 + 渲染进程共用）
// 参照 `agent/writing/writingAgentTypes.ts` 的 re-export 模式，使用 `export *` 透传全部类型与常量。
export * from '../../../../shared/types/worldbook-authoring.types';

// ==================== 主进程专用类型 ====================

import type {
  AuthoringConfig,
  AuthoringPlan,
  AuthoringSession,
  AuditReport,
  CompletenessReport,
  ConformanceReport,
  ConsistencyReport,
} from '../../../../shared/types/worldbook-authoring.types';

// ==================== LLM / AgentCore 配置（主进程专用） ====================

/**
 * LLM 调用配置（主进程专用）。
 *
 * 用于 `worldbookPlanningService` 与 `worldbookAuditService` 调用 LLM 时的参数。
 * 字段对齐 `AIService.streamChatAPI` 入参。
 */
export interface WorldBookAuthoringLLMConfig {
  /** 模型名称 */
  model: string;
  /** 采样温度 */
  temperature: number;
  /** 最大输出 tokens */
  maxTokens: number;
  /** API base URL（可选，未指定时使用全局配置） */
  baseUrl?: string;
  /** API key（可选，未指定时使用全局配置） */
  apiKey?: string;
}

/**
 * AgentCore 运行配置（主进程专用）。
 *
 * 用于 `worldbookAuthoringService` 调用 `AgentCore.run` 时的循环参数。
 * 字段对齐 `contracts.ts` 的 `AgentRunIntent`。
 */
export interface WorldBookAuthoringAgentCoreConfig {
  /** 最大迭代次数（默认 8，对齐 `AgentRunIntent.maxIterations`） */
  maxIterations?: number;
  /** 超时毫秒（默认 300000 = 5 分钟） */
  timeoutMs?: number;
  /** 是否禁用并行工具调用（默认 true，简化 agentLoop 顺序执行） */
  parallelToolCalls?: boolean;
}

/**
 * 世界书编写智能体主进程配置。
 *
 * 扩展共享 `AuthoringConfig`（业务参数），附加 LLM 与 AgentCore 运行参数。
 * 由 `worldbookAuthoringService` 构造时接收，IPC handler 从前端配置转换而来。
 */
export interface WorldBookAuthoringConfig extends AuthoringConfig {
  /** LLM 调用配置 */
  llmConfig: WorldBookAuthoringLLMConfig;
  /** AgentCore 运行配置（可选，未指定时使用默认值） */
  agentCoreConfig?: WorldBookAuthoringAgentCoreConfig;
}

// ==================== 审计服务接口契约 ====================

/**
 * 审计服务接口（spec §二 Task 2 / `worldbookAuditService` 契约）。
 *
 * 实现方：`worldbookAuditService.ts`
 * 职责：对编写过程与结果进行三维度质量把控：
 *  1. 内容完整性校验（必填字段、维度覆盖、条目数达标）
 *  2. 逻辑一致性检查（关键词冲突、设定矛盾、关系图无环）
 *  3. 设定符合度评估（与用户初始提示 + 澄清回答的语义一致性）
 *
 * 设计约束：
 *  - 接口尽量窄：仅暴露审计编排服务真正需要的 4 个方法
 *  - 返回 Promise：所有 I/O 异步化（LLM 调用 / 向量检索）
 *  - 不直接依赖 worldBookService：通过参数接收 entries，保持低耦合
 */
export interface IAuditServices {
  /**
   * 内容完整性校验（spec §ADDED Requirements 内容完整性校验）。
   *
   * 校验三维度：
   *  1. 必填字段：`key` 非空数组 / `content` 非空 / `comment` 或 `name` 非空
   *     （对齐 `worldBookService.migrateEntry` 字段标准）
   *  2. 维度覆盖：`AuthoringPlan` 中每个维度至少有 1 个条目
   *  3. 条目数达标：每维度达到目标条目数的 80% 以上
   *
   * @param plan 编写计划（提供维度清单与目标条目数）
   * @param entries 待校验条目列表（草稿区条目）
   * @returns 完整性报告
   */
  validateCompleteness(
    plan: AuthoringPlan,
    entries: Array<Record<string, unknown>>
  ): Promise<CompletenessReport>;

  /**
   * 逻辑一致性检查（spec §ADDED Requirements 逻辑一致性检查）。
   *
   * 检测三维度：
   *  1. 关键词冲突：同一 `key` 触发语义矛盾的条目（复用 `vectorStoreService` cosine 相似度）
   *  2. 设定矛盾：通过 LLM 对比条目 content 的语义一致性
   *  3. 关系图无环：若条目间有 `relations` 字段，校验无循环依赖
   *
   * @param entries 待检查条目列表
   * @returns 一致性报告
   */
  checkConsistency(
    entries: Array<Record<string, unknown>>
  ): Promise<ConsistencyReport>;

  /**
   * 设定符合度评估（spec §ADDED Requirements 设定符合度评估）。
   *
   * 将用户初始提示 + 澄清回答向量化，与每个条目做 cosine 相似度检索，
   * 低相似度条目标记为"偏离设定"，附相似度分数。
   *
   * @param userPrompt 用户初始提示
   * @param clarifications 澄清回答汇总（来自 `AuthoringPlan.userAnswers`）
   * @param entries 待评估条目列表
   * @returns 符合度报告
   */
  evaluateConformance(
    userPrompt: string,
    clarifications: Array<{ questionId: string; answer: string }>,
    entries: Array<Record<string, unknown>>
  ): Promise<ConformanceReport>;

  /**
   * 完整审计聚合（spec §ADDED Requirements 审计闭环阶段）。
   *
   * 调用上述三个方法，聚合为 `AuditReport`，附自动修复建议与需用户决策项。
   *
   * @param plan 编写计划
   * @param entries 待审计条目列表
   * @param userPrompt 用户初始提示
   * @param clarifications 澄清回答汇总
   * @returns 完整审计报告
   */
  runFullAudit(
    plan: AuthoringPlan,
    entries: Array<Record<string, unknown>>,
    userPrompt: string,
    clarifications: Array<{ questionId: string; answer: string }>
  ): Promise<AuditReport>;
}

// ==================== 规划服务接口契约 ====================

/**
 * 规划服务接口（spec §二 Task 3 / `worldbookPlanningService` 契约）。
 *
 * 实现方：`worldbookPlanningService.ts`
 * 职责：对话式需求澄清 + 维度扩展 + 计划生成。
 *
 * 设计约束：
 *  - 接口尽量窄：仅暴露编排服务真正需要的 4 个方法
 *  - 返回 Promise：所有 LLM 调用异步化
 *  - 复用 `integrate-worldbook-ai-prompts` 的 `world-book.generate-new-entries` 提示词模板
 */
export interface IPlanningServices {
  /**
   * 分析用户初始提示（spec §二 Task 3.1）。
   *
   * LLM 分析初始提示，识别设定维度（世界观/势力/人物/地点/物品/事件/规则），
   * 标注用户明确提及 vs 智能体建议补充。复用 `world-book.generate-new-entries` 提示词模板。
   *
   * @param userPrompt 用户初始提示（如"为一部赛博朋克侦探小说创建世界书"）
   * @param researchContext 网络搜索补充资料（可选，Spec: add-agent-web-search-tool）。
   *        启用网络搜索时由编排服务在 PLANNING 阶段调用 webSearch 获取，
   *        格式化为字符串后传入；实现方将其注入 LLM 系统提示词作为参考上下文。
   *        未启用网络搜索时为 undefined，行为与原实现一致（向后兼容）。
   * @returns 提示分析结果（含识别到的维度清单）
   */
  analyzePrompt(
    userPrompt: string,
    researchContext?: string
  ): Promise<{
    /** 识别到的设定维度（含用户明确提及与智能体建议补充） */
    dimensions: Array<{
      name: string;
      category: import('../../../../shared/types/worldbook-authoring.types').AuthoringDimensionCategory;
      source: 'user' | 'agent-suggested';
      description?: string;
    }>;
    /** 主题摘要（LLM 提取的核心主题） */
    themeSummary: string;
    /** 模糊点列表（用于生成澄清问题） */
    ambiguities: string[];
  }>;

  /**
   * 生成澄清问题（spec §二 Task 3.2 / §ADDED Requirements 主动提出澄清问题）。
   *
   * 基于提示分析中的模糊点，生成 2-4 个结构化澄清问题，每问题附"为什么需要"说明。
   *
   * @param promptAnalysis 提示分析结果（来自 `analyzePrompt`）
   * @returns 澄清问题列表（2-4 个）
   */
  generateClarifyingQuestions(
    promptAnalysis: Awaited<ReturnType<IPlanningServices['analyzePrompt']>>
  ): Promise<
    Array<{
      id: string;
      question: string;
      why: string;
    }>
  >;

  /**
   * 构建编写计划（spec §二 Task 3.3）。
   *
   * 综合用户回答生成 `AuthoringPlan`（维度清单 + 目标条目数 + 关键词策略 + 质量门槛）。
   * 跳过的问题由智能体推断默认值并标注。
   *
   * @param userPrompt 用户初始提示
   * @param answers 用户回答列表（含跳过标记）
   * @param promptAnalysis 提示分析结果
   * @returns 编写计划
   */
  buildPlan(
    userPrompt: string,
    answers: Array<{
      questionId: string;
      question: string;
      answer?: string;
      skipped: boolean;
    }>,
    promptAnalysis: Awaited<ReturnType<IPlanningServices['analyzePrompt']>>
  ): Promise<AuthoringPlan>;

  /**
   * 自驱扩展维度（spec §二 Task 3.4 / §ADDED Requirements 主动扩展内容维度）。
   *
   * 识别 plan 中缺失但对完整性必要的维度，追加到 plan 并标注"智能体建议"。
   *
   * @param plan 当前编写计划
   * @returns 扩展后的编写计划（新增维度 source='agent-suggested'）
   */
  expandDimensions(plan: AuthoringPlan): Promise<AuthoringPlan>;
}

// ==================== 进度回调类型 ====================

/**
 * 进度回调类型（主进程内部使用，渲染进程不直接使用）。
 *
 * 参照 `writingAgentTypes.ts` 的 `AgentWritingProgressCallback` 模式。
 * 编排服务通过此回调推送 `AuthoringProgressEvent`，IPC handler 桥接到渲染进程。
 */
export type WorldBookAuthoringProgressCallback = (
  event: import('../../../../shared/types/worldbook-authoring.types').AuthoringProgressEvent
) => void;

// ==================== 编排服务运行入参（主进程专用） ====================

/**
 * 编写智能体运行请求（主进程专用，IPC `worldbookAgent:run` 入参）。
 *
 * 由 IPC handler 从前端配置转换而来，传给 `worldbookAuthoringService.runAgent`。
 */
export interface WorldBookAuthoringRunRequest {
  /** 用户初始提示（如"为一部赛博朋克侦探小说创建世界书"） */
  userPrompt: string;
  /** 主世界书文件绝对路径 */
  worldBookPath: string;
  /** 沙盒白名单（默认 [worldBookPath]） */
  allowedWorldBookPaths?: string[];
  /** 编写配置（含 LLM / AgentCore 参数） */
  config: WorldBookAuthoringConfig;
  /** 进度回调（IPC handler 桥接到渲染进程事件流） */
  onProgress?: WorldBookAuthoringProgressCallback;
  /** AbortSignal（用于取消机制） */
  signal?: AbortSignal;
}

/**
 * 编写智能体运行结果（主进程专用，IPC `worldbookAgent:run` 出参）。
 */
export interface WorldBookAuthoringRunResult {
  /** 是否成功完成 */
  success: boolean;
  /** 会话 ID */
  sessionId: string;
  /** 最终会话状态（COMPLETE / AWAITING_REVIEW / CANCELLED / ERROR） */
  finalState: AuthoringSession['state'] | 'CANCELLED' | 'ERROR';
  /** 已生成条目 UID 列表（草稿区） */
  generatedEntryIds: Array<number | string>;
  /** 审计报告（若执行了审计） */
  auditReport?: AuditReport;
  /** 总耗时（ms） */
  totalDurationMs: number;
  /** 错误信息（success=false 时存在） */
  error?: string;
}
