/**
 * WorldBookAuthoringService —— 世界书编写智能体编排服务（核心）
 *
 * 来源：spec §二 Task 4 / `implement-worldbook-authoring-agent`
 * 决策：自研（spec §三无对应 openclaw 文件）。世界书自驱编排是本项目特有业务，
 *       复用现有底座（worldbookTools / worldbookAuditService / worldbookPlanningService /
 *       MemoryStore / steerEngine / goalTracker / autoGenerated 草稿区），
 *       借鉴 openclaw 任务驱动行为模型与 writingAgentService 的编排模式。
 *
 * 职责（spec §ADDED Requirements 三阶段启发式工作流）：
 *  1. PLANNING  ：调用规划服务分析提示 → 生成澄清问题 → 等待用户回答 → 构建计划 → 扩展维度
 *  2. AUTHORING ：按计划逐维度生成条目（LLM 生成 + worldbookTools.createEntry 写草稿），
 *                 每 3 条触发微型审计，发现问题注入 steer 消息，pacing 钳位
 *  3. AUDITING  ：调用 auditService.runFullAudit 三维度审计，小问题自动修复，大问题汇总报告
 *  4. AWAITING_REVIEW → COMPLETE：等待用户审阅草稿，标记完成
 *
 * 设计约束（对齐 `writingAgentService.ts` 编排模式）：
 *  - 单实例守卫：同一 worldBookPath 同时只允许一个编写会话（Map<worldBookPath, session>）
 *  - AbortController 取消：cancel(sessionId) 调用 abort，循环检查 signal
 *  - 断点续跑：每次状态转移后 memoryStore.write 持久化 session，resumeSession 恢复
 *  - 进度回调：emitProgress 推送 AuthoringProgressEvent
 *  - 降级保护：单维度失败不中断整体（记 warn + 继续下一维度）
 *  - LLM 重试：LLM 调用失败重试 3 次（复用 infra/retry.ts）
 *  - 日志前缀：[WorldBookAuthoringService]
 *
 * 等待用户回答机制（关键设计）：
 *  - PLANNING 阶段生成澄清问题后，通过 onProgress 推送 {phase: 'planning_clarifying', clarifyingQuestions}
 *  - 会话进入"等待回答"子状态：session.pendingQuestions = questions
 *  - 内部用 Promise + resolver：session.answerResolver
 *  - 暴露 submitAnswers(sessionId, answers) 供 IPC handler 调用，resolve 该 Promise
 *  - 设超时（10 分钟）自动跳过未回答问题（全部标 skipped=true）
 *  - 取消时 reject 该 Promise（避免永久挂起）
 */

import type {
  AuthoringSession,
  AuthoringState,
  AuthoringPlan,
  AuthoringDimension,
  AuthoringProgressEvent,
  AuditReport,
  ThoughtStep,
} from '../../../../shared/types/worldbook-authoring.types';
import type {
  WorldBookAuthoringRunRequest,
  WorldBookAuthoringRunResult,
  WorldBookAuthoringConfig,
  WorldBookAuthoringProgressCallback,
  IAuditServices,
  IPlanningServices,
} from './worldbookAuthoringTypes';
import type { ToolCallContext, ToolExecutionResult, IMemoryProvider } from '../contracts';
import { retryAsync } from '../infra/retry';
import { toAgentError } from '../infra/errors';
import { resolvePacedNextRunAtMs } from '../learning/pacing';
// Spec: polish-deai-humanizer 扩展 — 生成场景去AI味规则（与渲染进程 6 个生成入口同款 JSON-aware 变体）
import { withHumanizerGenerationRules } from '../../../../shared/prompts/humanizerPolish';

// ==================== 常量 ====================

const LOG_PREFIX = '[WorldBookAuthoringService]';

/** PLANNING 阶段等待用户回答超时（10 分钟，spec 要求） */
const CLARIFY_TIMEOUT_MS = 10 * 60 * 1000;

/** 会话总超时（30 分钟，spec 要求） */
const SESSION_TIMEOUT_MS = 30 * 60 * 1000;

/** 单维度连续失败阈值（spec §SubTask 4.6 阻塞计数器） */
const DIMENSION_FAILURE_THRESHOLD = 3;

/** 微型审计触发间隔（每 N 条触发一次，spec "每 3-5 条"） */
const MINI_AUDIT_INTERVAL = 3;

/** LLM 调用最大重试次数（spec "LLM 调用失败重试 3 次"） */
const LLM_MAX_RETRIES = 3;

// ==================== 依赖注入类型 ====================

/**
 * 编排服务所用的世界书工具能力（仅暴露编排真正需要的子集）。
 *
 * 通过结构化类型而非直接导入 worldbookTools，降低耦合并便于测试 mock。
 * 默认实现 `createDefaultAuthoringTools` 用 worldbookTools 的导出函数构造。
 */
export interface IAuthoringTools {
  /** 读取世界书（含 entries），用于审计前获取已生成条目 */
  readWorldBook(
    worldBookPath: string
  ): Promise<{
    name?: string;
    description?: string;
    entries?: Array<Record<string, unknown>>;
  } | null>;

  /** 创建草稿条目（autoGenerated=true，spec §ADDED Requirements 自驱编写阶段） */
  createEntry(args: {
    worldBookPath: string;
    name: string;
    content: string;
    keys: string[];
    secondaryKeys?: string[];
    comment?: string;
    dimensionId?: string;
  }, context: ToolCallContext): Promise<ToolExecutionResult>;

  /** 为已有条目重新生成关键词（用于微型审计发现问题后修复） */
  generateKeywords(args: {
    worldBookPath: string;
    entryUid: string | number;
    keys: string[];
    secondaryKeys?: string[];
  }, context: ToolCallContext): Promise<ToolExecutionResult>;

  /**
   * 网络搜索（可选，Spec: add-agent-web-search-tool §Requirement: 世界书编写智能体集成）。
   *
   * 仅当 `WorldBookAuthoringConfig.enableWebSearch === true` 时由编排服务注入并调用。
   * 为可选方法（`?`）：未启用网络搜索时 `undefined`，编排服务调用前做存在性检查，
   * 既有测试无需 mock 此方法（向后兼容）。
   *
   * @param query 搜索关键词
   * @param maxResults 最大结果条数（可选，默认由实现方决定，通常 5）
   * @returns 搜索结果数组（标题 / 摘要 / URL）。失败时返回空数组（不抛错，由实现方捕获降级）
   */
  webSearch?(query: string, maxResults?: number): Promise<Array<{
    title: string;
    snippet: string;
    url: string;
  }>>;
}

/**
 * 条目生成器（LLM 调用注入点，便于测试 mock）。
 *
 * 职责：根据维度描述 + 已有条目，调用 LLM 生成 N 个新条目的草稿数据（name/content/keys）。
 * 默认实现 `createDefaultEntryGenerator` 使用 AIService.callChatAPI。
 */
export interface IEntryGenerator {
  generateEntriesForDimension(
    dimension: AuthoringDimension,
    plan: AuthoringPlan,
    existingEntries: Array<Record<string, unknown>>,
    targetCount: number,
    signal?: AbortSignal,
    /**
     * 网络搜索补充资料（可选，Spec: add-agent-web-search-tool）。
     *
     * 启用网络搜索时由编排服务在 AUTHORING 阶段按维度名 + 主题派生 query 调用 webSearch 获取，
     * 连同原始 query 一并传入；实现方将其格式化后注入 LLM 系统提示词作为参考上下文。
     * 未启用网络搜索时为 undefined，行为与原实现一致（向后兼容）。
     */
    researchContext?: {
      /** 触发本次搜索的 query（便于日志/调试） */
      query: string;
      /** 搜索结果数组 */
      results: Array<{ title: string; snippet: string; url: string }>;
    }
  ): Promise<Array<{
    name: string;
    content: string;
    keys: string[];
    secondaryKeys?: string[];
    comment?: string;
  }>>;
}

/**
 * steerEngine 注入点（仅暴露 enqueueSteer，编排服务仅需此方法）。
 */
export interface ISteerSink {
  enqueueSteer(params: {
    sessionId: string;
    content: string;
    source: 'user' | 'system' | 'agent';
    label?: string;
  }): Promise<string>;
}

/**
 * goalTracker 注入点（仅暴露 createGoal/updateStatus）。
 */
export interface IGoalSink {
  createGoal(params: {
    sessionId: string;
    objective: string;
  }): Promise<unknown>;
  updateStatus(params: {
    sessionId: string;
    status: 'complete' | 'blocked';
    note?: string;
    blocker?: string;
    actor?: 'user' | 'agent' | 'system';
  }): Promise<unknown>;
}

/**
 * 编排服务依赖注入容器。
 */
export interface WorldBookAuthoringServiceDeps {
  planningService: IPlanningServices;
  auditService: IAuditServices;
  tools: IAuthoringTools;
  entryGenerator: IEntryGenerator;
  /** MemoryStore（可选，未注入时降级为内存 Map，仅测试用） */
  memoryStore?: IMemoryProvider;
  /** SteerEngine（可选，未注入时跳过 steer 注入） */
  steerEngine?: ISteerSink;
  /** GoalTracker（可选，未注入时跳过目标追踪） */
  goalTracker?: IGoalSink;
  /** sleep 函数（测试可注入快进），默认 setTimeout */
  sleep?: (ms: number) => Promise<void>;
}

// ==================== 内部会话类型 ====================

/**
 * 编排服务内部会话（扩展 AuthoringSession，附加运行时字段）。
 *
 * 运行时字段（abortController / answerResolver 等）不持久化到 MemoryStore，
 * 仅存在于内存中。持久化时只序列化 AuthoringSession 部分。
 */
interface InternalSession extends AuthoringSession {
  /** AbortController（取消用，运行时） */
  abortController?: AbortController;
  /** 用户回答 resolver（PLANNING 等待回答时设置，运行时） */
  answerResolver?: (answers: Array<{ questionId: string; question: string; answer?: string; skipped: boolean }>) => void;
  /** 回答超时定时器（运行时） */
  answerTimeout?: ReturnType<typeof setTimeout>;
  /** 待回答的澄清问题（运行时） */
  pendingQuestions?: Array<{ id: string; question: string; why: string }>;
  /** 原始澄清问题（含 why，用于构建 plan 时回填） */
  originalQuestions?: Array<{ id: string; question: string; why: string }>;
  /** 会话总超时定时器（运行时） */
  sessionTimeout?: ReturnType<typeof setTimeout>;
  /** 当前用户提示（运行时，便于 resume） */
  userPrompt?: string;
  /** 当前配置（运行时，便于 resume） */
  config?: WorldBookAuthoringConfig;
  /** 当前进度回调（运行时） */
  onProgress?: WorldBookAuthoringProgressCallback;
  /** 维度失败计数器（dimId → 连续失败次数，用于阻塞判定） */
  dimensionFailureCount?: Map<string, number>;
  /**
   * 网络搜索是否成功使用过至少一次（Spec: add-agent-web-search-tool）。
   *
   * 运行时字段，不持久化。PLANNING / AUTHORING 阶段每次 webSearch 调用成功
   * （未抛异常即视为成功，即使返回空结果）后置 true。AUDITING 阶段将此标记
   * 写入 `auditReport.metadata.webSearchUsed`。未启用 / 全部失败时保持 false。
   */
  webSearchUsed?: boolean;
}

// ==================== 工具函数 ====================

/**
 * 生成会话 ID。
 * 格式：wba_<timestamp>_<random>
 */
function generateSessionId(): string {
  return `wba_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

/**
 * 链接外部 AbortSignal 到内部 AbortController。
 *
 * 若外部 signal 已 abort，立即 abort 内部；否则监听 abort 事件转发。
 */
function linkAbortSignals(
  external: AbortSignal | undefined,
  internal: AbortController
): void {
  if (!external) return;
  if (external.aborted) {
    internal.abort(external.reason);
    return;
  }
  external.addEventListener(
    'abort',
    () => internal.abort(external.reason),
    { once: true }
  );
}

/**
 * 从 createEntry 工具返回的 content 中解析新条目 UID。
 *
 * createEntry 成功时 content 格式：
 *   "Entry created successfully as draft...\n- UID: 5\n- Name: ..."
 */
function parseEntryUidFromToolResult(result: ToolExecutionResult): number | string | undefined {
  if (!result.success) return undefined;
  const match = result.content.match(/UID:\s*(\d+)/);
  if (match) return parseInt(match[1], 10);
  return undefined;
}

/**
 * 截断字符串到指定长度（超出部分用 "..." 标记）。
 *
 * 用于 ThoughtStep.inputSummary / outputSummary 的长度限制（默认 300 字符）。
 */
function truncate(s: string, max = 300): string {
  return s.length > max ? s.slice(0, max) + '...' : s;
}

// ==================== 主服务实现 ====================

/**
 * 世界书编写智能体编排服务。
 *
 * 实现 `WorldBookAuthoringService` 类，导出单例 `worldbookAuthoringService`。
 *
 * 用法（运行时）：
 * ```ts
 * import { worldbookAuthoringService } from './worldbookAuthoringService';
 * const result = await worldbookAuthoringService.run(request);
 * ```
 *
 * 用法（测试，注入 mock 依赖）：
 * ```ts
 * const service = new WorldBookAuthoringService({
 *   planningService: mockPlanning,
 *   auditService: mockAudit,
 *   tools: mockTools,
 *   entryGenerator: mockGen,
 *   memoryStore: mockMemory,
 *   steerEngine: mockSteer,
 *   goalTracker: mockGoal,
 *   sleep: async () => {},  // 快进
 * });
 * ```
 */
export class WorldBookAuthoringService {
  private readonly deps: WorldBookAuthoringServiceDeps;
  private readonly sleep: (ms: number) => Promise<void>;

  /** 活跃会话映射：sessionId → InternalSession */
  private readonly sessions = new Map<string, InternalSession>();
  /** worldBookPath → sessionId（单实例守卫） */
  private readonly pathToSession = new Map<string, string>();

  constructor(deps: WorldBookAuthoringServiceDeps) {
    this.deps = deps;
    this.sleep = deps.sleep ?? ((ms: number) => new Promise<void>(resolve => setTimeout(resolve, ms)));
  }

  // ==================== SubTask 4.1: 状态机骨架 ====================

  /**
   * 启动编写会话（主入口，IPC `worldbookAgent:run` 调用）。
   *
   * 流程：
   *  1. 单实例守卫：同 worldBookPath 已有活跃会话 → 拒绝
   *  2. 创建 InternalSession（state=PLANNING）
   *  3. 创建 AbortController，链接外部 signal
   *  4. goalTracker.createGoal
   *  5. 执行状态机：PLANNING → AUTHORING → AUDITING → AWAITING_REVIEW → COMPLETE
   *  6. 返回结果
   */
  async run(request: WorldBookAuthoringRunRequest): Promise<WorldBookAuthoringRunResult> {
    // 单实例守卫
    const existingSessionId = this.pathToSession.get(request.worldBookPath);
    if (existingSessionId) {
      const existing = this.sessions.get(existingSessionId);
      if (existing && !existing.aborted && existing.state !== 'COMPLETE' && existing.state !== 'AWAITING_REVIEW') {
        return {
          success: false,
          sessionId: existingSessionId,
          finalState: existing.state,
          generatedEntryIds: existing.generatedEntryIds,
          totalDurationMs: 0,
          error: `WorldBook ${request.worldBookPath} already has an active authoring session: ${existingSessionId}`,
        };
      }
      // 旧会话已结束，清理映射
      this.pathToSession.delete(request.worldBookPath);
    }

    const startTime = Date.now();
    const sessionId = generateSessionId();
    const abortController = new AbortController();
    if (request.signal) {
      linkAbortSignals(request.signal, abortController);
    }

    const now = Date.now();
    const session: InternalSession = {
      id: sessionId,
      worldBookPath: request.worldBookPath,
      allowedWorldBookPaths: request.allowedWorldBookPaths ?? [request.worldBookPath],
      state: 'PLANNING',
      completedDimensions: [],
      generatedEntryIds: [],
      createdAt: now,
      updatedAt: now,
      abortController,
      userPrompt: request.userPrompt,
      config: request.config,
      onProgress: request.onProgress,
      dimensionFailureCount: new Map(),
    };

    this.sessions.set(sessionId, session);
    this.pathToSession.set(request.worldBookPath, sessionId);

    // 会话总超时（30 分钟）
    session.sessionTimeout = setTimeout(() => {
      if (!abortController.signal.aborted) {
        console.warn(`${LOG_PREFIX} Session ${sessionId} timed out after ${SESSION_TIMEOUT_MS}ms`);
        abortController.abort(new Error('Session timeout'));
      }
    }, SESSION_TIMEOUT_MS);

    // goalTracker.createGoal
    try {
      if (this.deps.goalTracker) {
        await this.deps.goalTracker.createGoal({
          sessionId,
          objective: `世界书编写: ${request.userPrompt.slice(0, 80)}`,
        });
      }
    } catch (err) {
      console.warn(`${LOG_PREFIX} goalTracker.createGoal failed:`, err);
      // 目标创建失败不阻塞会话
    }

    try {
      return await this.executeStateMachine(session, startTime);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.error(`${LOG_PREFIX} Session ${sessionId} failed:`, message);
      return {
        success: false,
        sessionId,
        finalState: session.aborted ? 'CANCELLED' : 'ERROR',
        generatedEntryIds: session.generatedEntryIds,
        totalDurationMs: Date.now() - startTime,
        error: message,
      };
    } finally {
      this.clearSessionTimeouts(session);
      // 不从 sessions Map 中删除（保留状态查询能力），但释放 pathToSession 守卫
      if (this.pathToSession.get(session.worldBookPath) === sessionId) {
        this.pathToSession.delete(session.worldBookPath);
      }
    }
  }

  /**
   * 执行状态机核心循环。
   *
   * 按 PLANNING → AUTHORING → AUDITING → AWAITING_REVIEW → COMPLETE 顺序执行。
   * 每个状态转移后持久化 session 到 memoryStore。
   */
  private async executeStateMachine(
    session: InternalSession,
    startTime: number
  ): Promise<WorldBookAuthoringRunResult> {
    // PLANNING
    if (session.state === 'PLANNING') {
      await this.runPlanning(session);
    }
    if (session.abortController?.signal.aborted) {
      return this.buildCancelledResult(session, startTime);
    }

    // AUTHORING
    if (session.state === 'AUTHORING') {
      await this.runAuthoring(session);
    }
    if (session.abortController?.signal.aborted) {
      return this.buildCancelledResult(session, startTime);
    }

    // AUDITING
    if (session.state === 'AUDITING') {
      await this.runAuditing(session);
    }
    if (session.abortController?.signal.aborted) {
      return this.buildCancelledResult(session, startTime);
    }

    // AWAITING_REVIEW → COMPLETE
    if (session.state === 'AWAITING_REVIEW') {
      await this.transitionState(session, 'COMPLETE');
    }

    // goalTracker complete
    try {
      if (this.deps.goalTracker) {
        await this.deps.goalTracker.updateStatus({
          sessionId: session.id,
          status: 'complete',
          note: `会话完成，生成 ${session.generatedEntryIds.length} 个草稿条目`,
          actor: 'agent',
        });
      }
    } catch (err) {
      console.warn(`${LOG_PREFIX} goalTracker.updateStatus(complete) failed:`, err);
    }

    return {
      success: true,
      sessionId: session.id,
      finalState: session.state,
      generatedEntryIds: session.generatedEntryIds,
      auditReport: session.auditReport,
      totalDurationMs: Date.now() - startTime,
    };
  }

  // ==================== SubTask 4.2: PLANNING 阶段 ====================

  /**
   * PLANNING 阶段执行。
   *
   * 流程：
   *  1. analyzePrompt（LLM 分析用户提示）
   *  2. generateClarifyingQuestions（LLM 生成澄清问题）
   *  3. 等待用户回答（通过 onProgress 推送问题，submitAnswers 唤醒，超时跳过）
   *  4. buildPlan（综合回答生成计划）
   *  5. expandDimensions（自驱扩展维度）
   *  6. 状态转移至 AUTHORING
   */
  private async runPlanning(session: InternalSession): Promise<void> {
    const { userPrompt, config } = session;
    if (!userPrompt || !config) {
      throw new Error('PLANNING 缺少 userPrompt 或 config');
    }

    // Spec: add-agent-web-search-tool — PLANNING 阶段网络搜索补充上下文
    // 在 analyzePrompt 之前：用用户初始提示派生 query 调用 webSearch，
    // 结果格式化为 researchContext 字符串传给 analyzePrompt（注入 LLM 系统提示词）。
    // try/catch 容错已在 performWebSearch 内部处理，此处不额外 try/catch。
    let planningResearchContext: string | undefined;
    if (this.isWebSearchEnabled(session)) {
      // 推送 planning_researching 进度事件
      this.emitProgress(session, {
        phase: 'planning_researching',
        entriesGenerated: 0,
        targetEntries: 0,
        currentActivity: '正在搜索相关资料...',
        message: '正在搜索相关资料补充上下文...',
      });
      // 用用户初始提示前 100 字符派生搜索 query（避免过长 query 影响搜索质量）
      const searchQuery = userPrompt.slice(0, 100);
      const searchStartTime = Date.now();
      const results = await this.performWebSearch(
        session,
        searchQuery,
        config.webSearchMaxResults
      );
      // 采集网络搜索思考步骤（performWebSearch 内部已容错，此处仅记录成功路径）
      try {
        this.emitThoughtStep(session, 'planning_researching', {
          type: 'tool_call',
          purpose: `搜索资料：${searchQuery}`,
          inputSummary: truncate(searchQuery),
          outputSummary: `找到 ${results.length} 条结果：${results[0]?.title ?? ''}`,
          durationMs: Date.now() - searchStartTime,
          success: true,
        });
      } catch { /* 采集失败不影响主流程 */ }
      planningResearchContext = this.formatResearchContext(results) || undefined;
    }

    // 1. analyzePrompt
    this.emitProgress(session, {
      phase: 'planning_analyzing',
      entriesGenerated: 0,
      targetEntries: 0,
      currentActivity: '正在分析用户提示...',
      message: `分析提示：${userPrompt.slice(0, 60)}`,
    });

    const analyzeStartTime = Date.now();
    const promptAnalysis = await this.retryLLMCall(() =>
      this.deps.planningService.analyzePrompt(userPrompt, planningResearchContext)
    );
    // 采集思考步骤：分析用户提示
    try {
      this.emitThoughtStep(session, 'planning_analyzing', {
        type: 'llm_call',
        purpose: '分析用户提示',
        inputSummary: truncate(userPrompt),
        outputSummary: truncate(`识别 ${promptAnalysis.dimensions.length} 个维度，${promptAnalysis.ambiguities.length} 个模糊点，主题：${promptAnalysis.themeSummary}`),
        durationMs: Date.now() - analyzeStartTime,
        success: true,
      });
    } catch { /* 采集失败不影响主流程 */ }

    // 2. generateClarifyingQuestions
    this.emitProgress(session, {
      phase: 'planning_analyzing',
      entriesGenerated: 0,
      targetEntries: 0,
      currentActivity: '正在生成澄清问题...',
      message: '生成澄清问题中',
    });

    const clarifyStartTime = Date.now();
    const questions = await this.retryLLMCall(() =>
      this.deps.planningService.generateClarifyingQuestions(promptAnalysis)
    );
    // 采集思考步骤：生成澄清问题
    try {
      this.emitThoughtStep(session, 'planning_analyzing', {
        type: 'llm_call',
        purpose: '生成澄清问题',
        inputSummary: `分析结果：${promptAnalysis.dimensions.length} 个维度`,
        outputSummary: `生成 ${questions.length} 个问题：${questions[0]?.question ?? ''}`,
        durationMs: Date.now() - clarifyStartTime,
        success: true,
      });
    } catch { /* 采集失败不影响主流程 */ }

    session.originalQuestions = questions;

    // 3. 等待用户回答
    const answers = await this.waitForClarifyAnswers(session, questions);

    // 4. buildPlan
    this.emitProgress(session, {
      phase: 'planning_building',
      entriesGenerated: 0,
      targetEntries: 0,
      currentActivity: '正在构建编写计划...',
      message: '综合用户回答构建计划',
    });

    const planStartTime = Date.now();
    const plan = await this.retryLLMCall(() =>
      this.deps.planningService.buildPlan(userPrompt, answers, promptAnalysis)
    );
    // 采集思考步骤：构建编写计划
    try {
      this.emitThoughtStep(session, 'planning_building', {
        type: 'llm_call',
        purpose: '构建编写计划',
        outputSummary: `计划包含 ${plan.goal.dimensions.length} 个维度，目标 ${plan.goal.targetTotalEntries} 个条目`,
        durationMs: Date.now() - planStartTime,
        success: true,
      });
    } catch { /* 采集失败不影响主流程 */ }

    // 回填 clarifyingQuestions 的 why 字段（buildPlan 中 why 留空，此处合并）
    plan.clarifyingQuestions = plan.clarifyingQuestions.map((q, i) => ({
      ...q,
      why: questions[i]?.why ?? q.why,
    }));

    // 5. expandDimensions
    const expandedPlan = await this.retryLLMCall(() =>
      this.deps.planningService.expandDimensions(plan)
    );

    session.plan = expandedPlan;
    session.goal = expandedPlan.goal;

    // 6. 状态转移至 AUTHORING
    await this.transitionState(session, 'AUTHORING');
  }

  /**
   * 等待用户回答澄清问题（关键设计：Promise + resolver + 超时）。
   *
   * 机制：
   *  - 通过 onProgress 推送 {phase: 'planning_clarifying', clarifyingQuestions}
   *  - 创建 Promise，将 resolver 存入 session.answerResolver
   *  - 设置 10 分钟超时，超时后所有未回答问题标 skipped=true
   *  - submitAnswers(sessionId, answers) 调用 resolver 唤醒
   *  - 取消时 reject Promise
   *
   * @returns 用户回答列表（含 skipped 标记）
   */
  private async waitForClarifyAnswers(
    session: InternalSession,
    questions: Array<{ id: string; question: string; why: string }>
  ): Promise<Array<{ questionId: string; question: string; answer?: string; skipped: boolean }>> {
    if (questions.length === 0) {
      return [];
    }

    // 推送澄清问题事件（IPC handler 桥接到渲染进程，触发 UI 显示问题）
    this.emitProgress(session, {
      phase: 'planning_clarifying',
      entriesGenerated: 0,
      targetEntries: 0,
      currentActivity: '等待用户回答澄清问题...',
      message: `请回答 ${questions.length} 个澄清问题`,
    });

    // 附加问题列表到事件（通过 metadata 传递，AuthoringProgressEvent 无 clarifyingQuestions 字段，
    // 但 onProgress 回调可接收扩展字段；IPC handler 在桥接时读取）
    // 注：为兼容类型，此处通过强制转型附加字段
    const extendedEvent: AuthoringProgressEvent & { clarifyingQuestions?: Array<{ id: string; question: string; why: string }> } = {
      phase: 'planning_clarifying',
      entriesGenerated: 0,
      targetEntries: 0,
      currentActivity: '等待用户回答澄清问题...',
      message: `请回答 ${questions.length} 个澄清问题`,
      // 附带 sessionId，解决阻塞调用期间渲染进程 state.sessionId 仍为 null 的时序问题
      sessionId: session.id,
      timestamp: Date.now(),
      clarifyingQuestions: questions,
    };
    session.onProgress?.(extendedEvent);

    session.pendingQuestions = questions;

    // 创建 Promise 等待回答
    return new Promise<Array<{ questionId: string; question: string; answer?: string; skipped: boolean }>>(
      (resolve, reject) => {
        // 超时：10 分钟后自动跳过所有未回答问题
        session.answerTimeout = setTimeout(() => {
          if (session.answerResolver) {
            console.warn(`${LOG_PREFIX} Session ${session.id} clarify timeout, auto-skipping all questions`);
            const skippedAnswers = questions.map((q) => ({
              questionId: q.id,
              question: q.question,
              answer: undefined,
              skipped: true,
            }));
            session.answerResolver?.(skippedAnswers);
            session.answerResolver = undefined;
          }
        }, CLARIFY_TIMEOUT_MS);

        // 取消时 reject
        const onAbort = () => {
          if (session.answerResolver) {
            session.answerResolver = undefined;
            reject(new Error('用户取消了编写'));
          }
        };
        if (session.abortController?.signal.aborted) {
          onAbort();
          return;
        }
        session.abortController?.signal.addEventListener('abort', onAbort, { once: true });

        // 设置 resolver
        session.answerResolver = (answers) => {
          if (session.answerTimeout) {
            clearTimeout(session.answerTimeout);
            session.answerTimeout = undefined;
          }
          session.abortController?.signal.removeEventListener('abort', onAbort);
          resolve(answers);
        };
      }
    );
  }

  /**
   * 提交澄清问题回答（IPC handler 调用）。
   *
   * 唤醒 waitForClarifyAnswers 中等待的 Promise。
   *
   * @param sessionId 会话 ID
   * @param answers 用户回答列表
   * @returns 是否成功提交（会话不存在或未在等待回答时返回 false）
   */
  async submitAnswers(
    sessionId: string,
    answers: Array<{ questionId: string; answer?: string; skipped: boolean }>
  ): Promise<boolean> {
    const session = this.sessions.get(sessionId);
    if (!session || !session.answerResolver) {
      console.warn(`${LOG_PREFIX} submitAnswers: session ${sessionId} 不存在或未在等待回答`);
      return false;
    }

    // 合并原始问题文本（用户回答只含 questionId + answer，需补全 question 文本）
    const questions = session.pendingQuestions ?? [];
    const mergedAnswers = answers.map((a) => {
      const q = questions.find((qq) => qq.id === a.questionId);
      return {
        questionId: a.questionId,
        question: q?.question ?? '',
        answer: a.answer,
        skipped: a.skipped,
      };
    });

    // 对用户未提交的问题，补为 skipped
    for (const q of questions) {
      if (!mergedAnswers.some((a) => a.questionId === q.id)) {
        mergedAnswers.push({
          questionId: q.id,
          question: q.question,
          answer: undefined,
          skipped: true,
        });
      }
    }

    const resolver = session.answerResolver;
    session.answerResolver = undefined;
    resolver?.(mergedAnswers);
    return true;
  }

  // ==================== SubTask 4.3: AUTHORING 阶段 ====================

  /**
   * AUTHORING 阶段执行。
   *
   * 按 plan.goal.dimensions 顺序逐维度生成条目：
   *  - 跳过已完成的维度（断点续跑支持）
   *  - 每维度循环生成条目直到达到 targetEntryCount 或连续失败 3 次
   *  - 每 3 条触发微型审计（validateCompleteness + checkConsistency）
   *  - 发现问题注入 steer 消息
   *  - pacing 钳位（每轮间隔 pacingMinMs ~ pacingMaxMs）
   *  - 检查 abort signal
   *
   * 全维度完成 → 状态转移至 AUDITING
   */
  private async runAuthoring(session: InternalSession): Promise<void> {
    const plan = session.plan;
    if (!plan) {
      throw new Error('AUTHORING 缺少 plan');
    }

    const dimensions = plan.goal.dimensions;
    const totalDimensions = dimensions.length;
    const targetTotal = plan.goal.targetTotalEntries;

    this.emitProgress(session, {
      phase: 'authoring_generating',
      currentDimension: '',
      totalDimensions,
      completedDimensions: session.completedDimensions.length,
      entriesGenerated: session.generatedEntryIds.length,
      targetEntries: targetTotal,
      currentActivity: '开始自驱编写...',
      message: `共 ${totalDimensions} 个维度，目标 ${targetTotal} 个条目`,
    });

    for (const dimension of dimensions) {
      // 断点续跑：跳过已完成的维度
      if (session.completedDimensions.includes(dimension.id)) {
        continue;
      }

      // 检查取消
      if (session.abortController?.signal.aborted) {
        return;
      }

      await this.generateEntriesForDimension(session, dimension, totalDimensions, targetTotal);

      // 检查取消
      if (session.abortController?.signal.aborted) {
        return;
      }
    }

    // 全维度完成 → AUDITING
    await this.transitionState(session, 'AUDITING');
  }

  /**
   * 为单个维度生成条目。
   *
   * 循环生成直到达到 targetEntryCount 或连续失败 3 次：
   *  1. 调用 entryGenerator.generateEntriesForDimension（LLM 生成）
   *  2. 对每个生成条目调用 tools.createEntry（写草稿区）
   *  3. 每 3 条触发微型审计
   *  4. 发现问题注入 steer 消息
   *  5. pacing 钳位（每轮 sleep）
   *  6. 维度完成 → session.completedDimensions.push(dim.id) + goalTracker.updateStatus
   *  7. 连续失败 3 次 → goalTracker.updateStatus(blocked) + 推送 blocked 事件
   */
  private async generateEntriesForDimension(
    session: InternalSession,
    dimension: AuthoringDimension,
    totalDimensions: number,
    targetTotal: number
  ): Promise<void> {
    const plan = session.plan!;
    const config = session.config!;
    const targetCount = Math.min(
      dimension.targetEntryCount,
      config.maxEntriesPerDimension
    );

    let generatedForDim = 0;
    let consecutiveFailures = 0;
    const failureCounts = session.dimensionFailureCount ?? (session.dimensionFailureCount = new Map());

    this.emitProgress(session, {
      phase: 'authoring_generating',
      currentDimension: dimension.name,
      totalDimensions,
      completedDimensions: session.completedDimensions.length,
      entriesGenerated: session.generatedEntryIds.length,
      targetEntries: targetTotal,
      currentActivity: `正在生成「${dimension.name}」维度条目...`,
      message: `维度 ${dimension.name}：目标 ${targetCount} 个条目`,
    });

    // Spec: add-agent-web-search-tool — AUTHORING 阶段按维度名 + 主题派生 query 搜索
    // 在 generateEntriesForDimension 之前调用，结果作为 researchContext 传入。
    // 每维度搜索一次（在 while 循环外），重试时复用同一 researchContext。
    // try/catch 容错已在 performWebSearch 内部处理。
    let authoringResearchContext:
      | { query: string; results: Array<{ title: string; snippet: string; url: string }> }
      | undefined;
    if (this.isWebSearchEnabled(session)) {
      // 按维度名 + 主题派生搜索 query
      const theme = plan.goal.theme ?? '';
      const searchQuery = theme ? `${dimension.name} ${theme}` : dimension.name;
      const results = await this.performWebSearch(
        session,
        searchQuery,
        config.webSearchMaxResults
      );
      if (results.length > 0) {
        authoringResearchContext = { query: searchQuery, results };
      }
    }

    while (generatedForDim < targetCount && consecutiveFailures < DIMENSION_FAILURE_THRESHOLD) {
      // 检查取消
      if (session.abortController?.signal.aborted) {
        return;
      }

      try {
        // 读取已有条目（供 LLM 避免重复）
        const existingEntries = await this.readExistingEntries(session);

        // LLM 生成条目（重试 3 次）
        const genStartTime = Date.now();
        const drafts = await this.retryLLMCall(
          () => this.deps.entryGenerator.generateEntriesForDimension(
            dimension,
            plan,
            existingEntries,
            targetCount - generatedForDim,
            session.abortController?.signal,
            authoringResearchContext
          ),
          { label: `generateEntriesForDimension(${dimension.name})` }
        );
        // 采集思考步骤：生成维度条目
        try {
          this.emitThoughtStep(session, 'authoring_generating', {
            type: 'llm_call',
            purpose: `生成「${dimension.name}」维度条目`,
            inputSummary: `维度：${dimension.name}，目标：${targetCount} 个条目`,
            outputSummary: `成功生成 ${drafts.length} 个条目：${drafts[0]?.name ?? ''}`,
            durationMs: Date.now() - genStartTime,
            success: true,
          });
        } catch { /* 采集失败不影响主流程 */ }

        if (!drafts || drafts.length === 0) {
          throw new Error('LLM 未返回任何条目');
        }

        // 构造 ToolCallContext
        const toolContext: ToolCallContext = {
          mode: 'worldbook',
          allowedWorldBookPaths: session.allowedWorldBookPaths,
          sessionId: session.id,
        };

        // 逐条写入草稿区
        for (const draft of drafts) {
          if (session.abortController?.signal.aborted) return;

          if (generatedForDim >= targetCount) break;

          const createResult = await this.deps.tools.createEntry(
            {
              worldBookPath: session.worldBookPath,
              name: draft.name,
              content: draft.content,
              keys: draft.keys,
              secondaryKeys: draft.secondaryKeys,
              comment: draft.comment,
              dimensionId: dimension.id,
            },
            toolContext
          );

          if (createResult.success) {
            const uid = parseEntryUidFromToolResult(createResult);
            if (uid !== undefined) {
              session.generatedEntryIds.push(uid);
            }
            generatedForDim += 1;
            consecutiveFailures = 0;
            failureCounts.delete(dimension.id);

            this.emitProgress(session, {
              phase: 'authoring_generating',
              currentDimension: dimension.name,
              totalDimensions,
              completedDimensions: session.completedDimensions.length,
              entriesGenerated: session.generatedEntryIds.length,
              targetEntries: targetTotal,
              currentActivity: `已生成「${draft.name}」`,
              message: `维度 ${dimension.name}：${generatedForDim}/${targetCount}`,
              generatedEntries: drafts.slice(0, 5).map(d => ({
                name: d.name,
                content: (d.content ?? '').slice(0, 200),
              })),
            });

            // 每 N 条触发微型审计（按总条目数计，spec §SubTask 4.3 "每 3-5 条触发微型审计"）
            if (session.generatedEntryIds.length % MINI_AUDIT_INTERVAL === 0) {
              await this.runMiniAudit(session, dimension);
            }
          } else {
            console.warn(`${LOG_PREFIX} createEntry failed: ${createResult.content}`);
          }
        }

        // pacing 钳位（每轮 sleep）
        await this.applyPacing(session, config);

      } catch (err) {
        consecutiveFailures += 1;
        failureCounts.set(dimension.id, consecutiveFailures);
        const message = err instanceof Error ? err.message : String(err);
        console.warn(
          `${LOG_PREFIX} 维度 ${dimension.name} 生成失败（第 ${consecutiveFailures} 次）: ${message}`
        );

        if (consecutiveFailures < DIMENSION_FAILURE_THRESHOLD) {
          // pacing 后重试
          await this.applyPacing(session, config);
        }
      }
    }

    // 维度完成判定
    if (generatedForDim > 0) {
      session.completedDimensions.push(dimension.id);
      await this.persistSession(session);

      // goalTracker.updateStatus（note 记录进度，status 仍为 in_progress 由 updateStatus 内部处理）
      try {
        if (this.deps.goalTracker) {
          // 注：goalTracker.updateStatus 仅接受 'complete' | 'blocked'，
          // 此处用 complete 表示该维度完成（会话级 goal 在最终 complete 时再标记）
          // 但为避免提前 complete 整个 goal，此处不调用 updateStatus(complete)，
          // 仅在 3 次失败时调用 updateStatus(blocked)
        }
      } catch (err) {
        console.warn(`${LOG_PREFIX} goalTracker update for dimension ${dimension.id} failed:`, err);
      }

      this.emitProgress(session, {
        phase: 'authoring_generating',
        currentDimension: dimension.name,
        totalDimensions,
        completedDimensions: session.completedDimensions.length,
        entriesGenerated: session.generatedEntryIds.length,
        targetEntries: targetTotal,
        currentActivity: `维度「${dimension.name}」完成`,
        message: `已完成 ${session.completedDimensions.length}/${totalDimensions} 个维度`,
      });
    }

    // 连续失败 3 次 → goalTracker.markBlocked + 推送 blocked 事件
    if (consecutiveFailures >= DIMENSION_FAILURE_THRESHOLD) {
      console.warn(`${LOG_PREFIX} 维度 ${dimension.name} 连续失败 ${consecutiveFailures} 次，标记为阻塞`);

      try {
        if (this.deps.goalTracker) {
          await this.deps.goalTracker.updateStatus({
            sessionId: session.id,
            status: 'blocked',
            blocker: `dimension:${dimension.id}`,
            note: `维度 ${dimension.name} 连续生成失败 ${consecutiveFailures} 次`,
            actor: 'agent',
          });
        }
      } catch (err) {
        console.warn(`${LOG_PREFIX} goalTracker.updateStatus(blocked) failed:`, err);
      }

      this.emitProgress(session, {
        phase: 'error',
        currentDimension: dimension.name,
        totalDimensions,
        completedDimensions: session.completedDimensions.length,
        entriesGenerated: session.generatedEntryIds.length,
        targetEntries: targetTotal,
        currentActivity: `维度「${dimension.name}」生成受阻`,
        message: `维度 ${dimension.name} 连续失败 ${consecutiveFailures} 次，跳过`,
        error: `dimension ${dimension.name} blocked after ${consecutiveFailures} failures`,
      });
    }
  }

  /**
   * 微型审计（精简版，仅 completeness + consistency）。
   *
   * 读取草稿区条目 → 调用 auditService.validateCompleteness + checkConsistency
   * 发现问题 → 注入 steer 消息（如"条目 X 的关键词与内容不匹配"）
   */
  private async runMiniAudit(
    session: InternalSession,
    dimension: AuthoringDimension
  ): Promise<void> {
    const plan = session.plan;
    if (!plan) return;

    try {
      this.emitProgress(session, {
        phase: 'authoring_mini_audit',
        currentDimension: dimension.name,
        totalDimensions: plan.goal.dimensions.length,
        completedDimensions: session.completedDimensions.length,
        entriesGenerated: session.generatedEntryIds.length,
        targetEntries: plan.goal.targetTotalEntries,
        currentActivity: `微型审计「${dimension.name}」...`,
        message: `维度 ${dimension.name} 触发微型审计`,
      });

      const entries = await this.readExistingEntries(session);

      // 并行执行完整性 + 一致性审计
      const miniAuditStartTime = Date.now();
      const [completeness, consistency] = await Promise.all([
        this.deps.auditService.validateCompleteness(plan, entries),
        this.deps.auditService.checkConsistency(entries),
      ]);
      // 采集思考步骤：微型审计决策
      try {
        this.emitThoughtStep(session, 'authoring_mini_audit', {
          type: 'decision',
          purpose: `微型审计「${dimension.name}」`,
          outputSummary: `完整性问题：${completeness.missingFields.length}，一致性问题：${consistency.issues.length}`,
          durationMs: Date.now() - miniAuditStartTime,
          success: true,
        });
      } catch { /* 采集失败不影响主流程 */ }

      // 发现问题 → 注入 steer 消息
      if (this.deps.steerEngine) {
        if (completeness.missingFields.length > 0) {
          const desc = completeness.missingFields
            .map((m) => `条目 ${m.entryUid} 缺失字段 ${m.field}（${m.reason}）`)
            .join('；');
          await this.deps.steerEngine.enqueueSteer({
            sessionId: session.id,
            content: `[微型审计-完整性] 维度 ${dimension.name} 发现问题：${desc}。请在后续生成中避免缺失必填字段（key 非空数组 / content 非空 / comment 或 name 非空）。`,
            source: 'agent',
            label: `mini-audit:completeness:${dimension.id}`,
          }).catch((err) => console.warn(`${LOG_PREFIX} steer enqueue failed:`, err));
        }

        const blockingIssues = consistency.issues.filter(
          (i) => i.severity === 'error' || i.severity === 'critical'
        );
        if (blockingIssues.length > 0) {
          const desc = blockingIssues
            .map((i) => `${i.kind}: ${i.description}（涉及条目 ${i.entryIds.join(', ')}）`)
            .join('；');
          await this.deps.steerEngine.enqueueSteer({
            sessionId: session.id,
            content: `[微型审计-一致性] 维度 ${dimension.name} 发现问题：${desc}。请在后续生成中避免与已有条目设定矛盾。`,
            source: 'agent',
            label: `mini-audit:consistency:${dimension.id}`,
          }).catch((err) => console.warn(`${LOG_PREFIX} steer enqueue failed:`, err));
        }
      }

      this.emitProgress(session, {
        phase: 'authoring_mini_audit',
        currentDimension: dimension.name,
        totalDimensions: plan.goal.dimensions.length,
        completedDimensions: session.completedDimensions.length,
        entriesGenerated: session.generatedEntryIds.length,
        targetEntries: plan.goal.targetTotalEntries,
        currentActivity: `微型审计完成：${completeness.missingFields.length} 个完整性问题，${consistency.issues.length} 个一致性问题`,
        message: `维度 ${dimension.name} 微型审计完成`,
        auditDetail: {
          type: 'mini',
          dimension: dimension.name,
          completenessIssues: completeness.missingFields.length,
          consistencyIssues: consistency.issues.length,
          issues: (consistency.issues ?? [])
            .filter(i => i.severity === 'error' || i.severity === 'critical')
            .slice(0, 5)
            .map(i => ({
              description: `${i.kind}: ${i.description}`,
              entryIds: i.entryIds.map(String),
            })),
        },
      });
    } catch (err) {
      console.warn(`${LOG_PREFIX} runMiniAudit failed:`, err);
      // 微型审计失败不阻塞生成
    }
  }

  /**
   * 应用 pacing 钳位（spec §设计理念 §6 防失控调度）。
   *
   * 使用 resolvePacedNextRunAtMs 将"提议延迟"钳位到 [pacingMinMs, pacingMaxMs]。
   * 提议延迟为 0（立即下一轮），钳位后 = pacingMinMs（最小间隔）。
   */
  private async applyPacing(
    _session: InternalSession,
    config: WorldBookAuthoringConfig
  ): Promise<void> {
    const minMs = config.pacingMinMs ?? 0;
    const maxMs = config.pacingMaxMs ?? 30_000;
    if (minMs <= 0) return;

    try {
      // 提议延迟 0，钳位到 [minMs, maxMs] → 实际 sleep minMs
      const sleepMs = resolvePacedNextRunAtMs({
        nowMs: Date.now(),
        delayMs: 0,
        pacing: { min: `${minMs}ms`, max: `${maxMs}ms` },
      }) - Date.now();
      if (sleepMs > 0) {
        await this.sleep(sleepMs);
      }
    } catch {
      // pacing 解析失败，降级为直接 sleep minMs
      if (minMs > 0) {
        await this.sleep(minMs);
      }
    }
  }

  // ==================== SubTask 4.4: AUDITING 阶段 ====================

  /**
   * AUDITING 阶段执行。
   *
   * 流程：
   *  1. 读取全部草稿区条目
   *  2. 调用 auditService.runFullAudit（三维度审计）
   *  3. 小问题自动修复（config.enableAutoFix=true 时）
   *  4. 状态转移至 AWAITING_REVIEW
   *  5. 推送 audit:complete 事件
   */
  private async runAuditing(session: InternalSession): Promise<void> {
    const plan = session.plan;
    if (!plan) {
      throw new Error('AUDITING 缺少 plan');
    }

    this.emitProgress(session, {
      phase: 'auditing_full',
      totalDimensions: plan.goal.dimensions.length,
      completedDimensions: session.completedDimensions.length,
      entriesGenerated: session.generatedEntryIds.length,
      targetEntries: plan.goal.targetTotalEntries,
      currentActivity: '正在执行完整审计...',
      message: '三维度审计：完整性 / 一致性 / 符合度',
    });

    const entries = await this.readExistingEntries(session);
    const clarifications = (plan.userAnswers ?? []).map((a) => ({
      questionId: a.questionId,
      answer: a.answer,
    }));

    const auditReport = await this.deps.auditService.runFullAudit(
      plan,
      entries,
      session.userPrompt ?? '',
      clarifications
    );

    // Spec: add-agent-web-search-tool — 在审计报告 metadata 中标记 webSearchUsed
    // （成功至少一次为 true，全部失败/未启用为 false）。合并已有 metadata 避免覆盖审计服务产出的字段。
    auditReport.metadata = {
      ...(auditReport.metadata ?? {}),
      webSearchUsed: session.webSearchUsed === true,
    };

    session.auditReport = auditReport;

    // 自动修复
    if (session.config?.enableAutoFix) {
      await this.autoFixIssues(session, auditReport);
    }

    await this.transitionState(session, 'AWAITING_REVIEW');

    this.emitProgress(session, {
      phase: 'auditing_fixing',
      totalDimensions: plan.goal.dimensions.length,
      completedDimensions: session.completedDimensions.length,
      entriesGenerated: session.generatedEntryIds.length,
      targetEntries: plan.goal.targetTotalEntries,
      currentActivity: '审计完成，等待用户审阅',
      message: `审计完成：${auditReport.overallPassed ? '通过' : '未通过'}（分数 ${auditReport.overallScore.toFixed(2)}）`,
      auditDetail: {
        type: 'full',
        overallPassed: auditReport.overallPassed,
        overallScore: auditReport.overallScore,
        completeness: `通过: ${auditReport.completeness.passed ? '是' : '否'}，缺失字段 ${auditReport.completeness.missingFields.length} 个，未覆盖维度 ${auditReport.completeness.uncoveredDimensions.length} 个`,
        consistency: `通过: ${auditReport.consistency.passed ? '是' : '否'}，问题 ${auditReport.consistency.issues.length} 个`,
        conformance: `通过: ${auditReport.conformance.passed ? '是' : '否'}，符合 ${auditReport.conformance.conformantCount}/${auditReport.conformance.totalCount}`,
        autoFixesApplied: auditReport.autoFixes.filter(f => f.applied).length,
        userDecisions: auditReport.userDecisions.slice(0, 5).map(d => ({
          description: d.description,
          severity: String(d.severity),
        })),
      },
    });
  }

  /**
   * 自动修复审计问题（spec §ADDED Requirements 审计闭环阶段自动修复或提示）。
   *
   * 修复策略：
   *  - 缺失字段（key）：调用 tools.generateKeywords 重新生成关键词
   *  - 未覆盖维度：调用 tools.createEntry 补充 1 个条目
   *  - 未达标维度：调用 entryGenerator + createEntry 补充条目
   *  - 修复后标记 autoFixes[i].applied = true
   *
   * 大问题（critical/error）不自动修复，汇总在 auditReport.userDecisions 中。
   */
  private async autoFixIssues(
    session: InternalSession,
    auditReport: AuditReport
  ): Promise<void> {
    const plan = session.plan!;
    const toolContext: ToolCallContext = {
      mode: 'worldbook',
      allowedWorldBookPaths: session.allowedWorldBookPaths,
      sessionId: session.id,
    };

    let fixedCount = 0;

    for (const fix of auditReport.autoFixes) {
      if (fix.applied) continue;
      if (fix.severity === 'critical' || fix.severity === 'error') continue; // 大问题不自动修复

      try {
        // 缺失字段：key → 调用 generateKeywords
        if (fix.field === 'key' && typeof fix.entryUid === 'number') {
          // 读取条目内容，基于内容重新生成关键词
          const entries = await this.readExistingEntries(session);
          const entry = entries.find((e) => e.uid === fix.entryUid || e.id === fix.entryUid);
          if (entry && typeof entry.content === 'string') {
            // 用 content 前 N 个词作为简易关键词（避免再次调用 LLM）
            const words = (entry.content as string).split(/[\s,，。.]+/).filter((w) => w.length > 1).slice(0, 5);
            const result = await this.deps.tools.generateKeywords(
              {
                worldBookPath: session.worldBookPath,
                entryUid: fix.entryUid,
                keys: words,
              },
              toolContext
            );
            if (result.success) {
              fix.applied = true;
              fixedCount += 1;
            }
          }
        }

        // 未覆盖维度 / 未达标维度：调用 createEntry 补充条目
        if (fix.field === 'entries' && typeof fix.entryUid === 'string' && fix.entryUid.startsWith('dim:')) {
          const dimId = fix.entryUid.slice(4);
          const dim = plan.goal.dimensions.find((d) => d.id === dimId);
          if (dim) {
            const drafts = await this.retryLLMCall(
              async () => this.deps.entryGenerator.generateEntriesForDimension(
                dim,
                plan,
                await this.readExistingEntries(session),
                1,
                session.abortController?.signal
              ),
              { label: `autoFix:${dim.name}` }
            );
            if (drafts.length > 0) {
              const result = await this.deps.tools.createEntry(
                {
                  worldBookPath: session.worldBookPath,
                  name: drafts[0].name,
                  content: drafts[0].content,
                  keys: drafts[0].keys,
                  secondaryKeys: drafts[0].secondaryKeys,
                  comment: drafts[0].comment,
                  dimensionId: dim.id,
                },
                toolContext
              );
              if (result.success) {
                const uid = parseEntryUidFromToolResult(result);
                if (uid !== undefined) {
                  session.generatedEntryIds.push(uid);
                }
                fix.applied = true;
                fixedCount += 1;
              }
            }
          }
        }
      } catch (err) {
        console.warn(`${LOG_PREFIX} autoFix failed for ${fix.entryUid}.${fix.field}:`, err);
      }
    }

    if (fixedCount > 0) {
      console.log(`${LOG_PREFIX} autoFix applied ${fixedCount}/${auditReport.autoFixes.length} fixes`);
      // 更新 session 中的 auditReport（autoFixes.applied 已就地修改）
      session.auditReport = auditReport;
      await this.persistSession(session);
    }
  }

  // ==================== SubTask 4.5: 断点续跑 ====================

  /**
   * 从断点恢复会话。
   *
   * 流程：
   *  1. 从内存 Map 或 memoryStore 恢复 session
   *  2. 创建新的 AbortController
   *  3. 从当前状态继续执行状态机
   *
   * @param sessionId 会话 ID
   * @param options 进度回调 + signal（可选）
   */
  async resumeSession(
    sessionId: string,
    options?: {
      onProgress?: WorldBookAuthoringProgressCallback;
      signal?: AbortSignal;
    }
  ): Promise<WorldBookAuthoringRunResult> {
    const startTime = Date.now();

    // 1. 从内存或 memoryStore 恢复
    let session: InternalSession | undefined = this.sessions.get(sessionId);
    if (!session) {
      const restored = await this.restoreSessionFromMemory(sessionId);
      if (!restored) {
        return {
          success: false,
          sessionId,
          finalState: 'ERROR',
          generatedEntryIds: [],
          totalDurationMs: 0,
          error: `Session ${sessionId} not found in memory or memoryStore`,
        };
      }
      session = restored;
    }

    // 已完成或等待审阅的会话不恢复
    if (session.state === 'COMPLETE') {
      return {
        success: true,
        sessionId,
        finalState: 'COMPLETE',
        generatedEntryIds: session.generatedEntryIds,
        auditReport: session.auditReport,
        totalDurationMs: 0,
      };
    }
    if (session.state === 'AWAITING_REVIEW') {
      return {
        success: true,
        sessionId,
        finalState: 'AWAITING_REVIEW',
        generatedEntryIds: session.generatedEntryIds,
        auditReport: session.auditReport,
        totalDurationMs: 0,
      };
    }

    // 2. 创建新 AbortController
    const abortController = new AbortController();
    if (options?.signal) {
      linkAbortSignals(options.signal, abortController);
    }
    session.abortController = abortController;
    if (options?.onProgress) {
      session.onProgress = options.onProgress;
    }
    session.aborted = false;
    session.abortReason = undefined;

    // 重新注册单实例守卫
    const existingSessionId = this.pathToSession.get(session.worldBookPath);
    if (existingSessionId && existingSessionId !== sessionId) {
      // 已有其他会话占用，但允许恢复（清理旧映射）
      this.pathToSession.delete(session.worldBookPath);
    }
    this.pathToSession.set(session.worldBookPath, sessionId);
    this.sessions.set(sessionId, session);

    // 会话总超时
    session.sessionTimeout = setTimeout(() => {
      if (!abortController.signal.aborted) {
        console.warn(`${LOG_PREFIX} Resumed session ${sessionId} timed out`);
        abortController.abort(new Error('Session timeout'));
      }
    }, SESSION_TIMEOUT_MS);

    try {
      // PLANNING 状态的会话：从头开始 PLANNING（无法恢复 LLM 中间状态）
      if (session.state === 'PLANNING' && !session.plan) {
        return await this.executeStateMachine(session, startTime);
      }
      // AUTHORING / AUDITING 状态：从当前状态继续
      return await this.executeStateMachine(session, startTime);
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      return {
        success: false,
        sessionId,
        finalState: session.aborted ? 'CANCELLED' : 'ERROR',
        generatedEntryIds: session.generatedEntryIds,
        totalDurationMs: Date.now() - startTime,
        error: message,
      };
    } finally {
      this.clearSessionTimeouts(session);
      if (this.pathToSession.get(session.worldBookPath) === sessionId) {
        this.pathToSession.delete(session.worldBookPath);
      }
    }
  }

  /**
   * 从 memoryStore 恢复 session。
   */
  private async restoreSessionFromMemory(sessionId: string): Promise<InternalSession | null> {
    if (!this.deps.memoryStore) return null;

    try {
      const results = await this.deps.memoryStore.search({
        query: sessionId,
        types: ['agent'],
        sessionId,
        limit: 50,
      });

      const sessionEntries = results
        .filter((m) => (m.metadata as Record<string, unknown>)?.kind === 'worldbook-authoring-session')
        .sort((a, b) => (b.timestamp ?? 0) - (a.timestamp ?? 0));

      if (sessionEntries.length === 0) return null;

      const latest = sessionEntries[0];
      const sessionData = (latest.metadata as Record<string, unknown>)?.session as string;
      if (!sessionData) return null;

      const parsed = JSON.parse(sessionData) as AuthoringSession;
      return {
        ...parsed,
        dimensionFailureCount: new Map(),
      };
    } catch (err) {
      console.warn(`${LOG_PREFIX} restoreSessionFromMemory failed:`, err);
      return null;
    }
  }

  /**
   * 查询会话当前状态。
   */
  getSessionStatus(sessionId: string): {
    found: boolean;
    state?: AuthoringState | 'CANCELLED' | 'ERROR';
    session?: AuthoringSession;
  } {
    const session = this.sessions.get(sessionId);
    if (session) {
      return {
        found: true,
        state: session.aborted ? 'CANCELLED' : session.state,
        session: this.serializeSession(session),
      };
    }
    return { found: false };
  }

  // ==================== SubTask 4.1: 取消机制 ====================

  /**
   * 取消会话（IPC `worldbookAgent:cancel` 调用）。
   *
   * 触发 AbortController.abort()，编排循环在下一次 checkpoint 检测到取消信号后停止。
   * 已生成的草稿条目保留在待审阅区（spec §ADDED Requirements 主动取消）。
   */
  cancel(sessionId: string): boolean {
    const session = this.sessions.get(sessionId);
    if (!session) {
      console.warn(`${LOG_PREFIX} cancel: session ${sessionId} not found`);
      return false;
    }

    session.aborted = true;
    session.abortReason = '用户主动取消';
    session.abortController?.abort(new Error('用户取消了编写'));

    // 若在等待澄清问题回答，reject Promise
    if (session.answerResolver) {
      // answerResolver 已通过 abort 事件的监听器 reject，此处清理
      session.answerResolver = undefined;
      if (session.answerTimeout) {
        clearTimeout(session.answerTimeout);
        session.answerTimeout = undefined;
      }
    }

    this.emitProgress(session, {
      phase: 'cancelled',
      entriesGenerated: session.generatedEntryIds.length,
      targetEntries: session.plan?.goal.targetTotalEntries ?? 0,
      currentActivity: '会话已取消',
      message: '用户取消了编写，已生成的草稿条目保留',
    });

    return true;
  }

  // ==================== 内部辅助方法 ====================

  /**
   * 状态转移 + 持久化。
   *
   * @param session 会话
   * @param newState 新状态
   */
  private async transitionState(
    session: InternalSession,
    newState: AuthoringState
  ): Promise<void> {
    const oldState = session.state;
    session.state = newState;
    session.updatedAt = Date.now();
    console.log(`${LOG_PREFIX} Session ${session.id}: ${oldState} → ${newState}`);

    await this.persistSession(session);

    // AWAITING_REVIEW 推送事件
    if (newState === 'AWAITING_REVIEW') {
      this.emitProgress(session, {
        phase: 'awaiting_review',
        totalDimensions: session.plan?.goal.dimensions.length ?? 0,
        completedDimensions: session.completedDimensions.length,
        entriesGenerated: session.generatedEntryIds.length,
        targetEntries: session.plan?.goal.targetTotalEntries ?? 0,
        currentActivity: '等待用户审阅草稿条目',
        message: '编写完成，请前往待审阅区审批草稿条目',
      });
    }

    // COMPLETE 推送事件
    if (newState === 'COMPLETE') {
      this.emitProgress(session, {
        phase: 'complete',
        totalDimensions: session.plan?.goal.dimensions.length ?? 0,
        completedDimensions: session.completedDimensions.length,
        entriesGenerated: session.generatedEntryIds.length,
        targetEntries: session.plan?.goal.targetTotalEntries ?? 0,
        currentActivity: '会话完成',
        message: '世界书编写智能体已完成全部流程',
      });
    }
  }

  /**
   * 持久化 session 到 memoryStore（spec §SubTask 4.5 断点续跑）。
   *
   * 含 writeProvenance: {source: 'worldbook-agent', runId, toolName, timestamp}
   */
  private async persistSession(session: InternalSession): Promise<void> {
    if (!this.deps.memoryStore) return;

    try {
      const sessionData = JSON.stringify(this.serializeSession(session));
      await this.deps.memoryStore.write({
        type: 'agent',
        content: `WorldBook Authoring Session: ${session.id} [${session.state}]`,
        source: `worldbook-authoring-session:${session.id}`,
        metadata: {
          kind: 'worldbook-authoring-session',
          sessionId: session.id,
          state: session.state,
          session: sessionData,
          writeProvenance: {
            source: 'worldbook-agent',
            runId: session.id,
            toolName: 'worldbookAuthoringService',
            timestamp: Date.now(),
          },
        },
        sessionId: session.id,
      });
    } catch (err) {
      console.warn(`${LOG_PREFIX} persistSession failed:`, err);
      // 持久化失败不阻塞会话
    }
  }

  /**
   * 序列化 session（剥离运行时字段，仅保留可序列化的 AuthoringSession 部分）。
   */
  private serializeSession(session: InternalSession): AuthoringSession {
    return {
      id: session.id,
      worldBookPath: session.worldBookPath,
      allowedWorldBookPaths: session.allowedWorldBookPaths,
      state: session.state,
      goal: session.goal,
      plan: session.plan,
      completedDimensions: session.completedDimensions,
      generatedEntryIds: session.generatedEntryIds,
      auditReport: session.auditReport,
      createdAt: session.createdAt,
      updatedAt: session.updatedAt,
      aborted: session.aborted,
      abortReason: session.abortReason,
    };
  }

  /**
   * 推送进度事件。
   */
  private emitProgress(
    session: InternalSession,
    event: Omit<AuthoringProgressEvent, 'timestamp'>
  ): void {
    const fullEvent: AuthoringProgressEvent = {
      ...event,
      // 附带 sessionId，解决阻塞调用期间渲染进程 state.sessionId 仍为 null 的时序问题
      sessionId: session.id,
      timestamp: Date.now(),
    };
    try {
      session.onProgress?.(fullEvent);
    } catch (err) {
      console.warn(`${LOG_PREFIX} onProgress callback error:`, err);
    }
  }

  /**
   * 推送思考步骤事件（封装 ThoughtStep 构建 + emitProgress）。
   *
   * 在关键 LLM 调用 / 决策点采集思考过程，通过 progress 事件推送思考步骤到前端，
   * 用于思考过程可视化时间线。entriesGenerated / targetEntries 取值与 emitProgress 一致，
   * 复用 session.generatedEntryIds.length 和 session.plan?.goal.targetTotalEntries。
   */
  private emitThoughtStep(
    session: InternalSession,
    phase: AuthoringProgressEvent['phase'],
    step: {
      type: ThoughtStep['type'];
      purpose: string;
      inputSummary?: string;
      outputSummary?: string;
      durationMs: number;
      success: boolean;
    }
  ): void {
    this.emitProgress(session, {
      phase,
      entriesGenerated: session.generatedEntryIds.length,
      targetEntries: session.plan?.goal.targetTotalEntries ?? 0,
      currentActivity: step.purpose,
      thoughtStep: {
        ...step,
        phase,
        timestamp: Date.now(),
      },
    });
  }

  /**
   * 读取世界书现有条目（用于审计 + LLM 上下文）。
   */
  private async readExistingEntries(session: InternalSession): Promise<Array<Record<string, unknown>>> {
    try {
      const worldBook = await this.deps.tools.readWorldBook(session.worldBookPath);
      if (!worldBook || !worldBook.entries) return [];
      const entries = worldBook.entries;
      return Array.isArray(entries) ? entries : Object.values(entries);
    } catch (err) {
      console.warn(`${LOG_PREFIX} readExistingEntries failed:`, err);
      return [];
    }
  }

  // ==================== 网络搜索集成（Spec: add-agent-web-search-tool） ====================

  /**
   * 判断是否启用网络搜索补充。
   *
   * 同时满足两个条件：
   *  1. `config.enableWebSearch === true`（用户在 Modal 中显式开启）
   *  2. `this.deps.tools.webSearch` 方法存在（默认实现已注入；测试 mock 未注入时为 undefined）
   *
   * 未启用时编排服务跳过所有 webSearch 调用，行为与原实现完全一致（向后兼容）。
   */
  private isWebSearchEnabled(session: InternalSession): boolean {
    return (
      session.config?.enableWebSearch === true &&
      typeof this.deps.tools.webSearch === 'function'
    );
  }

  /**
   * 安全执行网络搜索（Spec: add-agent-web-search-tool §搜索失败不阻断编写）。
   *
   * - try/catch 包裹，失败时 `console.warn` + 返回空数组（不抛错，不阻断编写流程）
   * - 调用成功（未抛异常）即标记 `session.webSearchUsed = true`（即使返回空结果）
   * - 检查 abort signal，已取消时直接返回空数组
   *
   * @param session 当前会话
   * @param query 搜索关键词
   * @param maxResults 最大结果条数（可选，未指定时由 tools.webSearch 实现决定）
   * @returns 搜索结果数组（失败 / 取消时返回空数组）
   */
  private async performWebSearch(
    session: InternalSession,
    query: string,
    maxResults?: number
  ): Promise<Array<{ title: string; snippet: string; url: string }>> {
    // 取消检查
    if (session.abortController?.signal.aborted) {
      return [];
    }
    // webSearch 方法存在性二次检查（防御性编程）
    const searchFn = this.deps.tools.webSearch;
    if (typeof searchFn !== 'function') {
      return [];
    }
    const trimmedQuery = query?.trim();
    if (!trimmedQuery) {
      return [];
    }
    try {
      const results = await searchFn(trimmedQuery, maxResults);
      // 调用成功（未抛异常）即标记 webSearchUsed = true
      session.webSearchUsed = true;
      return results ?? [];
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.warn(`${LOG_PREFIX} webSearch failed (query="${trimmedQuery.slice(0, 60)}"): ${message}`);
      // 失败时返回空数组，不阻断编写流程
      return [];
    }
  }

  /**
   * 将搜索结果格式化为 researchContext 字符串（供注入 LLM 系统提示词）。
   *
   * 格式示例：
   * ```
   * 1. {title}
   *    {snippet}
   *    URL: {url}
   * 2. {title}
   *    ...
   * ```
   *
   * @param results 搜索结果数组
   * @returns 格式化字符串；空结果返回空串
   */
  private formatResearchContext(
    results: Array<{ title: string; snippet: string; url: string }>
  ): string {
    if (!results || results.length === 0) return '';
    return results
      .map((r, i) => `${i + 1}. ${r.title}\n   ${r.snippet}\n   URL: ${r.url}`)
      .join('\n');
  }

  /**
   * LLM 调用重试包装（spec §实现要点：LLM 调用失败重试 3 次）。
   *
   * 使用 infra/retry.ts 的 retryAsync，最多 3 次尝试。
   */
  private async retryLLMCall<T>(
    fn: () => Promise<T>,
    options?: { label?: string }
  ): Promise<T> {
    return retryAsync(fn, {
      attempts: LLM_MAX_RETRIES,
      minDelayMs: 500,
      maxDelayMs: 5000,
      label: options?.label ?? 'worldbookAuthoring LLM call',
      sleep: this.sleep,
    });
  }

  /**
   * 清理会话定时器（会话结束时调用）。
   */
  private clearSessionTimeouts(session: InternalSession): void {
    if (session.sessionTimeout) {
      clearTimeout(session.sessionTimeout);
      session.sessionTimeout = undefined;
    }
    if (session.answerTimeout) {
      clearTimeout(session.answerTimeout);
      session.answerTimeout = undefined;
    }
  }

  /**
   * 构建取消结果（保留已生成草稿）。
   */
  private buildCancelledResult(
    session: InternalSession,
    startTime: number
  ): WorldBookAuthoringRunResult {
    return {
      success: false,
      sessionId: session.id,
      finalState: 'CANCELLED',
      generatedEntryIds: session.generatedEntryIds,
      auditReport: session.auditReport,
      totalDurationMs: Date.now() - startTime,
      error: session.abortReason ?? '用户取消了编写',
    };
  }
}

// ==================== 默认依赖工厂 ====================

/**
 * 创建默认的 IAuthoringTools 实现（基于 worldbookTools 导出函数）。
 *
 * 通过 IWorldbookToolServices 构造工具执行器，包装为 IAuthoringTools 接口。
 * 运行时调用：import { createDefaultAuthoringTools } from './worldbookAuthoringService';
 */
export async function createDefaultAuthoringTools(
  services: import('../tools/builtin/worldbookTools').IWorldbookToolServices
): Promise<IAuthoringTools> {
  // 动态导入避免循环依赖
  const {
    createCreateEntryExecutor,
    createGenerateKeywordsExecutor,
  } = await import('../tools/builtin/worldbookTools');

  const createEntryExecutor = createCreateEntryExecutor(services);
  const generateKeywordsExecutor = createGenerateKeywordsExecutor(services);

  return {
    async readWorldBook(worldBookPath: string) {
      return services.readWorldBook(worldBookPath);
    },
    async createEntry(args, context) {
      return createEntryExecutor(
        {
          worldBookPath: args.worldBookPath,
          name: args.name,
          content: args.content,
          keys: args.keys,
          secondaryKeys: args.secondaryKeys ?? [],
          comment: args.comment ?? args.name,
        },
        context
      );
    },
    async generateKeywords(args, context) {
      return generateKeywordsExecutor(
        {
          worldBookPath: args.worldBookPath,
          entryUid: args.entryUid,
          keys: args.keys,
          secondaryKeys: args.secondaryKeys ?? [],
        },
        context
      );
    },
    // Spec: add-agent-web-search-tool — 可选 webSearch 方法实现
    // 仅当 config.enableWebSearch === true 时由编排服务调用（存在性检查 + isWebSearchEnabled）。
    // 从 storageService 读取 webSearch 配置；若全局 webSearch.enabled === false，返回空数组（不抛错）。
    // 调用 webSearchService.search 并将 SearchResult 映射为 { title, snippet, url }（剔除 source 字段）。
    async webSearch(query: string, maxResults?: number): Promise<Array<{
      title: string;
      snippet: string;
      url: string;
    }>> {
      try {
        // 动态导入避免循环依赖（与 agentHandlers.createWebSearchToolServices 模式一致）
        // 路径说明：本文件位于 src/main/services/agent/worldbook/，
        //   webSearchService 位于 src/main/services/webSearchService.ts → ../../webSearchService
        //   storageService 位于 src/main/services/storageService.ts → ../../storageService
        const { webSearchService } = await import('../../webSearchService');
        const { getStorageService } = await import('../../storageService');
        const settings = getStorageService().getSettings();
        const ws = settings?.webSearch;
        // 全局未启用 → 返回空数组（不抛错，编排服务降级为无搜索上下文）
        if (!ws || ws.enabled !== true) {
          return [];
        }
        // 构造 WebSearchConfig（字段缺失时用安全默认值）
        const config = {
          enabled: ws.enabled === true,
          provider: ws.provider ?? 'duckduckgo',
          apiKey: typeof ws.apiKey === 'string' ? ws.apiKey : '',
          endpoint: typeof ws.endpoint === 'string' ? ws.endpoint : '',
          maxResults: typeof ws.maxResults === 'number' ? ws.maxResults : 5,
          timeout: typeof ws.timeout === 'number' ? ws.timeout : 10000,
          allowedDomains: Array.isArray(ws.allowedDomains) ? ws.allowedDomains : [],
          enableInAuthoring: ws.enableInAuthoring === true,
        };
        const results = await webSearchService.search(query, config, { maxResults });
        // 映射为编排服务所需的最小结构（剔除 source 字段）
        return results.map((r) => ({
          title: r.title,
          snippet: r.snippet,
          url: r.url,
        }));
      } catch (err) {
        const message = err instanceof Error ? err.message : String(err);
        console.warn(`${LOG_PREFIX} createDefaultAuthoringTools.webSearch failed: ${message}`);
        // 失败时返回空数组，不阻断编写流程（spec: 搜索失败不阻断编写）
        return [];
      }
    },
  };
}

/**
 * 创建默认的 IEntryGenerator 实现（基于 AIService.callChatAPI）。
 *
 * 通过 LLM 生成指定维度的条目草稿数据（name/content/keys）。
 */
export function createDefaultEntryGenerator(
  aiService?: import('../../AIService').AIService,
  model?: string
): IEntryGenerator {
  return {
    async generateEntriesForDimension(
      dimension: AuthoringDimension,
      plan: AuthoringPlan,
      existingEntries: Array<Record<string, unknown>>,
      targetCount: number,
      signal?: AbortSignal,
      // Spec: add-agent-web-search-tool — 网络搜索补充资料（可选）
      researchContext?: {
        query: string;
        results: Array<{ title: string; snippet: string; url: string }>;
      }
    ): Promise<Array<{ name: string; content: string; keys: string[]; secondaryKeys?: string[]; comment?: string }>> {
      // 动态导入避免循环依赖
      const { aiService: defaultAiService } = await import('../../AIService');
      const ai = aiService ?? defaultAiService;

      const existingNames = existingEntries
        .map((e) => e.name)
        .filter((n): n is string => typeof n === 'string')
        .slice(0, 20);

      // Spec: add-agent-web-search-tool — 若提供 researchContext，将其格式化后注入系统提示词
      // 作为参考网络资料；未提供时（undefined / 空结果）行为与原实现一致（向后兼容）。
      const researchSection =
        researchContext && researchContext.results.length > 0
          ? `\n【参考网络资料（搜索 query: ${researchContext.query}）】\n` +
            researchContext.results
              .map((r, i) => `${i + 1}. ${r.title}\n   ${r.snippet}\n   URL: ${r.url}`)
              .join('\n') +
            '\n\n请参考上述资料提升内容事实准确性，但保持世界书文风一致，不要直接复制粘贴。'
          : '';

      // 去AI味规则注入（Spec: polish-deai-humanizer 扩展）：智能体生成的条目同样
      // 供 RP 检索注入，JSON-aware 规则只约束 name/content/comment 文本字段行文
      const systemPrompt = withHumanizerGenerationRules(`你是一个世界书条目生成器。根据维度描述与已有条目，生成 ${targetCount} 个不重复的新条目。

【输出格式强制要求】
- 你的响应必须且只能是一个合法的 JSON 对象
- 不要输出任何分析、推理、说明文字
- 不要使用 Markdown 标记
- 响应的第一个字符必须是 "{"，最后一个字符必须是 "}"

【JSON Schema】
{
  "entries": [
    {
      "name": "string，条目名称（10-30 字）",
      "content": "string，条目内容（50-200 字，描述该设定的详细信息）",
      "keys": ["string", ...]，触发关键词数组（3-5 个），
      "secondaryKeys": ["string", ...]，次要关键词数组（可选，0-3 个），
      "comment": "string，可选，简短注释"
    }
  ]
}

【维度信息】
- 名称：${dimension.name}
- 分类：${dimension.category}
- 描述：${dimension.description ?? '（无描述）'}

【已有条目名称（避免重复）】
${existingNames.length > 0 ? existingNames.join('、') : '（暂无）'}

【世界书主题】
${plan.goal.theme}
${researchSection}
请生成 ${targetCount} 个新条目。只输出 JSON。`);

      try {
        const aiConfig = await ai.getConfig();
        const modelName = model ?? aiConfig.model ?? 'gpt-4o-mini';

        const content = await ai.callChatAPI(
          [
            { role: 'system', content: systemPrompt },
            { role: 'user', content: `请为维度「${dimension.name}」生成 ${targetCount} 个条目。` },
          ],
          {
            model: modelName,
            temperature: aiConfig.temperature ?? 0.7,
            maxTokens: aiConfig.maxTokens ?? 4096,
            timeoutMs: 60_000,
            maxRetries: 1,
            abortSignal: signal,
          }
        );

        // 复用 planning service 的 parseJsonLoose（动态导入避免循环依赖）
        const { parseJsonLoose } = await import('./worldbookPlanningService');
        const parsed = parseJsonLoose<{ entries?: Array<{ name?: string; content?: string; keys?: unknown; secondaryKeys?: unknown; comment?: string }> }>(content);

        if (!parsed || !Array.isArray(parsed.entries)) {
          console.warn(`${LOG_PREFIX} generateEntriesForDimension: LLM 返回无法解析，原文前 200 字符: ${content.slice(0, 200)}`);
          return [];
        }

        const drafts: Array<{ name: string; content: string; keys: string[]; secondaryKeys?: string[]; comment?: string }> = [];
        for (const e of parsed.entries) {
          const name = typeof e?.name === 'string' ? e.name.trim() : '';
          const eContent = typeof e?.content === 'string' ? e.content.trim() : '';
          const keys = Array.isArray(e?.keys) ? (e.keys as unknown[]).map(String).filter((k) => k.trim()) : [];
          if (!name || !eContent || keys.length === 0) continue;
          drafts.push({
            name,
            content: eContent,
            keys,
            secondaryKeys: Array.isArray(e?.secondaryKeys) ? (e.secondaryKeys as unknown[]).map(String).filter((k) => k.trim()) : undefined,
            comment: typeof e?.comment === 'string' ? e.comment.trim() : undefined,
          });
        }

        return drafts;
      } catch (err) {
        const agentErr = toAgentError(err, 'generateEntriesForDimension LLM call failed');
        console.warn(`${LOG_PREFIX} generateEntriesForDimension failed: ${agentErr.message}`);
        throw err;
      }
    },
  };
}

// ==================== 单例导出 ====================

/**
 * 编排服务单例。
 *
 * 延迟初始化：首次调用 run() 时通过动态导入装配默认依赖。
 * 测试时应直接 `new WorldBookAuthoringService({ ...mocks })` 创建实例。
 *
 * 注：单例的依赖在首次使用时动态装配（避免模块加载时即触发 AIService 等重依赖）。
 *     若依赖装配失败，单例仍可创建（run 时再报错）。
 */
let singletonInstance: WorldBookAuthoringService | null = null;
let singletonInitPromise: Promise<WorldBookAuthoringService> | null = null;

/**
 * 获取编排服务单例（延迟初始化）。
 */
export async function getWorldBookAuthoringService(): Promise<WorldBookAuthoringService> {
  if (singletonInstance) return singletonInstance;
  if (singletonInitPromise) return singletonInitPromise;

  singletonInitPromise = (async () => {
    // 动态装配默认依赖
    const { worldbookPlanningService } = await import('./worldbookPlanningService');
    const { worldbookAuditService } = await import('./worldbookAuditService');

    // worldbookTools 的 IWorldbookToolServices 由 agentHandlers 注入，
    // 此处用 worldBookService 作为默认实现（动态导入避免循环依赖）
    let tools: IAuthoringTools;
    try {
      const { worldBookService } = await import('../../worldBookService');
      const toolServices: import('../tools/builtin/worldbookTools').IWorldbookToolServices = {
        async readWorldBook(filePath: string) {
          const wb = await worldBookService.readWorldBook(filePath);
          return wb as { name?: string; description?: string; entries?: Array<Record<string, unknown>> } | null;
        },
        async writeWorldBook(filePath: string, data) {
          const result = await worldBookService.writeWorldBook(filePath, data);
          return result;
        },
        async getWorldBookDescription(filePath: string) {
          const wb = await worldBookService.readWorldBook(filePath);
          return wb?.description ?? '';
        },
      };
      tools = await createDefaultAuthoringTools(toolServices);
    } catch (err) {
      console.warn(`${LOG_PREFIX} Failed to create default authoring tools, using stub:`, err);
      tools = {
        async readWorldBook() { return null; },
        async createEntry() { return { success: false, content: 'Tools not initialized', continueLoop: false }; },
        async generateKeywords() { return { success: false, content: 'Tools not initialized', continueLoop: false }; },
      };
    }

    const entryGenerator = createDefaultEntryGenerator();

    // memoryStore / steerEngine / goalTracker 单例可选（未初始化时跳过对应功能）
    let memoryStore: IMemoryProvider | undefined;
    try {
      const { getMemoryStore } = await import('../memory/memoryStore');
      memoryStore = getMemoryStore();
    } catch {
      // memoryStore 未初始化，降级为无持久化
    }

    let steerEngine: ISteerSink | undefined;
    try {
      const { getSteerEngine } = await import('../learning/steerEngine');
      steerEngine = getSteerEngine();
    } catch {
      // steerEngine 未初始化
    }

    let goalTracker: IGoalSink | undefined;
    try {
      const { getGoalTracker } = await import('../learning/goalTracker');
      goalTracker = getGoalTracker();
    } catch {
      // goalTracker 未初始化
    }

    singletonInstance = new WorldBookAuthoringService({
      planningService: worldbookPlanningService,
      auditService: worldbookAuditService,
      tools,
      entryGenerator,
      memoryStore,
      steerEngine,
      goalTracker,
    });

    return singletonInstance;
  })();

  return singletonInitPromise;
}

/**
 * 同步获取编排服务单例（若已初始化）。
 *
 * 用于不需要立即 run 的场景（如 getSessionStatus / cancel）。
 * 若未初始化，返回 null（调用方应改用 getWorldBookAuthoringService() 异步初始化）。
 */
export function getWorldBookAuthoringServiceSync(): WorldBookAuthoringService | null {
  return singletonInstance;
}

/**
 * 重置单例（仅测试用）。
 */
export function resetWorldBookAuthoringService(): void {
  singletonInstance = null;
  singletonInitPromise = null;
}
