import { WritingProject, ExportFormat, WritingStyleResource, ModelConfig } from '../../shared/types/writing.types';
import { WritingProjectRepository } from './writing/WritingProjectRepository';
import { WritingStyleRepository } from './writing/WritingStyleRepository';
import { WritingTableRepository } from './writing/WritingTableRepository';
import { TableOrganizeService } from './writing/TableOrganizeService';
import { TableEditCommandExecutor } from './writing/TableEditCommandExecutor';
import { AIConfigProvider, aiConfigProvider } from './ai/AIConfigProvider';
import type { VersionSnapshot } from './writing/WritingTableRepository';

// re-export 子模块类型与函数，便于外部消费方渐进迁移
// 注意：isolatedModules 模式下类型重导出必须使用 `export type`
export {
  WritingProjectRepository,
  getWritingProjectsPath,
  getProjectDir,
  getChaptersDir,
  getChunksDir,
  getVersionsDir,
  getIndexFilePath,
  safeWriteFile,
  computeProjectMetadata,
  loadIndex,
  saveIndex
} from './writing/WritingProjectRepository';
export type { ProjectsIndex } from './writing/WritingProjectRepository';
export {
  WritingStyleRepository,
  getWritingStylesDir,
  getWritingStylesIndexFilePath,
  loadWritingStylesIndex,
  saveWritingStylesIndex
} from './writing/WritingStyleRepository';
export type { WritingStylesIndex } from './writing/WritingStyleRepository';
export {
  WritingTableRepository,
  getWritingTablesDir,
  getWritingTableFile,
  getWritingTableConfigFile,
  getWritingOrganizeProgressFile,
  getVersionSnapshotFile,
  loadTableData,
  saveTableDataFile,
  loadTableConfig,
  saveTableConfigFile
} from './writing/WritingTableRepository';
export type {
  WritingTableData,
  WritingTableConfig,
  WritingOrganizeProgress,
  TableChangeRecord,
  VersionSnapshot
} from './writing/WritingTableRepository';
export { TableEditCommandExecutor } from './writing/TableEditCommandExecutor';
export { TableOrganizeService } from './writing/TableOrganizeService';
export { AIConfigProvider, aiConfigProvider } from './ai/AIConfigProvider';

/**
 * WritingStorageService (Facade)
 *
 * 这是 Task 9 拆分前的 God Class，已瘦身为编排层。
 * 真正的职责被分配到以下子模块：
 *
 * - {@link WritingProjectRepository}: 项目/章节/版本持久化
 * - {@link WritingStyleRepository}: 写作风格存储
 * - {@link WritingTableRepository}: 表格数据存储
 * - {@link TableOrganizeService}: 表格整理业务逻辑（含 AI 调用与 prompt 构建）
 * - {@link TableEditCommandExecutor}: 表格编辑指令解析执行
 * - {@link AIConfigProvider}: AI 配置获取
 *
 * 保持外部 API 完全不变：所有公共方法签名与原 WritingStorageService 一致。
 * writingHandlers.ts 与 WritingResourceManager.ts 的调用方式不受影响。
 *
 * SubTask 9.6: organizeTable 内 `chapter.status = 'organized' as any` 已在
 *   TableOrganizeService 中改为不可变更新 + ChapterStatus.ORGANIZED。
 * SubTask 9.7: 跨层依赖（tableTemplateService / tableEditParser / addLog）
 *   已隔离到 TableOrganizeService / TableEditCommandExecutor 内部，
 *   Facade 不再直接 import 这三者。剩余迁移至 Task 13 统一处理。
 */
export class WritingStorageService {
  private readonly projectRepo: WritingProjectRepository;
  private readonly styleRepo: WritingStyleRepository;
  private readonly tableRepo: WritingTableRepository;
  private readonly editExecutor: TableEditCommandExecutor;
  private readonly aiConfig: AIConfigProvider;
  private readonly organizeService: TableOrganizeService;

  constructor() {
    this.projectRepo = new WritingProjectRepository();
    this.styleRepo = new WritingStyleRepository();
    this.tableRepo = new WritingTableRepository();
    this.editExecutor = new TableEditCommandExecutor();
    this.aiConfig = aiConfigProvider;
    this.organizeService = new TableOrganizeService(
      this.projectRepo,
      this.tableRepo,
      this.aiConfig,
      this.editExecutor
    );
  }

  // ==================== 项目/章节/版本 ====================

  getStoragePath(): string {
    return this.projectRepo.getStoragePath();
  }

  getProjectDirPath(projectId: string): string | null {
    return this.projectRepo.getProjectDirPath(projectId);
  }

  async saveProject(project: WritingProject): Promise<boolean> {
    return this.projectRepo.saveProject(project);
  }

  async loadProject(projectId: string): Promise<WritingProject | null> {
    return this.projectRepo.loadProject(projectId);
  }

  async loadAllProjects(): Promise<WritingProject[]> {
    return this.projectRepo.loadAllProjects();
  }

  async deleteProject(projectId: string): Promise<boolean> {
    return this.projectRepo.deleteProject(projectId);
  }

  async exportProject(projectId: string, format: ExportFormat): Promise<string> {
    return this.projectRepo.exportProject(projectId, format);
  }

  async autoSaveChapter(projectId: string, chapterIndex: number, content: string, isAutoGenerated: boolean = false): Promise<void> {
    return this.projectRepo.autoSaveChapter(projectId, chapterIndex, content, isAutoGenerated);
  }

  async saveVersion(projectId: string, chapterIndex: number, content: string, note?: string, isAutoGenerated: boolean = false): Promise<boolean> {
    return this.projectRepo.saveVersion(projectId, chapterIndex, content, note, isAutoGenerated);
  }

  async restoreVersion(projectId: string, chapterIndex: number, versionId: string): Promise<boolean> {
    return this.projectRepo.restoreVersion(projectId, chapterIndex, versionId);
  }

  async saveChunkCheckpoint(projectId: string, chapterIndex: number, chunkIndex: number, content: string): Promise<boolean> {
    return this.projectRepo.saveChunkCheckpoint(projectId, chapterIndex, chunkIndex, content);
  }

  async loadChunkCheckpoint(projectId: string, chapterIndex: number, chunkIndex: number): Promise<string | null> {
    return this.projectRepo.loadChunkCheckpoint(projectId, chapterIndex, chunkIndex);
  }

  async clearChunkCheckpoints(projectId: string, chapterIndex: number): Promise<boolean> {
    return this.projectRepo.clearChunkCheckpoints(projectId, chapterIndex);
  }

  // ==================== 写作风格 ====================

  async saveWritingStyle(resource: WritingStyleResource): Promise<boolean> {
    return this.styleRepo.saveWritingStyle(resource);
  }

  async loadWritingStyle(resourceId: string): Promise<WritingStyleResource | null> {
    return this.styleRepo.loadWritingStyle(resourceId);
  }

  async listWritingStyles(): Promise<WritingStyleResource[]> {
    return this.styleRepo.listWritingStyles();
  }

  async deleteWritingStyle(resourceId: string): Promise<boolean> {
    return this.styleRepo.deleteWritingStyle(resourceId);
  }

  // ==================== 表格数据/配置 ====================

  async getTableData(projectId: string): Promise<import('./writing/WritingTableRepository').WritingTableData | null> {
    return this.tableRepo.getTableData(projectId);
  }

  async saveTableData(projectId: string, sheetName: string, sheetData: Record<string, unknown>[]): Promise<void> {
    return this.tableRepo.saveTableData(projectId, sheetName, sheetData);
  }

  async clearTableData(projectId: string): Promise<void> {
    return this.tableRepo.clearTableData(projectId);
  }

  async updateRowInTable(projectId: string, sheetName: string, rowIndex: number, rowData: Record<string, unknown>): Promise<boolean> {
    return this.tableRepo.updateRowInTable(projectId, sheetName, rowIndex, rowData);
  }

  async getTableConfig(projectId: string): Promise<import('./writing/WritingTableRepository').WritingTableConfig | null> {
    return this.tableRepo.getTableConfig(projectId);
  }

  async saveTableConfig(projectId: string, config: import('./writing/WritingTableRepository').WritingTableConfig): Promise<void> {
    return this.tableRepo.saveTableConfig(projectId, config);
  }

  async associateTableTemplate(projectId: string, templateId: string, templateName: string, templateSheets: Array<{ name: string; headers: string[]; description?: string }>): Promise<void> {
    return this.tableRepo.associateTableTemplate(projectId, templateId, templateName, templateSheets);
  }

  async getOrganizeProgress(projectId: string): Promise<import('./writing/WritingTableRepository').WritingOrganizeProgress | null> {
    return this.tableRepo.getOrganizeProgress(projectId);
  }

  async getChapterOrganizeStatus(projectId: string): Promise<{ chapterIndex: number; title: string; status: string }[]> {
    const project = await this.projectRepo.loadProject(projectId);
    return this.tableRepo.getChapterOrganizeStatus(project);
  }

  // ==================== 版本快照 ====================

  async getVersionSnapshot(projectId: string): Promise<VersionSnapshot | null> {
    return this.tableRepo.getVersionSnapshot(projectId);
  }

  async confirmVersion(projectId: string): Promise<{ success: boolean; error?: string }> {
    return this.tableRepo.confirmVersion(projectId);
  }

  async rollbackVersion(projectId: string): Promise<{ success: boolean; error?: string }> {
    return this.tableRepo.rollbackVersion(projectId);
  }

  compareTableData(
    originalData: import('./writing/WritingTableRepository').WritingTableData,
    newData: import('./writing/WritingTableRepository').WritingTableData
  ): import('./writing/WritingTableRepository').TableChangeRecord {
    return this.tableRepo.compareTableData(originalData, newData);
  }

  // ==================== 表格整理业务 ====================

  async organizeTable(
    projectId: string,
    modelConfig: ModelConfig,
    chapterIndex?: number,
    onProgress?: (current: number, total: number, message: string, percent?: number, currentChunk?: number, totalChunks?: number) => void,
    requirements?: string,
    skipOrganized?: boolean
  ): Promise<{ success: boolean; processedCount: number; errorCount: number; errors: string[] }> {
    return this.organizeService.organizeTable(projectId, modelConfig, chapterIndex, onProgress, requirements, skipOrganized);
  }

  async organizeSingleSheet(
    projectId: string,
    sheetName: string,
    modelConfig: ModelConfig,
    chapterIndex?: number,
    onProgress?: (current: number, total: number, status: string, percent: number, currentChunk?: number, totalChunks?: number) => void,
    requirements?: string
  ): Promise<{ success: boolean; processedCount: number; errorCount: number; errors: string[] }> {
    return this.organizeService.organizeSingleSheet(projectId, sheetName, modelConfig, chapterIndex, onProgress, requirements);
  }

  async reorganizeRow(
    projectId: string,
    sheet: string,
    rowIndex: number,
    rowData: Record<string, unknown>,
    requirements: string,
    modelConfig: ModelConfig
  ): Promise<{ success: boolean; updatedRow?: Record<string, unknown>; error?: string }> {
    return this.organizeService.reorganizeRow(projectId, sheet, rowIndex, rowData, requirements, modelConfig);
  }
}

/**
 * 单例。保持与原 WritingStorageService 单例导出方式一致。
 */
export const writingStorageService = new WritingStorageService();
