/**
 * 世界书组工具单元测试（Task 17.1）
 *
 * 验证 createEntry / expandFromContext / generateKeywords / sortEntries 四个工具的：
 *  - 参数校验（必填字段、空值、类型）
 *  - 沙盒隔离（allowedWorldBookPaths 白名单越权拒绝）
 *  - 草稿标记（autoGenerated=true + provenance 写溯源）
 *  - 读写闭环（readWorldBook → 修改 → writeWorldBook 调用链）
 *  - 错误降级（读失败/写失败返回 ToolExecutionResult 而非抛异常）
 */

import { describe, it, expect, vi, beforeEach } from 'vitest';
import {
  createCreateEntryExecutor,
  createExpandFromContextExecutor,
  createGenerateKeywordsExecutor,
  createSortEntriesExecutor,
  createEntryDescriptor,
  expandFromContextDescriptor,
  generateKeywordsDescriptor,
  sortEntriesDescriptor,
  registerWorldbookTools,
  type IWorldbookToolServices,
} from '../agent/tools/builtin/worldbookTools';
import type { ToolDescriptor } from '../agent/tools/types';
import type { ToolCallContext } from '../agent/contracts';

// ==================== Mock 服务工厂 ====================

interface MockState {
  worldBooks: Record<string, { name?: string; description?: string; entries: any[] }>;
  writeCalls: Array<{ filePath: string; data: any }>;
  writeShouldFail?: boolean;
}

function createMockServices(state: MockState): IWorldbookToolServices {
  return {
    readWorldBook: async (filePath) => {
      const wb = state.worldBooks[filePath];
      if (!wb) return null;
      return { name: wb.name, description: wb.description, entries: wb.entries };
    },
    writeWorldBook: async (filePath, data) => {
      if (state.writeShouldFail) {
        return { success: false, error: 'mock write failure' };
      }
      state.writeCalls.push({ filePath, data });
      // 模拟持久化：更新内存中的 worldbook
      state.worldBooks[filePath] = {
        name: data.name as string | undefined,
        description: data.description as string | undefined,
        entries: Array.isArray(data.entries) ? (data.entries as any[]) : Object.values(data.entries || {}),
      };
      return { success: true };
    },
    getWorldBookDescription: async (filePath) => {
      return state.worldBooks[filePath]?.description || '';
    },
  };
}

function createContext(mode: 'worldbook' | 'dialogue' = 'worldbook', allowedPaths?: string[]): ToolCallContext {
  return {
    mode,
    sessionId: 'test-session',
    ...(allowedPaths ? { allowedWorldBookPaths: allowedPaths } : {}),
  };
}

// ==================== 测试 ====================

describe('worldbookTools（Task 17.1）', () => {
  let state: MockState;

  beforeEach(() => {
    state = {
      worldBooks: {
        '/test/wb.json': {
          name: '测试世界书',
          description: '测试描述',
          entries: [
            { uid: 1, id: 1, name: '条目1', content: '内容1', key: ['关键词1'], secondaryKeys: [], autoGenerated: false },
            { uid: 2, id: 2, name: '条目2', content: '内容2', key: ['关键词2'], secondaryKeys: ['次要'], autoGenerated: false },
          ],
        },
      },
      writeCalls: [],
    };
  });

  // ===== 描述符验证 =====

  describe('描述符定义', () => {
    it('四个工具描述符均正确', () => {
      const descriptors = [createEntryDescriptor, expandFromContextDescriptor, generateKeywordsDescriptor, sortEntriesDescriptor];
      for (const d of descriptors) {
        expect(d.owner.kind).toBe('core');
        expect(d.availability).toEqual({ kind: 'context', key: 'mode', equals: 'worldbook' });
        expect(d.inputSchema.type).toBe('object');
      }
    });

    it('工具名符合规范（2-3 词，可 grep）', () => {
      expect(createEntryDescriptor.name).toBe('createEntry');
      expect(expandFromContextDescriptor.name).toBe('expandFromContext');
      expect(generateKeywordsDescriptor.name).toBe('generateKeywords');
      expect(sortEntriesDescriptor.name).toBe('sortEntries');
    });
  });

  // ===== createEntry 工具 =====

  describe('createEntry', () => {
    it('成功创建带 autoGenerated 标记的草稿条目', async () => {
      const services = createMockServices(state);
      const executor = createCreateEntryExecutor(services);
      const result = await executor(
        {
          worldBookPath: '/test/wb.json',
          name: '新角色',
          content: '一个新角色的描述',
          keys: ['新角色', '角色名'],
          secondaryKeys: ['别名'],
        },
        createContext()
      );

      expect(result.success).toBe(true);
      expect(result.continueLoop).toBe(true);
      expect(result.content).toContain('autoGenerated=true');
      expect(result.content).toContain('UID: 3');

      // 验证写入调用
      expect(state.writeCalls).toHaveLength(1);
      const writtenEntries = state.writeCalls[0].data.entries;
      expect(Array.isArray(writtenEntries)).toBe(true);
      const newEntry = writtenEntries.find((e: any) => e.uid === 3);
      expect(newEntry).toBeDefined();
      expect(newEntry.autoGenerated).toBe(true);
      expect(newEntry.key).toEqual(['新角色', '角色名']);
      expect(newEntry.secondaryKeys).toEqual(['别名']);
      expect(newEntry.provenance).toBeDefined();
      expect(newEntry.provenance.source).toBe('agent');
      expect(newEntry.provenance.toolName).toBe('createEntry');
      expect(newEntry.provenance.timestamp).toBeGreaterThan(0);
    });

    it('缺少必填参数 worldBookPath 时返回错误', async () => {
      const services = createMockServices(state);
      const executor = createCreateEntryExecutor(services);
      const result = await executor({ name: 'x', content: 'y', keys: ['k'] }, createContext());

      expect(result.success).toBe(false);
      expect(result.continueLoop).toBe(false);
      expect(result.content).toContain('worldBookPath');
    });

    it('keys 为空数组时返回错误', async () => {
      const services = createMockServices(state);
      const executor = createCreateEntryExecutor(services);
      const result = await executor(
        { worldBookPath: '/test/wb.json', name: 'x', content: 'y', keys: [] },
        createContext()
      );

      expect(result.success).toBe(false);
      expect(result.content).toContain('keys');
    });

    it('沙盒越权时拒绝写入', async () => {
      const services = createMockServices(state);
      const executor = createCreateEntryExecutor(services);
      const result = await executor(
        {
          worldBookPath: '/test/wb.json',
          name: 'x',
          content: 'y',
          keys: ['k'],
        },
        createContext('worldbook', ['/other/path.json']) // 白名单不含 /test/wb.json
      );

      expect(result.success).toBe(false);
      expect(result.content).toContain('Sandbox violation');
      expect(state.writeCalls).toHaveLength(0);
    });

    it('沙盒白名单匹配时允许写入', async () => {
      const services = createMockServices(state);
      const executor = createCreateEntryExecutor(services);
      const result = await executor(
        {
          worldBookPath: '/test/wb.json',
          name: 'x',
          content: 'y',
          keys: ['k'],
        },
        createContext('worldbook', ['/test/wb.json'])
      );

      expect(result.success).toBe(true);
      expect(state.writeCalls).toHaveLength(1);
    });

    it('读取世界书失败时返回错误（不抛异常）', async () => {
      const services = createMockServices(state);
      const executor = createCreateEntryExecutor(services);
      const result = await executor(
        {
          worldBookPath: '/nonexistent.json',
          name: 'x',
          content: 'y',
          keys: ['k'],
        },
        createContext()
      );

      expect(result.success).toBe(false);
      expect(result.content).toContain('Failed to read worldbook');
    });
  });

  // ===== expandFromContext 工具 =====

  describe('expandFromContext', () => {
    it('批量创建多个草稿条目', async () => {
      const services = createMockServices(state);
      const executor = createExpandFromContextExecutor(services);
      const result = await executor(
        {
          worldBookPath: '/test/wb.json',
          contextText: '一段包含多个实体的上下文...',
          entries: [
            { name: '地点A', content: '地点A描述', keys: ['地点A'] },
            { name: '物品B', content: '物品B描述', keys: ['物品B'], secondaryKeys: ['宝物'] },
          ],
        },
        createContext()
      );

      expect(result.success).toBe(true);
      expect(result.content).toContain('Expanded 2 lore entries');
      expect(result.content).toContain('UIDs: 3, 4');

      const writtenEntries = state.writeCalls[0].data.entries;
      expect(writtenEntries).toHaveLength(4); // 2 原有 + 2 新增
      const newEntries = writtenEntries.filter((e: any) => e.autoGenerated === true);
      expect(newEntries).toHaveLength(2);
      expect(newEntries[0].provenance.toolName).toBe('expandFromContext');
    });

    it('entries 数组为空时返回错误', async () => {
      const services = createMockServices(state);
      const executor = createExpandFromContextExecutor(services);
      const result = await executor(
        { worldBookPath: '/test/wb.json', contextText: 'x', entries: [] },
        createContext()
      );

      expect(result.success).toBe(false);
      expect(result.content).toContain('entries');
    });

    it('entry 缺少 keys 时返回错误并指明索引', async () => {
      const services = createMockServices(state);
      const executor = createExpandFromContextExecutor(services);
      const result = await executor(
        {
          worldBookPath: '/test/wb.json',
          contextText: 'x',
          entries: [
            { name: 'valid', content: 'c', keys: ['k'] },
            { name: 'invalid', content: 'c', keys: [] }, // 缺少 keys
          ],
        },
        createContext()
      );

      expect(result.success).toBe(false);
      expect(result.content).toContain('entries[1]');
    });
  });

  // ===== generateKeywords 工具 =====

  describe('generateKeywords', () => {
    it('成功更新已有条目的关键词', async () => {
      const services = createMockServices(state);
      const executor = createGenerateKeywordsExecutor(services);
      const result = await executor(
        {
          worldBookPath: '/test/wb.json',
          entryUid: 2,
          keys: ['新主关键词'],
          secondaryKeys: ['新次关键词'],
        },
        createContext()
      );

      expect(result.success).toBe(true);
      expect(result.content).toContain('UID 2');
      expect(result.content).toContain('New keys: 新主关键词');

      const updatedEntry = state.writeCalls[0].data.entries.find((e: any) => e.uid === 2);
      expect(updatedEntry.key).toEqual(['新主关键词']);
      expect(updatedEntry.secondaryKeys).toEqual(['新次关键词']);
      expect(updatedEntry.keysecondary).toEqual(['新次关键词']);
    });

    it('条目不存在时返回错误', async () => {
      const services = createMockServices(state);
      const executor = createGenerateKeywordsExecutor(services);
      const result = await executor(
        {
          worldBookPath: '/test/wb.json',
          entryUid: 999,
          keys: ['k'],
        },
        createContext()
      );

      expect(result.success).toBe(false);
      expect(result.content).toContain('not found');
    });

    it('支持字符串形式的 entryUid', async () => {
      const services = createMockServices(state);
      const executor = createGenerateKeywordsExecutor(services);
      const result = await executor(
        {
          worldBookPath: '/test/wb.json',
          entryUid: '1',
          keys: ['字符串UID'],
        },
        createContext()
      );

      expect(result.success).toBe(true);
    });
  });

  // ===== sortEntries 工具 =====

  describe('sortEntries', () => {
    it('按指定顺序重排条目（更新 order/displayIndex）', async () => {
      const services = createMockServices(state);
      const executor = createSortEntriesExecutor(services);
      // 原顺序 uid=1,2 → 新顺序 uid=2,1
      const result = await executor(
        {
          worldBookPath: '/test/wb.json',
          sortOrder: [2, 1],
        },
        createContext()
      );

      expect(result.success).toBe(true);
      expect(result.content).toContain('Reordered 2 entries');

      const writtenEntries = state.writeCalls[0].data.entries;
      expect(writtenEntries[0].uid).toBe(2);
      expect(writtenEntries[0].order).toBe(10);
      expect(writtenEntries[0].displayIndex).toBe(0);
      expect(writtenEntries[1].uid).toBe(1);
      expect(writtenEntries[1].order).toBe(20);
      expect(writtenEntries[1].displayIndex).toBe(1);
    });

    it('sortOrder 包含重复 UID 时拒绝', async () => {
      const services = createMockServices(state);
      const executor = createSortEntriesExecutor(services);
      const result = await executor(
        {
          worldBookPath: '/test/wb.json',
          sortOrder: [1, 1],
        },
        createContext()
      );

      expect(result.success).toBe(false);
      expect(result.content).toContain('duplicate');
    });

    it('sortOrder 包含不存在的 UID 时拒绝', async () => {
      const services = createMockServices(state);
      const executor = createSortEntriesExecutor(services);
      const result = await executor(
        {
          worldBookPath: '/test/wb.json',
          sortOrder: [1, 2, 999],
        },
        createContext()
      );

      expect(result.success).toBe(false);
      expect(result.content).toContain('unknown UIDs');
    });

    it('sortOrder 未覆盖所有条目时拒绝', async () => {
      const services = createMockServices(state);
      const executor = createSortEntriesExecutor(services);
      const result = await executor(
        {
          worldBookPath: '/test/wb.json',
          sortOrder: [1], // 缺少 uid=2
        },
        createContext()
      );

      expect(result.success).toBe(false);
      expect(result.content).toContain('missing');
    });
  });

  // ===== registerWorldbookTools 注册函数 =====

  describe('registerWorldbookTools', () => {
    it('注册 4 个工具到 registry', () => {
      const registered: Array<{ descriptor: ToolDescriptor; executor: any }> = [];
      const mockRegistry = {
        register: (descriptor: ToolDescriptor, executor: any) => {
          registered.push({ descriptor, executor });
        },
      };
      const services = createMockServices(state);
      registerWorldbookTools(mockRegistry as any, services);

      expect(registered).toHaveLength(4);
      expect(registered.map((r) => r.descriptor.name)).toEqual([
        'createEntry',
        'expandFromContext',
        'generateKeywords',
        'sortEntries',
      ]);
    });

    it('重复注册时忽略错误（不抛异常）', () => {
      const mockRegistry = {
        register: () => {
          throw new Error('already registered');
        },
      };
      const services = createMockServices(state);
      expect(() => registerWorldbookTools(mockRegistry as any, services)).not.toThrow();
    });
  });

  // ===== 可用性 gating =====

  describe('可用性 gating', () => {
    it('四个工具均仅在 mode=worldbook 时可用', () => {
      const descriptors = [createEntryDescriptor, expandFromContextDescriptor, generateKeywordsDescriptor, sortEntriesDescriptor];
      for (const d of descriptors) {
        expect(d.availability).toEqual({ kind: 'context', key: 'mode', equals: 'worldbook' });
      }
    });
  });
});
