/**
 * 全局设置文件 - 主进程和渲染进程共享
 */
import { EmbeddingMode } from './types/vector';

export const AppSetting = {
  version: '1.0.0',
  name: 'Creative Café',
  description: '创想咖啡厅 - SillyTavern 管理工具',
  defaultSetting: {
    preset_name: 'Default',
    aiEngines: [
      {
        id: 'default',
        name: '默认引擎',
        api_url: 'http://127.0.0.1:5000',
        api_key: '',
        model_name: 'llmfan46/Qwen3.5-27B-heretic-v3-no-think',
        api_mode: 'text_completion',
        // 后端能力探测（Spec: optimize-chat-ai-intelligence / Task 6.2）
        // 默认引擎使用 text_completion 模式（textgen-webui/koboldcpp/aphrodite 类后端），
        // 因此预设 supportsRepPen=true / supportsDrySampler=true，使 DRY 采样与 rep_pen 默认启用。
        // 用户可在设置 UI 中按 engine type 显式覆盖此字段。
        capabilities: {
          supportsStopArray: true,
          supportsRepPen: true,
          supportsDrySampler: true,
          supportsVision: false,
          supportsThinking: false,
          supportsToolCalling: false,
        },
        prompt_template: '',
        stop_words: '',
        max_generation_length: undefined,
        custom_optimization_prompt: '# 请按照要求优化以下提示词模板：\n\n{{prompt}}\n\n# 优化说明\n\n- 增强了任务描述的清晰度，使其更符合SillyTavern的使用场景\n\n- 添加了更明确的格式要求，确保与SillyTavern的用户交互模式匹配\n\n- 优化了指令的逻辑结构，提高了在SillyTavern平台上的性能\n\n- 调整了提示模板的表达方式，使其更符合SillyTavern的最佳实践\n\n- 确保了提示模板与SillyTavern平台的预期用例保持一致',
        system_prompt: '',
        temperature: undefined,
        max_tokens: undefined,
        streaming: true,
        enable_chain_of_thought: false,
        openai_max_context: 4095,
        names_behavior: 0,
        send_if_empty: '',
        impersonation_prompt: "[Write your next reply from the point of view of {{user}}, using the chat history so far as a guideline for the writing style of {{user}}. Don't write as {{char}} or system. Don't describe actions of {{char}}.]",
        new_chat_prompt: "[Start a new Chat]",
        new_example_chat_prompt: "[Example Chat]",
        continue_nudge_prompt: "[Continue your last message without repeating its original content.]",
        bias_preset_selected: "Default (none)",
        max_context_unlocked: false,
        wi_format: "{0}",
        scenario_format: "{{scenario}}",
        personality_format: "{{personality}}",
        assistant_prefill: "",
        assistant_impersonation: "",
        use_sysprompt: false,
        squash_system_messages: false,
        media_inlining: true,
        continue_prefill: false,
        continue_postfix: " ",
        seed: -1,
        n: 1,
        novelai_api_key: '',
        novelai_model: 'krake-v2',
        novelai_sampler: 'k_dpm_2',
        novelai_cfg_scale: 7.0,
        ai_horde_api_key: '',
        ai_horde_model: '',
        ai_horde_max_wait: 60,
        ai_horde_priority: 50,
        temp: 2,
        temperature_last: false,
        top_p: undefined,
        top_k: 0,
        top_a: 0,
        tfs: 1,
        epsilon_cutoff: 0,
        eta_cutoff: 0,
        typical_p: 1,
        min_p: 0.1,
        rep_pen: 1,
        rep_pen_range: 0,
        rep_pen_decay: 0,
        rep_pen_slope: 1,
        no_repeat_ngram_size: 0,
        penalty_alpha: 0,
        num_beams: 1,
        length_penalty: 1,
        min_length: 0,
        encoder_rep_pen: 1,
        freq_pen: 0,
        presence_pen: 0,
        skew: 0,
        do_sample: true,
        early_stopping: false,
        dynatemp: false,
        min_temp: 0,
        max_temp: 2,
        dynatemp_exponent: 1,
        smoothing_factor: 0,
        smoothing_curve: 1,
        dry_allowed_length: 2,
        dry_multiplier: 0,
        dry_base: 1.75,
        dry_sequence_breakers: '["\n", ":", "\"", "*"]',
        dry_penalty_last_n: 0,
        add_bos_token: true,
        ban_eos_token: false,
        skip_special_tokens: true,
        mirostat_mode: 0,
        mirostat_tau: 5,
        mirostat_eta: 0.1,
        guidance_scale: 1,
        negative_prompt: '',
        grammar_string: '',
        json_schema: null,
        json_schema_allow_empty: false,
        banned_tokens: '',
        sampler_priority: [
            "repetition_penalty", "presence_penalty", "frequency_penalty", "dry",
            "temperature", "dynamic_temperature", "quadratic_sampling", "top_n_sigma",
            "top_k", "top_p", "typical_p", "epsilon_cutoff", "eta_cutoff", "tfs",
            "top_a", "min_p", "mirostat", "xtc", "encoder_repetition_penalty", "no_repeat_ngram"
        ],
        samplers: [
            "penalties", "dry", "top_n_sigma", "top_k", "typ_p", "tfs_z",
            "typical_p", "xtc", "top_p", "adaptive_p", "min_p", "temperature"
        ],
        samplers_priorities: [
            "dry", "penalties", "no_repeat_ngram", "temperature", "top_nsigma",
            "top_p_top_k", "top_a", "min_p", "tfs", "eta_cutoff", "epsilon_cutoff",
            "typical_p", "quadratic", "xtc"
        ],
        ignore_eos_token: false,
        spaces_between_special_tokens: true,
        speculative_ngram: false,
        sampler_order: [5, 6, 0, 1, 2, 3, 4],
        logit_bias: [],
        xtc_threshold: 0.1,
        xtc_probability: 0,
        nsigma: 0,
        min_keep: 0,
        extensions: {},
        adaptive_target: -0.01,
        adaptive_decay: 0.9,
        rep_pen_size: 0,
        genamt: 350,
        max_length: 8192,
        frequency_penalty: undefined,
        presence_penalty: undefined,
        use_function_calling: false,
        useAgent: false,
        auto_connect: true,
        skip_status_check: false,
        use_proxy: false,
        proxy_url: 'http://localhost:7890',
        proxy_port: 7890,
        encrypt_api_key: false,
        enable_access_control: false,
        api_key_transmission: 'body'
      }
    ],
    activeEngineId: 'default',
    defaultEngineId: 'default',
    logLevel: 'info',
    characterPath: '__USER_DATA__/data/characters',
    worldBookPath: '__USER_DATA__/data/worldbooks',
    avatarPath: '__USER_DATA__/data/avatars',
    creativePath: '__USER_DATA__/data/creatives',
    memoryPath: '__USER_DATA__/data/memories',
    pluginPath: '__USER_DATA__/data/plugins',
    dashboardBackgroundImage: '',
    animationEnabled: true,
    compactMode: false,
    debugMode: false,
    vector: {
      embeddingMode: 'remote' as EmbeddingMode,
      remoteModel: 'text-embedding-3-small',
      remoteApiUrl: '',
      remoteApiKey: '',
      cacheEnabled: true,
      cacheL1Size: 1000,
      cacheL1TTL: 300,
      cacheL2TTL: 3600,
      defaultTopK: 5,
      minSimilarityScore: 0.7,
      contextWindowTokens: 4096,
      autoVectorizeWorldBook: true,
      autoVectorizeKnowledge: true
    },
    // Spec: add-ai-expression-generation / Task 6
    // Stable Diffusion WebUI 默认配置（角色卡 AI 表情生成 img2img 调用参数）
    // 端点对应 Forge Neo 默认端口；model 留空表示使用 SD WebUI 当前已加载模型。
    // denoisingStrength=0.55 / steps=28 / cfgScale=7 与 sdGenerationService 默认值一致。
    // adetailerEnabled=true 默认开启面部一致性修复。
    //
    // 【重点标记 - ADetailer-Neo 兼容性 + 参数扩展（2026-07-27）】
    // 新增 sampler 字段（早期版本缺失导致采样器固定无法更改）；
    // 新增全套 ADetailer 高级参数（adModel/adConfidence/adDenoisingStrength 等），
    // 字段名严格对齐 ADetailer-Neo 的 ADetailerArgs 定义，避免 pydantic extra="forbid" 报错。
    // ADetailer 默认值与 sdGenerationService 中的 ADETAILER_* 常量保持一致。
    sdWebui: {
      endpoint: 'http://localhost:7860',
      model: '',
      denoisingStrength: 0.55,
      steps: 28,
      cfgScale: 7,
      sampler: 'DPM++ 3M SDE',
      scheduler: 'Karras',
      clipSkip: 2,
      adetailerEnabled: true,
      // 【重点标记 - 特征携带机制（Spec: add-asset-and-trait-management / Task 5）】
      // 默认模板含 {traits} 与 {emotion} 两个占位符：
      // - {traits} 放在 portrait 之后，确保角色视觉特征（如 white fur, dog girl）优先注入
      // - {emotion} 位置保留，由 PromptBuilder.buildExpressionGenerationPrompt 替换为情绪专用提示词
      // 旧配置（仅含 {emotion}）由 PromptBuilder 兼容处理：特征 tag 会在 prompt 开头追加
      positivePromptTemplate: 'portrait, {traits}, looking at viewer, simple background, {emotion}, high quality, best quality, masterpiece, detailed face',
      customNegativePrompt: '',
      // ADetailer 高级参数默认值（与 sdGenerationService ADETAILER_* 常量一致）
      // 【重点标记 - ADetailer 参数优化（2026-07-29）】表情图模糊修复：
      // 降低降噪强度、增大蒙版模糊/膨胀、提高修复分辨率
      adModel: 'face_yolov8n.pt',
      adConfidence: 0.3,
      adDenoisingStrength: 0.3,
      adMaskBlur: 8,
      adDilateErode: 8,
      adInpaintOnlyMasked: true,
      adInpaintOnlyMaskedPadding: 64,
      adUseInpaintWidthHeight: true,
      adInpaintWidth: 1024,
      adInpaintHeight: 1024,
      adUseSteps: true,
      adSteps: 30,
      adUseCfgScale: true,
      adCfgScale: 5.0,
      adUseSampler: true,
      adSampler: 'DPM++ 2M SDE',
      adScheduler: 'Use same scheduler',
      // 【重点标记 - ADetailer 面部修复专用参数（2026-07-29 源码核验）】
      // adNegativePrompt：ADetailer 独立负面提示词，空=沿用主负面提示词，可针对性优化面部
      // adUseNoiseMultiplier/adNoiseMultiplier：独立噪声倍率（0.5-1.5），控制面部修复细节
      adNegativePrompt: '',
      adUseNoiseMultiplier: true,
      adNoiseMultiplier: 1.0,
      modelType: 'sdxl' as const,
      nlPromptTemplate: 'A portrait of a character. {traits} The character has {emotion}, looking at the viewer. High quality, detailed.',
      txt2imgWidth: 1024,
      txt2imgHeight: 1024,
      selectedLoras: [] as Array<{ name: string; weight: number }>,
      // 【Hires.fix】默认开启修复与放大，4x-AnimeSharp 放大器
      hrFixEnabled: true,
      hrUpscaler: '4x-AnimeSharp',
      hrSteps: 50,
      hrScale: 2.0,
      hrDenoisingStrength: 0.55,
      hrPrompt: '',
      hrNegativePrompt: '',
      hrCfg: 5.0,
      hrSamplerName: 'DPM++ 2M SDE',
      hrScheduler: 'Karras',
      img2imgExtraNoise: 0.05,
      initialNoiseMultiplier: 1.0,
      // 【img2img 高清模式】默认两步放大（768→1024）
      img2imgHiresMode: 'two-step',
    }
  }
};
