/**
 * 世界书组工具 —— worldbook mode 工具集
 *
 * 来源：spec §二 Task 17.1（世界书组工具：createEntry / expandFromContext /
 *       generateKeywords / sortEntries）
 * 决策：自研（spec §三无对应 openclaw 文件）。世界书自驱是本项目特有业务，
 *       复用现有服务（worldBookService）。
 *
 * 四个工具：
 *  1. createEntry         —— 在指定世界书中创建新条目（标记 autoGenerated=true，进入待审阅区）
 *  2. expandFromContext   —— 基于上下文文本扩展生成 lore 条目（批量 autoGenerated）
 *  3. generateKeywords    —— 为已有条目生成关键词（key + secondaryKeys）
 *  4. sortEntries         —— 按主题/相关性重排条目顺序（仅调整 order/displayIndex，不改内容）
 *
 * 设计约束（spec §5.4 沙盒隔离 + §5.1 双轨并行）：
 *  - 写工具（createEntry/expandFromContext）默认写入"草稿"区（autoGenerated=true），
 *    需用户在 UI 待审阅区确认后才转为正式条目（autoGenerated=false）
 *  - 沙盒：agent 仅能写入 context.allowedWorldBookPaths 白名单内的世界书；
 *    越权 → 返回 SANDBOX_VIOLATION 错误，不执行写入
 *  - 可用性限制：仅 mode='worldbook' 时可用（availability 表达式 gating）
 *  - 闭环返回：执行结果回灌给 LLM，让模型知道写入/排序结果
 *  - 降级保护：工具失败不中断 agentLoop，转为 ToolExecutionResult
 */

import type { ToolDescriptor } from '../types';
import type { ToolCallContext, ToolExecutionResult } from '../../contracts';
import type { ToolExecutor } from '../toolRegistry';

// ==================== 服务接口（依赖注入） ====================

/**
 * 世界书组工具依赖的服务接口。
 *
 * 由调用方（agentHandlers）注入实际实现，工具代码不直接 import worldBookService，
 * 保持低耦合（与 dialogueTools 的 IDialogueToolServices 模式一致）。
 *
 * 写入的条目均带 `autoGenerated: true` 标记，进入待审阅区；
 * 用户在 UI 审阅后通过 approve/reject 决定是否保留（SubTask 17.2）。
 */
export interface IWorldbookToolServices {
  /**
   * 读取世界书内容（含 entries）。
   * @returns 标准化后的世界书对象，或 null（读取失败）
   */
  readWorldBook(
    filePath: string
  ): Promise<{
    name?: string;
    description?: string;
    entries?: Array<Record<string, unknown>>;
  } | null>;

  /**
   * 写入完整世界书内容（覆盖写）。
   * 调用方负责保证 data 完整性（通常先 read 再修改再 write）。
   */
  writeWorldBook(
    filePath: string,
    data: {
      name?: string;
      description?: string;
      entries?: Array<Record<string, unknown>> | Record<string, Record<string, unknown>>;
      [key: string]: unknown;
    }
  ): Promise<{ success: boolean; error?: string }>;

  /**
   * 读取世界书描述（用于 prompt 上下文）。
   */
  getWorldBookDescription(filePath: string): Promise<string>;
}

// ==================== 共用辅助函数 ====================

/**
 * 校验 worldBookPath 是否在沙盒白名单内。
 * spec §5.4 沙盒隔离：agent 仅能写入白名单内的世界书。
 */
function assertSandboxAllowed(
  worldBookPath: string,
  context?: ToolCallContext
): { allowed: boolean; reason?: string } {
  if (!context?.allowedWorldBookPaths || context.allowedWorldBookPaths.length === 0) {
    // 未配置白名单时，允许写入（向后兼容；生产环境应由调用方显式配置白名单）
    return { allowed: true };
  }
  const normalized = worldBookPath.replace(/\\/g, '/').toLowerCase();
  const allowed = context.allowedWorldBookPaths.some(
    (p) => p.replace(/\\/g, '/').toLowerCase() === normalized
  );
  if (!allowed) {
    return {
      allowed: false,
      reason: `Sandbox violation: worldBookPath "${worldBookPath}" is not in allowedWorldBookPaths whitelist. The agent can only modify worldbooks explicitly granted by the user.`,
    };
  }
  return { allowed: true };
}

/**
 * 从世界书 entries 中提取最大 uid（用于新条目 id 分配）。
 * 兼容 entries 为 Array 或 Record 两种存储形态。
 */
function extractMaxUid(entries: unknown): number {
  if (!entries) return 0;
  let maxUid = 0;
  const iterate = (entry: any) => {
    const uid = typeof entry?.uid === 'number' ? entry.uid : parseInt(String(entry?.uid || '0'), 10);
    if (!isNaN(uid) && uid > maxUid) maxUid = uid;
  };
  if (Array.isArray(entries)) {
    for (const e of entries) iterate(e);
  } else if (typeof entries === 'object') {
    for (const _k of Object.keys(entries as object)) {
      iterate((entries as Record<string, any>)[_k]);
    }
  }
  return maxUid;
}

/**
 * 将 entries 标准化为数组形式（便于追加）。
 */
function entriesToArray(entries: unknown): Array<Record<string, unknown>> {
  if (!entries) return [];
  if (Array.isArray(entries)) return entries as Array<Record<string, unknown>>;
  if (typeof entries === 'object') {
    return Object.values(entries as Record<string, Record<string, unknown>>);
  }
  return [];
}

/**
 * 构造一个 autoGenerated 草稿条目。
 * 字段对齐 worldBookService.migrateEntry 的标准化输出。
 */
function buildAutoGeneratedEntry(
  uid: number,
  name: string,
  content: string,
  keys: string[],
  secondaryKeys: string[],
  comment: string,
  provenance: { source: string; runId?: string; toolName: string; timestamp: number }
): Record<string, unknown> {
  return {
    uid,
    id: uid,
    name: name || `Entry ${uid}`,
    comment: comment || name,
    content,
    key: keys,
    secondaryKeys,
    keysecondary: secondaryKeys,
    tags: ['auto-generated'],
    triggers: [],
    characterFilter: { isExclude: false, names: [], tags: [] },
    order: 100,
    position: 1,
    depth: 4,
    probability: 100,
    group: '',
    disable: false,
    useRegex: false,
    vectorized: false,
    caseSensitive: false,
    priority: 100,
    insertion_order: 100,
    enabled: true,
    extensions: {
      depth: 4,
      weight: 10,
      addMemo: true,
      displayIndex: uid,
      useProbability: true,
      characterFilter: null,
      excludeRecursion: false,
    },
    delayUntilRecursion: 0,
    selectiveLogic: 0,
    displayIndex: uid,
    useProbability: true,
    addMemo: true,
    excludeRecursion: false,
    automationId: '',
    outletName: '',
    matchPersonaDescription: false,
    matchCharacterDescription: false,
    matchCharacterPersonality: false,
    matchCharacterDepthPrompt: false,
    matchScenario: false,
    matchCreatorNotes: false,
    ignoreBudget: false,
    preventRecursion: false,
    constant: false,
    selective: true,
    // ===== Task 17 新增：autoGenerated 草稿标记 + 写溯源 =====
    autoGenerated: true,
    provenance,
  };
}

// ==================== createEntry 工具 ====================

export const createEntryDescriptor: ToolDescriptor = {
  name: 'createEntry',
  title: 'Create Worldbook Entry',
  description: `Create a new entry in a worldbook. The entry is created as a draft (autoGenerated=true) and will appear in the "Pending Review" area of the WorldBook manager UI. The user must approve it before it becomes a permanent entry.

Use this when the agent discovers new lore, characters, locations, or world rules that should be recorded in the worldbook.

Parameters:
- worldBookPath: Absolute path to the worldbook .json file (must be in the allowed whitelist)
- name: Short entry name / title (e.g., "Kingdom of Aldoria")
- content: Full entry content describing the lore (1-3 paragraphs)
- keys: Primary trigger keywords array (words that activate this entry)
- secondaryKeys: Optional secondary keywords array
- comment: Optional short comment / memo (defaults to name)

Returns: Confirmation with the new entry UID, or sandbox violation error.`,
  inputSchema: {
    type: 'object',
    properties: {
      worldBookPath: {
        type: 'string',
        description: 'Absolute path to the worldbook .json file',
      },
      name: {
        type: 'string',
        description: 'Short entry name / title',
      },
      content: {
        type: 'string',
        description: 'Full entry content describing the lore',
      },
      keys: {
        type: 'array',
        items: { type: 'string' },
        description: 'Primary trigger keywords',
      },
      secondaryKeys: {
        type: 'array',
        items: { type: 'string' },
        description: 'Optional secondary keywords',
      },
      comment: {
        type: 'string',
        description: 'Optional short comment / memo',
      },
    },
    required: ['worldBookPath', 'name', 'content', 'keys'],
  },
  owner: { kind: 'core' },
  availability: {
    kind: 'context',
    key: 'mode',
    equals: 'worldbook',
  },
  annotations: { group: 'worldbook', sortKey: '010' },
};

export function createCreateEntryExecutor(
  services: IWorldbookToolServices
): ToolExecutor {
  return async (
    args: Record<string, unknown>,
    context?: ToolCallContext
  ): Promise<ToolExecutionResult> => {
    const worldBookPath = String(args.worldBookPath || '').trim();
    const name = String(args.name || '').trim();
    const content = String(args.content || '').trim();
    const keys = Array.isArray(args.keys) ? args.keys.map(String).filter(Boolean) : [];
    const secondaryKeys = Array.isArray(args.secondaryKeys)
      ? args.secondaryKeys.map(String).filter(Boolean)
      : [];
    const comment = typeof args.comment === 'string' ? args.comment.trim() : name;

    // 参数校验
    if (!worldBookPath) {
      return { success: false, content: 'Parameter "worldBookPath" is required.', continueLoop: false };
    }
    if (!name) {
      return { success: false, content: 'Parameter "name" is required.', continueLoop: false };
    }
    if (!content) {
      return { success: false, content: 'Parameter "content" is required.', continueLoop: false };
    }
    if (keys.length === 0) {
      return {
        success: false,
        content: 'Parameter "keys" must be a non-empty array of trigger keywords.',
        continueLoop: false,
      };
    }

    // 沙盒校验
    const sandbox = assertSandboxAllowed(worldBookPath, context);
    if (!sandbox.allowed) {
      return { success: false, content: sandbox.reason || 'Sandbox violation.', continueLoop: false };
    }

    try {
      const worldBook = await services.readWorldBook(worldBookPath);
      if (!worldBook) {
        return {
          success: false,
          content: `Failed to read worldbook at: ${worldBookPath}. Check the path is correct.`,
          continueLoop: true,
        };
      }

      const entriesArr = entriesToArray(worldBook.entries);
      const maxUid = extractMaxUid(worldBook.entries);
      const newUid = maxUid + 1;

      const newEntry = buildAutoGeneratedEntry(
        newUid,
        name,
        content,
        keys,
        secondaryKeys,
        comment,
        {
          source: 'agent',
          runId: context?.sessionId,
          toolName: 'createEntry',
          timestamp: Date.now(),
        }
      );

      entriesArr.push(newEntry);

      const writeResult = await services.writeWorldBook(worldBookPath, {
        ...worldBook,
        entries: entriesArr,
      });

      if (!writeResult.success) {
        return {
          success: false,
          content: `Failed to write worldbook: ${writeResult.error || 'unknown error'}`,
          continueLoop: true,
        };
      }

      return {
        success: true,
        content: `Entry created successfully as draft (autoGenerated=true, pending user review).
- UID: ${newUid}
- Name: ${name}
- Keys: ${keys.join(', ')}${secondaryKeys.length ? ` | Secondary: ${secondaryKeys.join(', ')}` : ''}
- Worldbook: ${worldBookPath}

The entry is now in the "Pending Review" area. The user will approve or reject it. Do not create duplicate entries for the same lore.`,
        continueLoop: true,
      };
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : String(err);
      return {
        success: false,
        content: `createEntry failed: ${errMsg}`,
        continueLoop: true,
      };
    }
  };
}

// ==================== expandFromContext 工具 ====================

export const expandFromContextDescriptor: ToolDescriptor = {
  name: 'expandFromContext',
  title: 'Expand Lore From Context',
  description: `Create multiple new worldbook entries by extracting lore from a given context text. This is useful when the agent has a body of text (e.g., a chapter, dialogue, or scenario) and wants to extract and record all relevant lore entities (characters, locations, items, rules).

All extracted entries are created as drafts (autoGenerated=true) and appear in the "Pending Review" area.

Parameters:
- worldBookPath: Absolute path to the worldbook .json file
- contextText: The source text to extract lore from (e.g., chapter content, dialogue)
- entries: Array of extracted entry objects, each with {name, content, keys, secondaryKeys?, comment?}

Returns: Confirmation with the count and UIDs of created draft entries.`,
  inputSchema: {
    type: 'object',
    properties: {
      worldBookPath: {
        type: 'string',
        description: 'Absolute path to the worldbook .json file',
      },
      contextText: {
        type: 'string',
        description: 'The source text to extract lore from',
      },
      entries: {
        type: 'array',
        description: 'Array of extracted entry objects',
        items: {
          type: 'object',
          properties: {
            name: { type: 'string', description: 'Entry name / title' },
            content: { type: 'string', description: 'Entry content' },
            keys: { type: 'array', items: { type: 'string' }, description: 'Primary keywords' },
            secondaryKeys: {
              type: 'array',
              items: { type: 'string' },
              description: 'Optional secondary keywords',
            },
            comment: { type: 'string', description: 'Optional comment / memo' },
          },
          required: ['name', 'content', 'keys'],
        },
      },
    },
    required: ['worldBookPath', 'contextText', 'entries'],
  },
  owner: { kind: 'core' },
  availability: {
    kind: 'context',
    key: 'mode',
    equals: 'worldbook',
  },
  annotations: { group: 'worldbook', sortKey: '020' },
};

export function createExpandFromContextExecutor(
  services: IWorldbookToolServices
): ToolExecutor {
  return async (
    args: Record<string, unknown>,
    context?: ToolCallContext
  ): Promise<ToolExecutionResult> => {
    const worldBookPath = String(args.worldBookPath || '').trim();
    const contextText = String(args.contextText || '').trim();
    const rawEntries = Array.isArray(args.entries) ? args.entries : [];

    if (!worldBookPath) {
      return { success: false, content: 'Parameter "worldBookPath" is required.', continueLoop: false };
    }
    if (!contextText) {
      return { success: false, content: 'Parameter "contextText" is required.', continueLoop: false };
    }
    if (rawEntries.length === 0) {
      return {
        success: false,
        content: 'Parameter "entries" must be a non-empty array of entry objects.',
        continueLoop: false,
      };
    }

    // 沙盒校验
    const sandbox = assertSandboxAllowed(worldBookPath, context);
    if (!sandbox.allowed) {
      return { success: false, content: sandbox.reason || 'Sandbox violation.', continueLoop: false };
    }

    // 校验每个 entry 的必填字段
    const validatedEntries: Array<{
      name: string;
      content: string;
      keys: string[];
      secondaryKeys: string[];
      comment: string;
    }> = [];
    for (let i = 0; i < rawEntries.length; i++) {
      const e = rawEntries[i] as Record<string, unknown>;
      const name = String(e?.name || '').trim();
      const content = String(e?.content || '').trim();
      const keys = Array.isArray(e?.keys) ? (e.keys as unknown[]).map(String).filter(Boolean) : [];
      if (!name || !content || keys.length === 0) {
        return {
          success: false,
          content: `entries[${i}] is invalid: "name", "content", and non-empty "keys" are required.`,
          continueLoop: false,
        };
      }
      validatedEntries.push({
        name,
        content,
        keys,
        secondaryKeys: Array.isArray(e?.secondaryKeys)
          ? (e.secondaryKeys as unknown[]).map(String).filter(Boolean)
          : [],
        comment: typeof e?.comment === 'string' ? (e.comment as string).trim() : name,
      });
    }

    try {
      const worldBook = await services.readWorldBook(worldBookPath);
      if (!worldBook) {
        return {
          success: false,
          content: `Failed to read worldbook at: ${worldBookPath}.`,
          continueLoop: true,
        };
      }

      const entriesArr = entriesToArray(worldBook.entries);
      let maxUid = extractMaxUid(worldBook.entries);
      const createdUids: number[] = [];

      for (const ve of validatedEntries) {
        maxUid += 1;
        const newEntry = buildAutoGeneratedEntry(
          maxUid,
          ve.name,
          ve.content,
          ve.keys,
          ve.secondaryKeys,
          ve.comment,
          {
            source: 'agent',
            runId: context?.sessionId,
            toolName: 'expandFromContext',
            timestamp: Date.now(),
          }
        );
        entriesArr.push(newEntry);
        createdUids.push(maxUid);
      }

      const writeResult = await services.writeWorldBook(worldBookPath, {
        ...worldBook,
        entries: entriesArr,
      });

      if (!writeResult.success) {
        return {
          success: false,
          content: `Failed to write worldbook: ${writeResult.error || 'unknown error'}`,
          continueLoop: true,
        };
      }

      return {
        success: true,
        content: `Expanded ${createdUids.length} lore entries from context as drafts (autoGenerated=true, pending review).
- New UIDs: ${createdUids.join(', ')}
- Worldbook: ${worldBookPath}
- Source context length: ${contextText.length} chars

All entries are in the "Pending Review" area. The user will review and approve/reject them. Avoid extracting duplicate lore that already exists in the worldbook.`,
        continueLoop: true,
      };
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : String(err);
      return {
        success: false,
        content: `expandFromContext failed: ${errMsg}`,
        continueLoop: true,
      };
    }
  };
}

// ==================== generateKeywords 工具 ====================

export const generateKeywordsDescriptor: ToolDescriptor = {
  name: 'generateKeywords',
  title: 'Generate Keywords For Entry',
  description: `Generate or regenerate trigger keywords (primary + secondary) for an existing worldbook entry based on its content. This updates the entry's "key" and "secondaryKeys" fields in-place.

Use this when an entry has weak or missing keywords that would cause it to not activate properly during chat.

Parameters:
- worldBookPath: Absolute path to the worldbook .json file
- entryUid: The UID of the entry to update
- keys: New primary keywords array (replaces existing)
- secondaryKeys: New secondary keywords array (replaces existing; can be empty)

Returns: Confirmation with the updated keywords, or error if entry not found.`,
  inputSchema: {
    type: 'object',
    properties: {
      worldBookPath: {
        type: 'string',
        description: 'Absolute path to the worldbook .json file',
      },
      entryUid: {
        type: ['string', 'number'],
        description: 'The UID of the entry to update',
      },
      keys: {
        type: 'array',
        items: { type: 'string' },
        description: 'New primary keywords (replaces existing)',
      },
      secondaryKeys: {
        type: 'array',
        items: { type: 'string' },
        description: 'New secondary keywords (replaces existing; can be empty)',
      },
    },
    required: ['worldBookPath', 'entryUid', 'keys'],
  },
  owner: { kind: 'core' },
  availability: {
    kind: 'context',
    key: 'mode',
    equals: 'worldbook',
  },
  annotations: { group: 'worldbook', sortKey: '030' },
};

export function createGenerateKeywordsExecutor(
  services: IWorldbookToolServices
): ToolExecutor {
  return async (
    args: Record<string, unknown>,
    context?: ToolCallContext
  ): Promise<ToolExecutionResult> => {
    const worldBookPath = String(args.worldBookPath || '').trim();
    const entryUidRaw = args.entryUid;
    const keys = Array.isArray(args.keys) ? args.keys.map(String).filter(Boolean) : [];
    const secondaryKeys = Array.isArray(args.secondaryKeys)
      ? args.secondaryKeys.map(String).filter(Boolean)
      : [];

    if (!worldBookPath) {
      return { success: false, content: 'Parameter "worldBookPath" is required.', continueLoop: false };
    }
    if (entryUidRaw === undefined || entryUidRaw === null || entryUidRaw === '') {
      return { success: false, content: 'Parameter "entryUid" is required.', continueLoop: false };
    }
    if (keys.length === 0) {
      return {
        success: false,
        content: 'Parameter "keys" must be a non-empty array of keywords.',
        continueLoop: false,
      };
    }

    // 沙盒校验
    const sandbox = assertSandboxAllowed(worldBookPath, context);
    if (!sandbox.allowed) {
      return { success: false, content: sandbox.reason || 'Sandbox violation.', continueLoop: false };
    }

    const entryUidStr = String(entryUidRaw);

    try {
      const worldBook = await services.readWorldBook(worldBookPath);
      if (!worldBook) {
        return {
          success: false,
          content: `Failed to read worldbook at: ${worldBookPath}.`,
          continueLoop: true,
        };
      }

      const entriesArr = entriesToArray(worldBook.entries);
      let targetIndex = -1;
      for (let i = 0; i < entriesArr.length; i++) {
        const e = entriesArr[i];
        if (String(e.uid || '') === entryUidStr) {
          targetIndex = i;
          break;
        }
      }
      if (targetIndex === -1) {
        return {
          success: false,
          content: `Entry with UID "${entryUidStr}" not found in worldbook.`,
          continueLoop: true,
        };
      }

      // 更新关键词（保留旧值用于回显对比）
      const oldKeys = Array.isArray(entriesArr[targetIndex].key)
        ? (entriesArr[targetIndex].key as unknown[]).map(String)
        : [];
      const oldSecondary = Array.isArray(entriesArr[targetIndex].secondaryKeys)
        ? (entriesArr[targetIndex].secondaryKeys as unknown[]).map(String)
        : [];

      entriesArr[targetIndex].key = keys;
      entriesArr[targetIndex].secondaryKeys = secondaryKeys;
      entriesArr[targetIndex].keysecondary = secondaryKeys;

      const writeResult = await services.writeWorldBook(worldBookPath, {
        ...worldBook,
        entries: entriesArr,
      });

      if (!writeResult.success) {
        return {
          success: false,
          content: `Failed to write worldbook: ${writeResult.error || 'unknown error'}`,
          continueLoop: true,
        };
      }

      return {
        success: true,
        content: `Keywords updated for entry UID ${entryUidStr} ("${entriesArr[targetIndex].name || ''}").
- Old keys: ${oldKeys.join(', ') || '(none)'}
- New keys: ${keys.join(', ')}
- Old secondary: ${oldSecondary.join(', ') || '(none)'}
- New secondary: ${secondaryKeys.join(', ') || '(none)'}

The change is applied immediately (not a draft, since this is an in-place edit of an existing entry).`,
        continueLoop: true,
      };
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : String(err);
      return {
        success: false,
        content: `generateKeywords failed: ${errMsg}`,
        continueLoop: true,
      };
    }
  };
}

// ==================== sortEntries 工具 ====================

export const sortEntriesDescriptor: ToolDescriptor = {
  name: 'sortEntries',
  title: 'Sort Worldbook Entries',
  description: `Reorder entries in a worldbook by updating their "order" and "displayIndex" fields based on a logical grouping (e.g., by topic, by entity type, or by importance). This does NOT modify entry content — only the sort order.

Use this when the worldbook has become disorganized and entries should be grouped logically for better readability and maintenance.

Parameters:
- worldBookPath: Absolute path to the worldbook .json file
- sortOrder: Array of entry UIDs (as strings or numbers) in the desired order, from first to last. All entries must be present exactly once.

Returns: Confirmation with the count of reordered entries.`,
  inputSchema: {
    type: 'object',
    properties: {
      worldBookPath: {
        type: 'string',
        description: 'Absolute path to the worldbook .json file',
      },
      sortOrder: {
        type: 'array',
        description: 'Array of entry UIDs in the desired order (first to last)',
        items: { type: ['string', 'number'] },
      },
    },
    required: ['worldBookPath', 'sortOrder'],
  },
  owner: { kind: 'core' },
  availability: {
    kind: 'context',
    key: 'mode',
    equals: 'worldbook',
  },
  annotations: { group: 'worldbook', sortKey: '040' },
};

export function createSortEntriesExecutor(
  services: IWorldbookToolServices
): ToolExecutor {
  return async (
    args: Record<string, unknown>,
    context?: ToolCallContext
  ): Promise<ToolExecutionResult> => {
    const worldBookPath = String(args.worldBookPath || '').trim();
    const sortOrderRaw = Array.isArray(args.sortOrder) ? args.sortOrder : [];

    if (!worldBookPath) {
      return { success: false, content: 'Parameter "worldBookPath" is required.', continueLoop: false };
    }
    if (sortOrderRaw.length === 0) {
      return {
        success: false,
        content: 'Parameter "sortOrder" must be a non-empty array of entry UIDs.',
        continueLoop: false,
      };
    }

    // 沙盒校验
    const sandbox = assertSandboxAllowed(worldBookPath, context);
    if (!sandbox.allowed) {
      return { success: false, content: sandbox.reason || 'Sandbox violation.', continueLoop: false };
    }

    const sortOrder = sortOrderRaw.map((v) => String(v));

    try {
      const worldBook = await services.readWorldBook(worldBookPath);
      if (!worldBook) {
        return {
          success: false,
          content: `Failed to read worldbook at: ${worldBookPath}.`,
          continueLoop: true,
        };
      }

      const entriesArr = entriesToArray(worldBook.entries);

      // 校验 sortOrder 完整性：必须覆盖所有条目且不重复
      const existingUids = new Set(entriesArr.map((e) => String(e.uid || '')));
      const orderSet = new Set(sortOrder);
      if (orderSet.size !== sortOrder.length) {
        return {
          success: false,
          content: 'sortOrder contains duplicate UIDs. Each entry must appear exactly once.',
          continueLoop: false,
        };
      }
      // 检查 sortOrder 中的 uid 是否都存在
      const unknownUids = sortOrder.filter((uid) => !existingUids.has(uid));
      if (unknownUids.length > 0) {
        return {
          success: false,
          content: `sortOrder references unknown UIDs: ${unknownUids.join(', ')}. All UIDs must exist in the worldbook.`,
          continueLoop: false,
        };
      }
      // 检查是否覆盖了所有条目
      const missingUids = [...existingUids].filter((uid) => !orderSet.has(uid));
      if (missingUids.length > 0) {
        return {
          success: false,
          content: `sortOrder is missing ${missingUids.length} entries (UIDs: ${missingUids.slice(0, 10).join(', ')}${missingUids.length > 10 ? '...' : ''}). All entries must be included exactly once.`,
          continueLoop: false,
        };
      }

      // 构建 uid → entry 映射
      const entryByUid = new Map<string, Record<string, unknown>>();
      for (const e of entriesArr) {
        entryByUid.set(String(e.uid || ''), e);
      }

      // 按 sortOrder 重建数组，并更新 order/displayIndex/insertion_order
      const reordered: Array<Record<string, unknown>> = [];
      for (let i = 0; i < sortOrder.length; i++) {
        const uid = sortOrder[i];
        const entry = entryByUid.get(uid);
        if (!entry) continue; // 已校验，理论不进入
        const newOrder = (i + 1) * 10; // 10, 20, 30... 留间隔便于手动插入
        entry.order = newOrder;
        entry.displayIndex = i;
        entry.insertion_order = newOrder;
        entry.priority = newOrder;
        reordered.push(entry);
      }

      const writeResult = await services.writeWorldBook(worldBookPath, {
        ...worldBook,
        entries: reordered,
      });

      if (!writeResult.success) {
        return {
          success: false,
          content: `Failed to write worldbook: ${writeResult.error || 'unknown error'}`,
          continueLoop: true,
        };
      }

      return {
        success: true,
        content: `Reordered ${reordered.length} entries in worldbook ${worldBookPath}.
Entries are now sorted by the specified order (order field: 10, 20, 30, ...). Entry content was not modified. The user may review the new order in the WorldBook manager.`,
        continueLoop: true,
      };
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : String(err);
      return {
        success: false,
        content: `sortEntries failed: ${errMsg}`,
        continueLoop: true,
      };
    }
  };
}

// ==================== 注册便捷函数 ====================

/**
 * 注册所有世界书组工具到 ToolRegistry。
 *
 * @param registry 工具注册中心
 * @param services 世界书组工具依赖的服务
 */
export function registerWorldbookTools(
  registry: { register: (descriptor: ToolDescriptor, executor: ToolExecutor) => void },
  services: IWorldbookToolServices
): void {
  const tools = [
    { descriptor: createEntryDescriptor, executor: createCreateEntryExecutor(services) },
    { descriptor: expandFromContextDescriptor, executor: createExpandFromContextExecutor(services) },
    { descriptor: generateKeywordsDescriptor, executor: createGenerateKeywordsExecutor(services) },
    { descriptor: sortEntriesDescriptor, executor: createSortEntriesExecutor(services) },
  ];

  for (const { descriptor, executor } of tools) {
    try {
      registry.register(descriptor, executor);
    } catch {
      // 工具可能已被注册（并发场景），忽略
    }
  }
}
