import { contextBridge, ipcRenderer } from 'electron';
import type { BatchFixRequest } from '../shared/types/writing.types';
import type { CharacterTraitManifestV2 } from '../shared/types/characterTrait.types';
import type {
  GameMeta,
  GameSaveData,
  GameTableData,
  GameTableEditCommand,
  GameNarrativeRequest,
  GameNarrativeChunk,
  GameNarrativeComplete,
  GameNarrativeError,
  GameTableUpdated,
  GameLocalConfig
} from '../shared/types/game.types';

// 存储 subscription 映射，以便 off 方法可以正确移除监听器
const subscriptionMap = new Map<string, Map<Function, Function>>();

contextBridge.exposeInMainWorld('electronAPI', {
  // 通用 invoke 方法，用于直接调用 IPC handler
  invoke: (channel: string, ...args: any[]) => ipcRenderer.invoke(channel, ...args),

  // 通用方法，用于监听 IPC 事件
  on: (channel: string, callback: (...args: any[]) => void) => {
    const subscription = (_event: any, ...args: any[]) => callback(...args);
    ipcRenderer.on(channel, subscription);
    
    // 保存 subscription 到映射中
    if (!subscriptionMap.has(channel)) {
      subscriptionMap.set(channel, new Map());
    }
    subscriptionMap.get(channel)!.set(callback, subscription);
    
    // 返回移除监听器的函数
    return () => {
      ipcRenderer.removeListener(channel, subscription);
      subscriptionMap.get(channel)?.delete(callback);
    };
  },
  off: (channel: string, callback: (...args: any[]) => void) => {
    // 从映射中获取对应的 subscription
    const channelMap = subscriptionMap.get(channel);
    if (channelMap && channelMap.has(callback)) {
      const subscription = channelMap.get(callback);
      ipcRenderer.removeListener(channel, subscription);
      channelMap.delete(callback);
    }
  },
  setting: {
    load: () => ipcRenderer.invoke('setting:load'),
    save: (setting: any) => ipcRenderer.invoke('setting:save', setting),
    getPath: () => ipcRenderer.invoke('setting:getPath')
  },
  worldBook: {
    list: () => ipcRenderer.invoke('worldBook:list'),
    read: (path: string) => ipcRenderer.invoke('worldBook:read', path),
    write: (path: string, data: any) => ipcRenderer.invoke('worldBook:write', path, data),
    delete: (path: string) => ipcRenderer.invoke('worldBook:delete', path),
    import: (sourcePath: string, fileName: string) => ipcRenderer.invoke('worldBook:import', sourcePath, fileName),
    optimize: (path: string) => ipcRenderer.invoke('worldBook:optimize', path),
    getDirectory: () => ipcRenderer.invoke('worldBook:getDirectory'),
    readTags: (path: string) => ipcRenderer.invoke('worldBook:readTags', path),
    writeTags: (path: string, data: any) => ipcRenderer.invoke('worldBook:writeTags', path, data),
    deleteTags: (path: string) => ipcRenderer.invoke('worldBook:deleteTags', path),
    saveToKnowledgeBase: (data: any, fileName: string) => ipcRenderer.invoke('worldBook:saveToKnowledgeBase', data, fileName),
    checkFileExists: (fileName: string) => ipcRenderer.invoke('worldBook:checkFileExists', fileName),
    vectorize: (path: string) => ipcRenderer.invoke('worldBook:vectorize', path),
    // Task 17.2: autoGenerated 草稿条目审阅流（世界书自驱）
    listAutoGenerated: (path: string) => ipcRenderer.invoke('worldBook:listAutoGenerated', path),
    approveAutoGenerated: (path: string, entryUid: string | number) => ipcRenderer.invoke('worldBook:approveAutoGenerated', path, entryUid),
    rejectAutoGenerated: (path: string, entryUid: string | number) => ipcRenderer.invoke('worldBook:rejectAutoGenerated', path, entryUid),
    approveAllAutoGenerated: (path: string) => ipcRenderer.invoke('worldBook:approveAllAutoGenerated', path)
  },
  // ============================================================================
  // 世界书编写智能体 API（Spec: implement-worldbook-authoring-agent / Task 5.1）
  // ============================================================================
  // 5 个 IPC 通道 + 2 个事件流：
  //   - worldbookAgent:run       启动编写会话（入参 {userPrompt, worldBookPath, allowedWorldBookPaths, config?}）
  //   - worldbookAgent:cancel    取消会话（入参 {sessionId}）
  //   - worldbookAgent:status    查询状态（入参 {sessionId?}）
  //   - worldbookAgent:resume    续跑会话（入参 {sessionId}）
  //   - worldbookAgent:answer    回答澄清问题（入参 {sessionId, answers}）
  //   - worldbookAgent:progress  进度事件流（主进程 → 渲染进程推送）
  //   - worldbookAgent:clarify   澄清问题事件流（预留）
  //
  // 【重点标记 - 参数包装】IPC handler 期望对象参数（如 { sessionId }），
  // preload 桥接负责将 hook 的原始参数包装为对象后透传。
  worldBookAgent: {
    run: (params: any) => ipcRenderer.invoke('worldbookAgent:run', params),
    cancel: (sessionId: string) => ipcRenderer.invoke('worldbookAgent:cancel', { sessionId }),
    status: (sessionId?: string) => ipcRenderer.invoke('worldbookAgent:status', { sessionId }),
    resume: (sessionId: string) => ipcRenderer.invoke('worldbookAgent:resume', { sessionId }),
    answer: (sessionId: string, answers: any) => ipcRenderer.invoke('worldbookAgent:answer', { sessionId, answers }),
    onProgress: (callback: (data: any) => void) => {
      const listener = (_event: any, data: any) => callback(data);
      ipcRenderer.on('worldbookAgent:progress', listener);
      return () => ipcRenderer.removeListener('worldbookAgent:progress', listener);
    },
    onClarify: (callback: (data: any) => void) => {
      const listener = (_event: any, data: any) => callback(data);
      ipcRenderer.on('worldbookAgent:clarify', listener);
      return () => ipcRenderer.removeListener('worldbookAgent:clarify', listener);
    },
  },
  webSearch: {
    test: (config: { provider: string; apiKey: string; endpoint: string }) =>
      ipcRenderer.invoke('webSearch:test', config),
    search: (args: { query: string; maxResults?: number }) =>
      ipcRenderer.invoke('webSearch:search', args),
  },
  character: {
    list: () => ipcRenderer.invoke('character:list'),
    read: (path: string) => ipcRenderer.invoke('character:read', path),
    write: (path: string, data: any) => ipcRenderer.invoke('character:write', path, data),
    createFromImage: (filePath: string, imageDataBase64: string, characterData: any) => ipcRenderer.invoke('character:createFromImage', filePath, imageDataBase64, characterData),
    delete: (path: string) => ipcRenderer.invoke('character:delete', path),
    optimize: (path: string) => ipcRenderer.invoke('character:optimize', path),
    getDirectory: () => ipcRenderer.invoke('character:getDirectory'),
    import: (sourcePath: string, fileName: string) => ipcRenderer.invoke('character:import', sourcePath, fileName),
    getWorldBookRelations: (path: string) => ipcRenderer.invoke('character:getWorldBookRelations', path),
    setWorldBookRelations: (path: string, relations: any[]) => ipcRenderer.invoke('character:setWorldBookRelations', path, relations),
    savePNGToDirectory: (base64Data: string, filename: string) => ipcRenderer.invoke('character:savePNGToDirectory', base64Data, filename),
    exportCharacterCard: (params: { base64Image: string; filename: string; characterData: any }) => ipcRenderer.invoke('character:exportCharacterCard', params)
  },
  characterConfig: {
    save: (characterCardId: string, config: any) => ipcRenderer.invoke('characterConfig:save', characterCardId, config),
    load: (characterCardId: string) => ipcRenderer.invoke('characterConfig:load', characterCardId)
  },
  avatar: {
    list: () => ipcRenderer.invoke('avatar:list'),
    read: (path: string) => ipcRenderer.invoke('avatar:read', path),
    write: (path: string, data: any) => ipcRenderer.invoke('avatar:write', path, data),
    delete: (path: string) => ipcRenderer.invoke('avatar:delete', path),
    getDirectory: () => ipcRenderer.invoke('avatar:getDirectory')
  },
  plugin: {
    getAvailable: (forceRefresh?: boolean) => ipcRenderer.invoke('plugin:getAvailable', forceRefresh),
    getInstalled: () => ipcRenderer.invoke('plugin:getInstalled'),
    toggle: (pluginId: string, enabled: boolean) => ipcRenderer.invoke('plugin:toggle', pluginId, enabled),
    uninstall: (pluginId: string) => ipcRenderer.invoke('plugin:uninstall', pluginId),
    getDirectory: () => ipcRenderer.invoke('plugin:getDirectory'),
    checkUpdates: () => ipcRenderer.invoke('plugin:checkUpdates'),
    updateDescriptions: (translatedPlugins: any[]) => ipcRenderer.invoke('plugin:updateDescriptions', translatedPlugins),
    install: (url: string, branch?: string) => ipcRenderer.invoke('plugin:install', url, branch),
    uninstallById: (pluginId: string) => ipcRenderer.invoke('plugin:uninstallById', pluginId)
  },
  file: {
    selectDirectory: () => ipcRenderer.invoke('file:selectDirectory'),
    selectFile: (filters: any[]) => ipcRenderer.invoke('file:selectFile', filters),
    exists: (path: string) => ipcRenderer.invoke('file:exists', path),
    read: (path: string) => ipcRenderer.invoke('file:read', path),
    write: (path: string, content: string) => ipcRenderer.invoke('file:write', path, content),
    writeBinary: (path: string, content: string, isBase64?: boolean) => ipcRenderer.invoke('file:writeBinary', path, content, isBase64),
    copyFile: (sourcePath: string, targetPath: string) => ipcRenderer.invoke('file:copyFile', sourcePath, targetPath),
    openFolder: (path: string) => ipcRenderer.invoke('file:openFolder', path),
    openFile: (path: string) => ipcRenderer.invoke('file:openFile', path),
    readJson: (fileName: string) => ipcRenderer.invoke('file:readJson', fileName),
    readAsBase64: (path: string) => ipcRenderer.invoke('file:readAsBase64', path),
    validatePath: (path: string) => ipcRenderer.invoke('file:validatePath', path)
  },
  app: {
    getVersion: () => ipcRenderer.invoke('app:getVersion'),
    getPlatform: () => ipcRenderer.invoke('app:getPlatform'),
    openPath: (path: string) => ipcRenderer.invoke('app:openPath', path),
    getUserDataPath: () => ipcRenderer.invoke('app:getUserDataPath'),
    getUserDataSize: () => ipcRenderer.invoke('app:getUserDataSize'),
    getRootPath: () => ipcRenderer.invoke('app:getRootPath'),
    openConfigFile: () => ipcRenderer.invoke('app:openConfigFile')
  },
  update: {
    check: () => ipcRenderer.invoke('update:check'),
    pull: () => ipcRenderer.invoke('update:pull')
  },
  // 日志事件监听
  // 记忆插件 API
  memory: {
    // 获取记忆目录
    getMemoryDirectory: () => ipcRenderer.invoke('memory:getMemoryDirectory'),
    // 表格模板管理
    getAllTemplates: () => ipcRenderer.invoke('memory:getAllTemplates'),
    getTemplate: (templateId: string) => ipcRenderer.invoke('memory:getTemplate', templateId),
    createTemplate: (template: any) => ipcRenderer.invoke('memory:createTemplate', template),
    updateTemplate: (templateId: string, updates: any) => ipcRenderer.invoke('memory:updateTemplate', templateId, updates),
    deleteTemplate: (templateId: string) => ipcRenderer.invoke('memory:deleteTemplate', templateId),
    createTableFile: (chatId: string, templateId: string) => ipcRenderer.invoke('memory:createTableFile', chatId, templateId),
    readTableFile: (chatId: string) => ipcRenderer.invoke('memory:readTableFile', chatId),
    updateTableFile: (chatId: string, sheetName: string, data: any[]) => ipcRenderer.invoke('memory:updateTableFile', chatId, sheetName, data),
    getVersionHistory: (templateId: string) => ipcRenderer.invoke('memory:getVersionHistory', templateId),
    restoreVersion: (templateId: string, version: string) => ipcRenderer.invoke('memory:restoreVersion', templateId, version),
    getTemplateBindingStatus: () => ipcRenderer.invoke('memory:getTemplateBindingStatus'),
    
    // 聊天记录管理
    getChatSessions: () => ipcRenderer.invoke('memory:getChatSessions'),
    getChatSession: (chatId: string) => ipcRenderer.invoke('memory:getChatSession', chatId),
    getChatMessages: (chatId: string, page: number, pageSize: number) => ipcRenderer.invoke('memory:getChatMessages', chatId, page, pageSize),
    searchChatMessages: (keyword: string, chatId?: string) => ipcRenderer.invoke('memory:searchChatMessages', keyword, chatId),
    filterChatMessages: (chatId: string, filters: any) => ipcRenderer.invoke('memory:filterChatMessages', chatId, filters),
    processChatWithAI: (chatId: string, templateId: string, config: any) => ipcRenderer.invoke('memory:processChatWithAI', chatId, templateId, config),
    applyAIResults: (chatId: string, results: any[]) => ipcRenderer.invoke('memory:applyAIResults', chatId, results),
    deleteChatSession: (chatId: string) => ipcRenderer.invoke('memory:deleteChatSession', chatId),
    associateTemplate: (chatId: string, templateId: string) => ipcRenderer.invoke('memory:associateTemplate', chatId, templateId),
    getAssociatedTemplate: (chatId: string) => ipcRenderer.invoke('memory:getAssociatedTemplate', chatId),
    processChat: (chatId: string, templateId: string, selectedMessageIds: string[], config: { apiKey: string; apiUrl: string; modelName: string; apiMode: string }) => ipcRenderer.invoke('memory:processChat', chatId, templateId, selectedMessageIds, config),
    processChatProgressive: (chatId: string, templateId: string, config: { apiKey: string; apiUrl: string; modelName: string; apiMode: string }, options?: { continueFromLast?: boolean; minInterval?: number }) => ipcRenderer.invoke('memory:processChatProgressive', chatId, templateId, config, options),
    stopOrganizing: (chatId: string) => ipcRenderer.invoke('memory:stopOrganizing', chatId),
    processChatFull: (chatId: string, templateId: string, config: { apiKey: string; apiUrl: string; modelName: string; apiMode: string }) => ipcRenderer.invoke('memory:processChatFull', chatId, templateId, config),
    executeTableEditCommands: (chatId: string, commands: any[]) => ipcRenderer.invoke('memory:executeTableEditCommands', chatId, commands),
    parseTableEdit: (content: string) => ipcRenderer.invoke('memory:parseTableEdit', content),
    updateRowInTable: (chatId: string, tableIndex: number, rowIndex: number, rowData: Record<string, string>) =>
      ipcRenderer.invoke('memory:updateRowInTable', chatId, tableIndex, rowIndex, rowData),
    getOrganizingProgress: (chatId: string) => ipcRenderer.invoke('memory:getOrganizingProgress', chatId),
    clearOrganizingProgress: (chatId: string) => ipcRenderer.invoke('memory:clearOrganizingProgress', chatId),
    clearTableData: (chatId: string) => ipcRenderer.invoke('memory:clearTableData', chatId),
    copyTemplate: (sourceTemplateId: string, newTemplateName: string) => ipcRenderer.invoke('memory:copyTemplate', sourceTemplateId, newTemplateName),// 表格数据管理
    getTableData: (chatId: string) => ipcRenderer.invoke('memory:getTableData', chatId),
    saveTableData: (chatId: string, sheetName: string, sheetData: any[]) => ipcRenderer.invoke('memory:saveTableData', chatId, sheetName, sheetData),
    autoInitializeSession: (chatId: string) => ipcRenderer.invoke('memory:autoInitializeSession', chatId),

    getCharacterChatRecords: () => ipcRenderer.invoke('memory:getCharacterChatRecords'),
    getCharacterChatRecord: (fileName: string) => ipcRenderer.invoke('memory:getCharacterChatRecord', fileName),
    saveCharacterChatRecord: (fileName: string, content: string) => ipcRenderer.invoke('memory:saveCharacterChatRecord', fileName, content),
    deleteCharacterChatRecord: (fileName: string, characterCardName: string) => ipcRenderer.invoke('memory:deleteCharacterChatRecord', fileName, characterCardName),
    vectorizeCharacterChat: (fileName: string) => ipcRenderer.invoke('memory:vectorizeCharacterChat', fileName),
    getCharacterThumbnail: (characterCardName: string) => ipcRenderer.invoke('memory:getCharacterThumbnail', characterCardName),

    // 外部系统调用 API（供其他系统调用）
    external: {
      processSingleChat: (request: any) => ipcRenderer.invoke('memory:external:processSingleChat', request),
      processBatchChat: (request: any) => ipcRenderer.invoke('memory:external:processBatchChat', request)
    }
  },
  // AI 请求 API
  ai: {
    request: (config: { url: string; method: string; headers: Record<string, string>; body: any; timeout?: number; streaming?: boolean }) =>
      ipcRenderer.invoke('ai:request', config),
    cancel: () => ipcRenderer.invoke('ai:cancel'),
    listModels: (params: { apiUrl?: string; apiKey?: string; apiKeyTransmission?: string }) =>
      ipcRenderer.invoke('ai:listModels', params),
    // AI 辅助角色特征生成（Spec: add-asset-and-trait-management / Task 12）
    // 基于角色卡 description/personality/scenario 调用 LLM 生成「带分类」视觉特征列表 + 角色外观描述
    // 返回 { success, traits?: CategorizedTrait[], appearanceDescription?: string, error?: string }，traits 可能为空数组
    // 【重点标记 - AI 自动归类增强】traits 由 string[] 升级为 CategorizedTrait[]（{ text, categoryId }），
    // 使 AI 生成的特征直接携带系统分类信息，进入 store 后无需用户手动归类
    generateCharacterTraits: (args: {
      characterCardId: string;
      description: string;
      personality?: string;
      scenario?: string;
      includeImage?: boolean;
    }) => ipcRenderer.invoke('ai:generateCharacterTraits', args),
    // AI 图片识别特征提取（Spec: add-model-capability-detection-and-image-recognition / Task 6）
    // 通过多模态模型识别角色卡 PNG 图片，提取「带分类」视觉特征列表 + 角色外观描述
    // 前置条件：当前 AI 引擎 supportsVision=true（由前端判断）
    // 返回 { success, traits?: CategorizedTrait[], appearanceDescription?: string, error?: string }，traits 可能为空数组
    recognizeImageTraits: (args: { characterCardPath: string; characterName?: string }) =>
      ipcRenderer.invoke('ai:recognizeImageTraits', args),
    // 动态场景提示词生成（Spec: add-dynamic-scene-prompt-generation / Task 3）
    // 将自然语言指令解析为三组英文 SD tag（服装/动作/场景），未提及的维度返回空字符串
    // 入参：{ naturalLanguageInput: string, baseTraits?: string }
    // 返回：{ success, clothing?, pose?, scene?, error? } —— 三个字段均为逗号分隔的英文 tag 字符串
    // 错误场景：空输入（不调用 LLM）/ AI 引擎未配置 / 调用失败 / 解析失败
    generateDynamicScenePrompts: (args: {
      naturalLanguageInput: string;
      baseTraits?: string;
    }) => ipcRenderer.invoke('ai:generateDynamicScenePrompts', args),
    // 探测 AI 模型能力（Spec: add-model-capability-detection-and-image-recognition / Task 3）
    // 并行探测 vision / thinking / tool-calling，返回 { success, capabilities?, error? }
    probeCapabilities: (args: { apiUrl: string; apiKey: string; apiKeyTransmission: string; modelName: string }) =>
      ipcRenderer.invoke('ai:probeCapabilities', args),

    // 故障转移 API（Spec: optimize-agent-interaction-from-openclaw / Task 10）
    // 2 个 IPC 通道 + 1 个事件订阅：
    //   - ai:getFallbackProviders  获取备用 provider 列表
    //   - ai:setFallbackProviders  设置备用 provider 列表
    //   - ai:failover              故障转移事件订阅（主进程 → 渲染进程）
    failover: {
      getProviders: () => ipcRenderer.invoke('ai:getFallbackProviders'),
      setProviders: (providers: any[]) =>
        ipcRenderer.invoke('ai:setFallbackProviders', { providers }),
      onFailover: (callback: (data: any) => void) => {
        const subscription = (_event: unknown, data: any) => callback(data);
        ipcRenderer.on('ai:failover', subscription);
        return () => ipcRenderer.removeListener('ai:failover', subscription);
      },
    },
  },
  // 创意数据 API
  creative: {
    load: () => ipcRenderer.invoke('creative:load'),
    save: (data: any) => ipcRenderer.invoke('creative:save', data),
    export: () => ipcRenderer.invoke('creative:export'),
    import: (jsonData: string) => ipcRenderer.invoke('creative:import', jsonData),
    getDirectory: () => ipcRenderer.invoke('creative:getDirectory')
  },
  // 角色卡对话数据 API
  characterChat: {
    getTestChat: (creativeId: string, characterCardId: string) => ipcRenderer.invoke('characterChat:getTestChat', creativeId, characterCardId),
    saveTestChat: (creativeId: string, characterCardId: string, characterCardName: string, messages: any[]) => ipcRenderer.invoke('characterChat:saveTestChat', creativeId, characterCardId, characterCardName, messages),
    deleteTestChat: (creativeId: string, characterCardId: string) => ipcRenderer.invoke('characterChat:deleteTestChat', creativeId, characterCardId),
    getAllTestChats: () => ipcRenderer.invoke('characterChat:getAllTestChats'),
    clearCache: () => ipcRenderer.invoke('characterChat:clearCache')
  },
  // 聊天记录版本管理 API
  chatVersion: {
    getVersions: (characterCardName: string) => ipcRenderer.invoke('chatVersion:getVersions', characterCardName),
    getVersionContent: (filePath: string) => ipcRenderer.invoke('chatVersion:getVersionContent', filePath),
    deleteVersion: (filePath: string) => ipcRenderer.invoke('chatVersion:deleteVersion', filePath),
    getVersionsDir: (characterCardName: string) => ipcRenderer.invoke('chatVersion:getVersionsDir', characterCardName),
    getLinkedVersion: (characterCardName: string, versionLinkId: string) => ipcRenderer.invoke('chatVersion:getLinkedVersion', characterCardName, versionLinkId),
    createLinkedVersion: (characterCardName: string, options: any) => ipcRenderer.invoke('chatVersion:createLinkedVersion', characterCardName, options),
    getVersionIndex: (characterCardName: string) => ipcRenderer.invoke('chatVersion:getVersionIndex', characterCardName),
    getChangeLog: (characterCardName: string, options?: any) => ipcRenderer.invoke('chatVersion:getChangeLog', characterCardName, options),
    verifyConsistency: (characterCardName: string) => ipcRenderer.invoke('chatVersion:verifyConsistency', characterCardName),
    getTableSnapshot: (characterCardName: string, versionLinkId: string) => ipcRenderer.invoke('chatVersion:getTableSnapshot', characterCardName, versionLinkId),
    getTableSnapshots: (characterCardName: string) => ipcRenderer.invoke('chatVersion:getTableSnapshots', characterCardName),
    getSnapshotContent: (filePath: string) => ipcRenderer.invoke('chatVersion:getSnapshotContent', filePath)
  },
  // 通用存储 API
  storage: {
    get: (key: string) => ipcRenderer.invoke('storage:get', key),
    set: (data: { key: string; value: any }) => ipcRenderer.invoke('storage:set', data),
    delete: (key: string) => ipcRenderer.invoke('storage:delete', key),
    clear: () => ipcRenderer.invoke('storage:clear'),
    has: (key: string) => ipcRenderer.invoke('storage:has', key),
    getAll: () => ipcRenderer.invoke('storage:getAll'),
    import: (data: string) => ipcRenderer.invoke('storage:import', data)
  },
  embedding: {
    generate: (text: string) => ipcRenderer.invoke('embedding:generate', { text }),
    generateBatch: (texts: string[]) => ipcRenderer.invoke('embedding:generateBatch', { texts }),
    testConnection: (config?: any) => ipcRenderer.invoke('embedding:testConnection', config),
    listModels: (config?: any) => ipcRenderer.invoke('embedding:listModels', config),
    setMode: (mode: string) => ipcRenderer.invoke('embedding:setMode', { mode }),
    getMode: () => ipcRenderer.invoke('embedding:getMode'),
    localTest: (params?: { modelName?: string }) => ipcRenderer.invoke('embedding:localTest', params || {}),
    localGenerate: (text: string) => ipcRenderer.invoke('embedding:localGenerate', { text }),
    localInit: (modelName?: string) => ipcRenderer.invoke('embedding:localInit', { modelName }),
    checkModelStatus: (modelName: string) => ipcRenderer.invoke('embedding:checkModelStatus', { modelName })
  },
  vector: {
    add: (id: string, vector: number[], metadata: Record<string, any>) =>
      ipcRenderer.invoke('vector:add', { id, vector, metadata }),
    addBatch: (items: Array<{ id: string; vector: number[]; metadata: Record<string, any> }>) =>
      ipcRenderer.invoke('vector:addBatch', { items }),
    search: (query: number[], topK: number, filter?: Record<string, any>, scopeIds?: string[]) =>
      ipcRenderer.invoke('vector:search', { query, topK, filter, scopeIds }),
    getById: (id: string) => ipcRenderer.invoke('vector:getById', { id }),
    update: (id: string, vector: number[], metadata?: Record<string, any>) =>
      ipcRenderer.invoke('vector:update', { id, vector, metadata }),
    delete: (id: string) => ipcRenderer.invoke('vector:delete', { id }),
    count: () => ipcRenderer.invoke('vector:count'),
    rebuildIndex: () => ipcRenderer.invoke('vector:rebuildIndex'),
    testStorage: (scopeIds?: string[]) => ipcRenderer.invoke('vector:testStorage', { scopeIds }),
    getStorePath: () => ipcRenderer.invoke('vector:getStorePath'),
    testEmbedding: () => ipcRenderer.invoke('vector:testEmbedding'),
    testAll: () => ipcRenderer.invoke('vector:testAll'),
    getAvailableScopes: () => ipcRenderer.invoke('vector:getAvailableScopes')
  },
  document: {
    process: (filePath: string) => ipcRenderer.invoke('document:process', { filePath }),
    list: () => ipcRenderer.invoke('document:list'),
    delete: (docId: string) => ipcRenderer.invoke('document:delete', { docId }),
    deleteBatch: (docIds: string[]) => ipcRenderer.invoke('document:deleteBatch', { docIds }),
    getInfo: (docId: string) => ipcRenderer.invoke('document:getInfo', { docId }),
    getChunks: (docId: string) => ipcRenderer.invoke('document:getChunks', { docId }),
    searchVectors: (queryText: string, topK: number, docId?: string) => ipcRenderer.invoke('document:searchVectors', { queryText, topK, docId }),
    getVectorStats: () => ipcRenderer.invoke('document:getVectorStats'),
    generateEmbedding: (text: string) => ipcRenderer.invoke('document:generateEmbedding', { text }),
    selectFile: () => ipcRenderer.invoke('document:selectFile')
  },
  knowledge: {
    list: (filter?: Record<string, any>, page?: number, pageSize?: number) =>
      ipcRenderer.invoke('knowledge:list', { filter, page, pageSize }),
    create: (item: any) => ipcRenderer.invoke('knowledge:create', { item }),
    createBatch: (items: any[]) => ipcRenderer.invoke('knowledge:createBatch', { items }),
    update: (id: string, updates: any) => ipcRenderer.invoke('knowledge:update', { id, updates }),
    delete: (id: string) => ipcRenderer.invoke('knowledge:delete', { id }),
    deleteBatch: (ids: string[]) => ipcRenderer.invoke('knowledge:deleteBatch', { ids }),
    search: (query: string, options?: any) => ipcRenderer.invoke('knowledge:search', { query, options }),
    vectorize: (id: string) => ipcRenderer.invoke('knowledge:vectorize', { id }),
    vectorizeAll: () => ipcRenderer.invoke('knowledge:vectorizeAll'),
    uploadDocument: (filePath: string, options?: { category?: string[]; tags?: string[]; source?: string }) =>
      ipcRenderer.invoke('knowledge:uploadDocument', { filePath, options }),
    selectDocumentFile: () => ipcRenderer.invoke('knowledge:selectDocumentFile')
  },
  context: {
    retrieve: (conversation: any[], options: any) =>
      ipcRenderer.invoke('context:retrieve', { conversation, options }),
    retrieveWithKeywords: (
      conversation: any[], 
      options: any, 
      enableKeywordMatch?: boolean,
      scanDepth?: number,
      globalScanData?: {
        personaDescription?: string;
        characterDescription?: string;
        characterPersonality?: string;
        characterDepthPrompt?: string;
        scenario?: string;
        creatorNotes?: string;
      }
    ) =>
      ipcRenderer.invoke('context:retrieveWithKeywords', { 
        conversation, 
        options, 
        enableKeywordMatch,
        scanDepth,
        globalScanData 
      }),
    compress: (items: any[], maxTokens: number) =>
      ipcRenderer.invoke('context:compress', { items, maxTokens }),
    retrieveWithHybrid: (query: string, options: any) =>
      ipcRenderer.invoke('context:retrieveWithHybrid', { query, options })
  },
  worldbook: {
    matchKeywords: (text: string, worldBookPaths?: string[], options?: any) =>
      ipcRenderer.invoke('worldbook:matchKeywords', { text, worldBookPaths, options })
  },
  model: {
    download: (modelName: string) => ipcRenderer.invoke('model:download', { modelName }),
    isDownloaded: (modelName: string) => ipcRenderer.invoke('model:isDownloaded', { modelName }),
    getCacheDir: () => ipcRenderer.invoke('model:getCacheDir')
  },
  chatVector: {
    vectorize: (characterId: string, messages: any[]) => ipcRenderer.invoke('chatVector:vectorize', characterId, messages),
    delete: (characterId: string) => ipcRenderer.invoke('chatVector:delete', characterId),
    search: (characterId: string, query: string, topK?: number) => ipcRenderer.invoke('chatVector:search', characterId, query, topK)
  },
  // 对话历史 RAG API（Spec: optimize-chat-ai-intelligence / Task 7.4）
  // retrieve - 检索本会话历史消息的向量相似片段（topK=3, minScore=0.6 默认），返回 {content, score, timestamp}[]
  // vectorizeIncremental - 增量向量化最近消息（跳过已向量化的 messageId），fire-and-forget
  chatHistory: {
    retrieve: (chatId: string, queryText: string, topK?: number, minScore?: number) =>
      ipcRenderer.invoke('chatHistory:retrieve', chatId, queryText, topK, minScore),
    vectorizeIncremental: (chatId: string, messages: any[]) =>
      ipcRenderer.invoke('chatHistory:vectorizeIncremental', chatId, messages)
  },
  writing: {
    loadProjects: () => ipcRenderer.invoke('writing:loadProjects'),
    createProject: (config: any) => ipcRenderer.invoke('writing:createProject', config),
    saveProject: (project: any) => ipcRenderer.invoke('writing:saveProject', project),
    deleteProject: (projectId: string) => ipcRenderer.invoke('writing:deleteProject', projectId),
    exportProject: (projectId: string, format: string) => ipcRenderer.invoke('writing:exportProject', projectId, format),
    generateOutline: (request: any) => ipcRenderer.invoke('writing:generateOutline', request),
    saveOutline: (rawContent: string, config: any) => ipcRenderer.invoke('writing:saveOutline', { rawContent, config }),
    generateChapter: (request: any) => ipcRenderer.invoke('writing:generateChapter', request),
    generateChapterChunk: (request: any) => ipcRenderer.invoke('writing:generateChapterChunk', request),
    generateShardOutline: (request: any) => ipcRenderer.invoke('writing:generateShardOutline', request),
    generateShardContent: (request: any) => ipcRenderer.invoke('writing:generateShardContent', request),
    generateChunkSummary: (request: { projectId: string; chapterIndex: number; chunkIndex: number; content: string }) => 
      ipcRenderer.invoke('writing:generateChunkSummary', request),
    saveChunkCheckpoint: (request: { projectId: string; chapterIndex: number; chunkIndex: number; content: string }) => 
      ipcRenderer.invoke('writing:saveChunkCheckpoint', request),
    getChunkCheckpoint: (projectId: string, chapterIndex: number, chunkIndex: number) => 
      ipcRenderer.invoke('writing:getChunkCheckpoint', projectId, chapterIndex, chunkIndex),
    clearChunkCheckpoint: (projectId: string, chapterIndex: number) => 
      ipcRenderer.invoke('writing:clearChunkCheckpoint', projectId, chapterIndex),
    cancelGeneration: (projectId: string) => ipcRenderer.invoke('writing:cancelGeneration', projectId),
    cancelChunkGeneration: (projectId: string, chapterIndex: number, chunkIndex: number) => ipcRenderer.invoke('writing:cancelChunkGeneration', projectId, chapterIndex, chunkIndex),
    loadResources: (params: { worldBookIds: string[]; characterCardIds: string[] }) => ipcRenderer.invoke('writing:loadResources', params),
    autoSaveChapter: (params: { projectId: string; chapterIndex: number; content: string }) => ipcRenderer.invoke('writing:autoSaveChapter', params),
    saveVersion: (params: { projectId: string; chapterIndex: number; content: string; note?: string }) => ipcRenderer.invoke('writing:saveVersion', params),
    restoreVersion: (params: { projectId: string; chapterIndex: number; versionId: string }) => ipcRenderer.invoke('writing:restoreVersion', params),
    exportProjectWithChapters: (projectId: string, format: string, chapterIndices: number[]) => ipcRenderer.invoke('writing:exportProjectWithChapters', projectId, format, chapterIndices),
    checkChapter: (params: { projectId: string; chapterIndex: number; content: string; previousChapters?: { index: number; title: string; content: string }[] }) => ipcRenderer.invoke('writing:checkChapter', params),
    autoFixIssue: (params: { projectId: string; chapterIndex: number; content: string; issue: any; modelConfig?: any }) => ipcRenderer.invoke('writing:autoFixIssue', params),
    batchFixIssues: (req: BatchFixRequest) => ipcRenderer.invoke('writing:batchFixIssues', req),
    getLogicCheckRecords: () => ipcRenderer.invoke('writing:getLogicCheckRecords'),
    clearLogicCheckRecords: () => ipcRenderer.invoke('writing:clearLogicCheckRecords'),
    aiSuggestSplit: (request: any) => ipcRenderer.invoke('writing:aiSuggestSplit', request),
    aiSuggestMerge: (request: any) => ipcRenderer.invoke('writing:aiSuggestMerge', request),
    saveAIGenerationHistory: (params: { projectId: string; history: any }) => ipcRenderer.invoke('writing:saveAIGenerationHistory', params),
    loadAIGenerationHistory: (params: { projectId: string }) => ipcRenderer.invoke('writing:loadAIGenerationHistory', params),
    clearAIGenerationHistory: (params: { projectId: string }) => ipcRenderer.invoke('writing:clearAIGenerationHistory', params),
    polishDescription: (request: {
      description: string;
      instruction?: string;
      resources?: {
        worldBookIds?: string[];
        characterCardIds?: string[];
        userPersonaIds?: string[];
      };
      modelConfig?: {
        model?: string;
        temperature?: number;
        maxTokens?: number;
      };
    }) => ipcRenderer.invoke('writing:polishDescription', request),
    onPolishChunk: (callback: (data: { chunk: string }) => void) => {
      const handler = (_event: any, data: { chunk: string }) => callback(data);
      ipcRenderer.on('writing:polish:chunk', handler);
      return () => ipcRenderer.removeListener('writing:polish:chunk', handler);
    },
    onPolishComplete: (callback: (data: { content: string }) => void) => {
      const handler = (_event: any, data: { content: string }) => callback(data);
      ipcRenderer.on('writing:polish:complete', handler);
      return () => ipcRenderer.removeListener('writing:polish:complete', handler);
    },
    onPolishError: (callback: (data: { error: string }) => void) => {
      const handler = (_event: any, data: { error: string }) => callback(data);
      ipcRenderer.on('writing:polish:error', handler);
      return () => ipcRenderer.removeListener('writing:polish:error', handler);
    },
    onStreamChunk: (callback: (data: any) => void) => {
      const handler = (_event: any, data: any) => callback(data);
      ipcRenderer.on('writing:stream:chunk', handler);
      return () => ipcRenderer.removeListener('writing:stream:chunk', handler);
    },
    onStreamComplete: (callback: (data: any) => void) => {
      const handler = (_event: any, data: any) => callback(data);
      ipcRenderer.on('writing:stream:complete', handler);
      return () => ipcRenderer.removeListener('writing:stream:complete', handler);
    },
    onStreamError: (callback: (data: any) => void) => {
      const handler = (_event: any, data: any) => callback(data);
      ipcRenderer.on('writing:stream:error', handler);
      return () => ipcRenderer.removeListener('writing:stream:error', handler);
    },
    // 分片生成事件监听
    onChunkStart: (callback: (data: any) => void) => {
      const handler = (_event: any, data: any) => callback(data);
      ipcRenderer.on('writing:chunk:start', handler);
      return () => ipcRenderer.removeListener('writing:chunk:start', handler);
    },
    onChunkProgress: (callback: (data: any) => void) => {
      const handler = (_event: any, data: any) => callback(data);
      ipcRenderer.on('writing:chunk:progress', handler);
      return () => ipcRenderer.removeListener('writing:chunk:progress', handler);
    },
    onChunkComplete: (callback: (data: any) => void) => {
      const handler = (_event: any, data: any) => callback(data);
      ipcRenderer.on('writing:chunk:complete', handler);
      return () => ipcRenderer.removeListener('writing:chunk:complete', handler);
    },
    onChunkError: (callback: (data: any) => void) => {
      const handler = (_event: any, data: any) => callback(data);
      ipcRenderer.on('writing:chunk:error', handler);
      return () => ipcRenderer.removeListener('writing:chunk:error', handler);
    },
    style: {
      upload: (request: { filePath: string; fileName: string; fileSize: number }) => ipcRenderer.invoke('writing:style:upload', request),
      list: () => ipcRenderer.invoke('writing:style:list'),
      get: (resourceId: string) => ipcRenderer.invoke('writing:style:get', resourceId),
      delete: (resourceId: string) => ipcRenderer.invoke('writing:style:delete', resourceId),
      cancel: (taskId: string) => ipcRenderer.invoke('writing:style:cancel', taskId),
      getActiveTasks: () => ipcRenderer.invoke('writing:style:getActiveTasks'),
      onProgress: (callback: (data: { taskId: string; progress: any }) => void) => {
        const handler = (_event: any, data: any) => callback(data);
        ipcRenderer.on('writing:style:progress', handler);
        return () => ipcRenderer.removeListener('writing:style:progress', handler);
      },
      onComplete: (callback: (data: { taskId: string; resource: any }) => void) => {
        const handler = (_event: any, data: any) => callback(data);
        ipcRenderer.on('writing:style:complete', handler);
        return () => ipcRenderer.removeListener('writing:style:complete', handler);
      },
      onError: (callback: (data: { taskId: string; error: string }) => void) => {
        const handler = (_event: any, data: any) => callback(data);
        ipcRenderer.on('writing:style:error', handler);
        return () => ipcRenderer.removeListener('writing:style:error', handler);
      }
    },
    table: {
      getTableData: (projectId: string) => ipcRenderer.invoke('writing:table:getTableData', projectId),
      saveTableData: (projectId: string, sheetName: string, sheetData: Record<string, any>[]) => ipcRenderer.invoke('writing:table:saveTableData', projectId, sheetName, sheetData),
      clearTableData: (projectId: string) => ipcRenderer.invoke('writing:table:clearTableData', projectId),
      updateRowInTable: (projectId: string, sheetName: string, rowIndex: number, rowData: Record<string, any>) => ipcRenderer.invoke('writing:table:updateRowInTable', projectId, sheetName, rowIndex, rowData),
      getTableConfig: (projectId: string) => ipcRenderer.invoke('writing:table:getTableConfig', projectId),
      saveTableConfig: (projectId: string, config: any) => ipcRenderer.invoke('writing:table:saveTableConfig', projectId, config),
      associateTableTemplate: (projectId: string, templateId: string, templateName: string, templateSheets: Array<{ name: string; headers: string[]; description?: string }>) => ipcRenderer.invoke('writing:table:associateTableTemplate', projectId, templateId, templateName, templateSheets),
      getAllTemplates: () => ipcRenderer.invoke('writing:table:getAllTemplates'),
      organizeTable: (projectId: string, modelConfig: any, chapterIndex?: number, requirements?: string, skipOrganized?: boolean) => ipcRenderer.invoke('writing:table:organizeTable', projectId, modelConfig, chapterIndex, requirements, skipOrganized),
      organizeSingleSheet: (projectId: string, sheetName: string, modelConfig: any, chapterIndex?: number, requirements?: string) => ipcRenderer.invoke('writing:table:organizeSingleSheet', projectId, sheetName, modelConfig, chapterIndex, requirements),
      reorganizeRow: (projectId: string, sheet: string, rowIndex: number, rowData: Record<string, any>, requirements: string, modelConfig: any) => ipcRenderer.invoke('writing:table:reorganizeRow', projectId, sheet, rowIndex, rowData, requirements, modelConfig),
      getOrganizeProgress: (projectId: string) => ipcRenderer.invoke('writing:table:getOrganizeProgress', projectId),
      getChapterOrganizeStatus: (projectId: string) => ipcRenderer.invoke('writing:table:getChapterOrganizeStatus', projectId),
      getVersionSnapshot: (projectId: string) => ipcRenderer.invoke('writing:table:getVersionSnapshot', projectId),
      confirmVersion: (projectId: string) => ipcRenderer.invoke('writing:table:confirmVersion', projectId),
      rollbackVersion: (projectId: string) => ipcRenderer.invoke('writing:table:rollbackVersion', projectId)
    },
    template: {
      novelType: {
        list: () => ipcRenderer.invoke('writing:template:novelType:list'),
        get: (id: string) => ipcRenderer.invoke('writing:template:novelType:get', id),
        save: (template: any) => ipcRenderer.invoke('writing:template:novelType:save', template),
        delete: (id: string) => ipcRenderer.invoke('writing:template:novelType:delete', id),
      },
      writingStyle: {
        list: () => ipcRenderer.invoke('writing:template:writingStyle:list'),
        get: (id: string) => ipcRenderer.invoke('writing:template:writingStyle:get', id),
        save: (template: any) => ipcRenderer.invoke('writing:template:writingStyle:save', template),
        delete: (id: string) => ipcRenderer.invoke('writing:template:writingStyle:delete', id),
      }
    },
    // ============================================================================
    // 写作智能体编排 API（Task 15.2: 前端"智能体写作"按钮 + 进度流 + 断点续跑）
    // ============================================================================
    // 通道：
    //   - writing-agent:run       启动编排（返回 AgentWritingResult）
    //   - writing-agent:cancel    取消编排
    //   - writing-agent:status    查询状态（running + checkpoint）
    //   - writing-agent:resume    从 checkpoint 恢复
    //   - writing-agent:progress  进度事件流（主进程 → 渲染进程推送）
    agent: {
      run: (request: any) => ipcRenderer.invoke('writing-agent:run', request),
      cancel: () => ipcRenderer.invoke('writing-agent:cancel'),
      status: () => ipcRenderer.invoke('writing-agent:status'),
      resume: (request: any) => ipcRenderer.invoke('writing-agent:resume', request),
      onProgress: (callback: (event: any) => void) => {
        const handler = (_event: any, data: any) => callback(data);
        ipcRenderer.on('writing-agent:progress', handler);
        return () => ipcRenderer.removeListener('writing-agent:progress', handler);
      }
    }
  },
  // ============================================================================
  // 游戏模式 API（Spec: add-game-mode-framework / Task 5）
  // ============================================================================
  // 与 writing 命名空间结构对齐：invoke 方法 + 流式事件监听器
  // 流式事件监听器模式参考 writing.onPolishChunk / onPolishComplete / onPolishError
  //
  // 流式事件通道：
  //   - game:narrative:chunk      流式文本片段
  //   - game:narrative:complete   生成完成
  //   - game:narrative:error       生成错误
  //   - game:table:updated         表格被 tableEdit 更新后推送
  //
  // 每个监听器返回 unsubscribe 函数（与 writing 模式一致）
  game: {
    // ========== 游戏元数据 CRUD ==========
    list: () => ipcRenderer.invoke('game:list'),
    getMeta: (gameId: string) => ipcRenderer.invoke('game:getMeta', gameId),
    createGame: (meta: GameMeta) => ipcRenderer.invoke('game:createGame', meta),
    updateGame: (gameId: string, updates: Partial<GameMeta>) =>
      ipcRenderer.invoke('game:updateGame', gameId, updates),
    deleteGame: (gameId: string) => ipcRenderer.invoke('game:deleteGame', gameId),

    // ========== 存档 CRUD ==========
    createSave: (params: {
      gameId: string;
      gameType: import('../shared/types/game.types').GameType;
      name: string;
      isAuto: boolean;
      tableSchema: import('../shared/types/game.types').GameTableSchema;
      initialState?: Record<string, any>;
    }) => ipcRenderer.invoke('game:createSave', params),
    loadSave: (saveId: string) => ipcRenderer.invoke('game:loadSave', saveId),
    listSaves: (gameId: string) => ipcRenderer.invoke('game:listSaves', gameId),
    deleteSave: (saveId: string) => ipcRenderer.invoke('game:deleteSave', saveId),
    save: (
      saveId: string,
      updates: {
        narrativeLog?: GameSaveData['narrativeLog'];
        stateSnapshot?: Record<string, any>;
        currentTurn?: number | null;
        currentNodeId?: string | null;
        nodeTitle?: string | null;
        turnCount?: number;
      }
    ) => ipcRenderer.invoke('game:save', saveId, updates),

    // ========== 表格数据 CRUD + 版本快照 ==========
    getTableData: (saveId: string) => ipcRenderer.invoke('game:getTableData', saveId),
    saveTableData: (saveId: string, tableData: GameTableData) =>
      ipcRenderer.invoke('game:saveTableData', saveId, tableData),
    applyTableEdits: (saveId: string, commands: GameTableEditCommand[]) =>
      ipcRenderer.invoke('game:applyTableEdits', saveId, commands),
    getVersionSnapshot: (saveId: string) =>
      ipcRenderer.invoke('game:getVersionSnapshot', saveId),
    confirmVersion: (saveId: string) => ipcRenderer.invoke('game:confirmVersion', saveId),
    rollbackVersion: (saveId: string) => ipcRenderer.invoke('game:rollbackVersion', saveId),

    // ========== AI 叙事生成 ==========
    generateNarrative: (request: GameNarrativeRequest) =>
      ipcRenderer.invoke('game:generateNarrative', request),
    cancelGeneration: (saveId: string) =>
      ipcRenderer.invoke('game:cancelGeneration', saveId),

    // ========== 游戏本地配置 ==========
    getConfig: (gameId: string) => ipcRenderer.invoke('game:getConfig', gameId),
    saveConfig: (gameId: string, config: GameLocalConfig) =>
      ipcRenderer.invoke('game:saveConfig', gameId, config),

    // ========== 流式事件监听器 ==========
    /**
     * 监听流式 chunk 事件
     * @param callback 接收 { saveId, chunk, index }
     * @returns unsubscribe 函数
     */
    onNarrativeChunk: (callback: (data: GameNarrativeChunk) => void) => {
      const handler = (_event: any, data: GameNarrativeChunk) => callback(data);
      ipcRenderer.on('game:narrative:chunk', handler);
      return () => ipcRenderer.removeListener('game:narrative:chunk', handler);
    },
    /**
     * 监听生成完成事件
     * @param callback 接收 GameNarrativeComplete
     * @returns unsubscribe 函数
     */
    onNarrativeComplete: (callback: (data: GameNarrativeComplete) => void) => {
      const handler = (_event: any, data: GameNarrativeComplete) => callback(data);
      ipcRenderer.on('game:narrative:complete', handler);
      return () => ipcRenderer.removeListener('game:narrative:complete', handler);
    },
    /**
     * 监听生成错误事件
     * @param callback 接收 { saveId, error, code }
     * @returns unsubscribe 函数
     */
    onNarrativeError: (callback: (data: GameNarrativeError) => void) => {
      const handler = (_event: any, data: GameNarrativeError) => callback(data);
      ipcRenderer.on('game:narrative:error', handler);
      return () => ipcRenderer.removeListener('game:narrative:error', handler);
    },
    /**
     * 监听表格更新事件（在 tableEdit 命令应用成功后推送）
     * @param callback 接收 { saveId, changes }
     * @returns unsubscribe 函数
     */
    onTableUpdated: (callback: (data: GameTableUpdated) => void) => {
      const handler = (_event: any, data: GameTableUpdated) => callback(data);
      ipcRenderer.on('game:table:updated', handler);
      return () => ipcRenderer.removeListener('game:table:updated', handler);
    }
  },
  prompt: {
    getAll: () => ipcRenderer.invoke('prompt:getAll'),
    get: (moduleId: string) => ipcRenderer.invoke('prompt:get', moduleId),
    save: (template: any, modifiedBy: string, changeSummary: string) =>
      ipcRenderer.invoke('prompt:save', template, modifiedBy, changeSummary),
    getHistory: (moduleId: string) => ipcRenderer.invoke('prompt:getHistory', moduleId),
    rollback: (moduleId: string, version: number, modifiedBy: string) =>
      ipcRenderer.invoke('prompt:rollback', moduleId, version, modifiedBy),
    clearHistory: (moduleId: string) => ipcRenderer.invoke('prompt:clearHistory', moduleId),
    build: (moduleId: string, variables: Record<string, string>) =>
      ipcRenderer.invoke('prompt:build', moduleId, variables),
    validate: (template: any) => ipcRenderer.invoke('prompt:validate', template),
    reset: (moduleId: string) => ipcRenderer.invoke('prompt:reset', moduleId),
    optimize: (request: any) => ipcRenderer.invoke('prompt:optimize', request)
  },
  // Token 计数 API（精确 cl100k_base，主进程加载）
  token: {
    count: (text: string): Promise<number> => ipcRenderer.invoke('token:count', text),
    countBatch: (messages: Array<{ id: string; text: string }>): Promise<Array<{ id: string; count: number }>> =>
      ipcRenderer.invoke('token:countBatch', messages)
  },
  // 角色卡表情管理 API（Spec: add-character-expression-system / Task 1）
  // 存储路径：{userData}/data/character-expressions/{sha256(characterCardId).slice(0,16)}/
  // 每个角色卡一个 manifest.json + 多个 {emotionKey}.png
  expression: {
    list: (characterCardId: string) => ipcRenderer.invoke('expression:list', characterCardId),
    saveImage: (args: {
      characterCardId: string;
      emotionKey: string;
      imageBase64: string;
      isCustom: boolean;
      label?: string;
    }) => ipcRenderer.invoke('expression:saveImage', args),
    deleteImage: (args: { characterCardId: string; emotionKey: string }) =>
      ipcRenderer.invoke('expression:deleteImage', args),
    addCustomEmotion: (args: { characterCardId: string; key: string; label: string }) =>
      ipcRenderer.invoke('expression:addCustomEmotion', args),
    removeCustomEmotion: (args: { characterCardId: string; key: string }) =>
      ipcRenderer.invoke('expression:removeCustomEmotion', args),
    getImagePath: (args: { characterCardId: string; emotionKey: string }) =>
      ipcRenderer.invoke('expression:getImagePath', args)
  },
  // ============================================================================
  // 角色特征管理 API（Spec: add-asset-and-trait-management / Task 2）
  // ============================================================================
  // 为每个角色卡持久化「视觉特征清单」（如 white fur, dog girl, black shirt），
  // 在 SD 生成素材时自动携带该特征 tag，保证角色一致性。
  // 存储路径：{userData}/data/character-traits/{sha256(characterCardId).slice(0,16)}/traits.json
  characterTrait: {
    // 读取角色卡视觉特征 tag 数组；文件不存在时返回 []（不抛异常）
    // @deprecated 改用 loadData 获取完整 v2 数据
    list: (characterCardId: string) =>
      ipcRenderer.invoke('character-trait:list', characterCardId),
    // 覆盖保存角色卡视觉特征 tag 数组（可附带外观描述）
    // @deprecated 改用 saveData 保存完整 v2 数据
    save: (args: { characterCardId: string; traits: string[]; appearanceDescription?: string }) =>
      ipcRenderer.invoke('character-trait:save', args),
    // 读取角色卡外观描述（中文自然语言）；不存在时返回空串
    loadDescription: (characterCardId: string) =>
      ipcRenderer.invoke('character-trait:loadDescription', characterCardId),
    // 清除角色卡视觉特征文件（删除 traits.json，幂等）
    clear: (characterCardId: string) =>
      ipcRenderer.invoke('character-trait:clear', characterCardId),
    // 读取角色卡完整 v2 数据（含分类/组合/启用状态）；文件不存在返回空白 v2，v1 数据自动迁移
    // Spec: add-trait-category-grouping / Task 3
    loadData: (characterCardId: string) =>
      ipcRenderer.invoke('character-trait:loadData', characterCardId),
    // 覆盖保存角色卡完整 v2 数据（version 强制为 2，含分类/组合/启用状态）
    // Spec: add-trait-category-grouping / Task 3
    saveData: (args: { characterCardId: string; data: CharacterTraitManifestV2 }) =>
      ipcRenderer.invoke('character-trait:saveData', args)
  },
  // ============================================================================
  // 全局特征分类字典 API（Spec: fix-asset-trait-and-scene-defects / Task 3）
  // ============================================================================
  // 跨角色卡共享的自定义分类字典，持久化到 {userData}/data/trait-categories.json
  // 取代 CharacterTraitManifestV2.customCategories 作为分类的唯一读取源
  // 系统分类（SYSTEM_TRAIT_CATEGORIES）仍由代码常量提供，不写入此字典
  categoryDictionary: {
    // 读取全局分类字典；文件不存在或损坏时返回空白字典（categories=[]）
    load: () => ipcRenderer.invoke('category-dictionary:load'),
    // 新增自定义分类（重名时返回既有分类，不创建副本）
    add: (args: { name: string; icon?: string }) =>
      ipcRenderer.invoke('category-dictionary:add', args),
    // 按 id 删除自定义分类（幂等：id 不存在视为成功）
    delete: (args: { id: string }) => ipcRenderer.invoke('category-dictionary:delete', args),
    // 按 id 重命名自定义分类（newName 为空或重名时返回 success=false）
    rename: (args: { id: string; newName: string }) =>
      ipcRenderer.invoke('category-dictionary:rename', args),
    // 检查全局字典中是否已存在指定名称的分类（大小写不敏感）
    has: (args: { name: string }) => ipcRenderer.invoke('category-dictionary:has', args),
  },
  // ============================================================================
  // 角色卡 LoRA 管理 API（2026-07-29 bug 修复 - 按角色独立存储）
  // ============================================================================
  // 【重点标记】原实现将 LoRA 存在全局 AppSetting.sdWebui.selectedLoras 中，
  // 导致 A 角色 LoRA 污染 B 角色。现改为按角色卡独立持久化。
  // 存储路径：{userData}/data/character-loras/{sha256(characterCardId).slice(0,16)}/loras.json
  characterLora: {
    // 读取角色卡 LoRA 模型清单；文件不存在时返回 []（不抛异常）
    list: (characterCardId: string) =>
      ipcRenderer.invoke('character-lora:list', characterCardId),
    // 覆盖保存角色卡 LoRA 模型清单
    save: (args: { characterCardId: string; loras: Array<{ name: string; weight: number }> }) =>
      ipcRenderer.invoke('character-lora:save', args),
  },
  // ============================================================================
  // 素材管理 API（Spec: add-asset-and-trait-management / Task 7）
  // ============================================================================
  // 通用素材管理，新增三种素材类型：illustration / general / three-view。
  // 表情类型（expression）继续走 expressionService.ts，不纳入本命名空间。
  // 存储路径：{userData}/data/character-assets/{sha256(characterCardId).slice(0,16)}/{assetType}/...
  asset: {
    // 读取角色卡 × assetType 的素材包 manifest；不存在返回默认空 manifest
    list: (args: { characterCardId: string; assetType: string }) =>
      ipcRenderer.invoke('asset:list', args),
    // 保存素材图像（base64，可含 data URI 前缀）并更新 manifest；返回图像绝对路径
    save: (args: {
      characterCardId: string;
      assetType: string;
      assetId: string;
      imageBase64: string;
      slot?: string;
    }) => ipcRenderer.invoke('asset:save', args),
    // 删除指定素材的图像文件并从 manifest 移除条目（幂等）
    delete: (args: { characterCardId: string; assetType: string; assetId: string }) =>
      ipcRenderer.invoke('asset:delete', args),
    // 获取指定素材的图像绝对路径；不存在返回 null。
    // 【重点标记 - CSP 兼容】渲染进程应通过 file.readAsBase64 转 data URL 后再用于 <img src>
    getImagePath: (args: { characterCardId: string; assetType: string; assetId: string }) =>
      ipcRenderer.invoke('asset:getImagePath', args)
  },
  // ============================================================================
  // SD 表情生成 API（Spec: add-ai-expression-generation / Task 2 + integrate-nl-driven-sd-models / Task 5）
  // ============================================================================
  // 调用 sdGenerationService 通过 SD WebUI img2img / txt2img 端点生成角色卡表情图片
  // 支持单次生成与批量生成（含进度推送与取消）
  // 注意：本命名空间合并了 Task 6 的 checkStatus / getModels（改用 { endpoint } 包装），
  //       sdHandlers.ts 不再注册，由 sdGenerationHandlers.ts 统一提供全部 6 个通道
  sd: {
    checkStatus: (endpoint: string) => ipcRenderer.invoke('sd:checkStatus', { endpoint }),
    getModels: (endpoint: string) => ipcRenderer.invoke('sd:getModels', { endpoint }),
    generateExpression: (args: {
      characterCardPath: string;
      emotionKey: string;
      prompt: string;
      negativePrompt: string;
      options?: any;
    }) => ipcRenderer.invoke('sd:generateExpression', args),
    generateTxt2Img: (args: {
      endpoint: string;
      prompt: string;
      negativePrompt?: string;
      options?: any;
    }) => ipcRenderer.invoke('sd:generateTxt2Img', args),
    generateAllExpressions: (args: {
      characterCardPath: string;
      emotions: Array<{ key: string; prompt: string; negativePrompt: string }>;
      options?: any;
    }) => ipcRenderer.invoke('sd:generateAllExpressions', args),
    cancelGeneration: () => ipcRenderer.invoke('sd:cancelGeneration'),
    onGenerationProgress: (callback: (data: any) => void) => {
      ipcRenderer.on('sd:generationProgress', (_event, data) => callback(data));
    },
    onGenerationComplete: (callback: (data: any) => void) => {
      ipcRenderer.on('sd:generationComplete', (_event, data) => callback(data));
    },
    removeProgressListeners: () => {
      ipcRenderer.removeAllListeners('sd:generationProgress');
      ipcRenderer.removeAllListeners('sd:generationComplete');
    }
  },
  // ============================================================================
  // LoRA 模型列表 API（Spec: add-lora-model-selection / Task 3）
  // ============================================================================
  // 通过 SD WebUI API 获取可用 LoRA 模型列表，含预览图 URL 和 JSON 元数据
  // 返回 { success, loras?: LoraModel[], error? }
  lora: {
    list: (endpoint: string) => ipcRenderer.invoke('lora:list', { endpoint }),
  },

  // ============================================================================
  // Agent 智能体底座 API（Spec: implement-agent-foundation-and-fix-defects / Task 9）
  // ============================================================================
  // 9 个 IPC 通道：agent:run / agent:cancel / agent:token / agent:toolCall / agent:done
  //               + skill:list / skill:invoke + memory:search + learning:dream
  //
  // 流式事件订阅：渲染进程通过 onToken / onToolCall / onDone 订阅事件，
  //              返回取消订阅函数（与 on() 模式一致）。
  agent: {
    // 启动 agent 运行（返回 { success, result?, error? }）
    run: (intent: {
      systemPrompt: string;
      messages: Array<{ role: 'user' | 'assistant'; content: string }>;
      context?: { sessionId?: string; characterId?: string; mode?: 'dialogue' | 'writing' | 'game' };
      maxIterations?: number;
      timeoutMs?: number;
    }) => ipcRenderer.invoke('agent:run', intent),

    // 取消当前 agent 运行（返回 { success, error? }）
    cancel: () => ipcRenderer.invoke('agent:cancel'),

    // 订阅 token 流式事件（返回取消订阅函数）
    onToken: (callback: (data: { chunk: string; timestamp: number }) => void) => {
      const subscription = (_event: unknown, data: { chunk: string; timestamp: number }) => callback(data);
      ipcRenderer.on('agent:token', subscription);
      return () => ipcRenderer.removeListener('agent:token', subscription);
    },

    // 订阅工具调用事件（返回取消订阅函数）
    onToolCall: (callback: (data: {
      name: string;
      args: Record<string, unknown>;
      phase: 'start' | 'end';
      result?: unknown;
      durationMs?: number;
      timestamp: number;
    }) => void) => {
      const subscription = (_event: unknown, data: any) => callback(data);
      ipcRenderer.on('agent:toolCall', subscription);
      return () => ipcRenderer.removeListener('agent:toolCall', subscription);
    },

    // 订阅 agent 完成事件（返回取消订阅函数）
    onDone: (callback: (data: {
      finishReason: string;
      iterations: number;
      error?: string;
      timestamp: number;
    }) => void) => {
      const subscription = (_event: unknown, data: any) => callback(data);
      ipcRenderer.on('agent:done', subscription);
      return () => ipcRenderer.removeListener('agent:done', subscription);
    },

    // Agent 模式管理 API（Spec: add-agent-mode-management-and-center）
    // 3 个 IPC 通道 + 1 个事件广播：
    //   - agent:isModeActive    查询 Agent 模式是否激活
    //   - agent:getModeStatus   获取完整模式状态
    //   - agent:setModeOverride 设置覆盖开关（auto / force-on / force-off）
    //   - agent:modeChanged     模式变更事件广播（主进程 → 渲染进程）
    mode: {
      getStatus: () => ipcRenderer.invoke('agent:getModeStatus'),
      isModeActive: () => ipcRenderer.invoke('agent:isModeActive'),
      setOverride: (override: 'auto' | 'force-on' | 'force-off') =>
        ipcRenderer.invoke('agent:setModeOverride', { override }),
      onModeChanged: (callback: (status: any) => void) => {
        const subscription = (_event: unknown, status: any) => callback(status);
        ipcRenderer.on('agent:modeChanged', subscription);
        return () => ipcRenderer.removeListener('agent:modeChanged', subscription);
      },
    },

    // Agent 配置管理 API（Spec: add-agent-mode-management-and-center / Task 5.2）
    // 8 个 IPC 通道：
    //   - agent-config:list          列出全部智能体配置
    //   - agent-config:get           获取单个智能体配置
    //   - agent-config:update        更新智能体配置（Partial<AgentConfig>）
    //   - agent-config:toggle        切换智能体启用/禁用状态
    //   - agent-config:updateSkills  更新技能白名单
    //   - agent-config:create        创建用户自定义智能体
    //   - agent-config:delete        删除用户自定义智能体（系统预置不可删除）
    //   - agent-config:changed       配置变更事件广播（主进程 → 渲染进程）
    config: {
      list: () => ipcRenderer.invoke('agent-config:list'),
      get: (id: string) => ipcRenderer.invoke('agent-config:get', { id }),
      update: (id: string, patch: any) => ipcRenderer.invoke('agent-config:update', { id, patch }),
      toggle: (id: string) => ipcRenderer.invoke('agent-config:toggle', { id }),
      updateSkills: (id: string, skills: string[]) => ipcRenderer.invoke('agent-config:updateSkills', { id, skills }),
      create: (config: any) => ipcRenderer.invoke('agent-config:create', { config }),
      delete: (id: string) => ipcRenderer.invoke('agent-config:delete', { id }),
      onConfigChanged: (callback: (data: any) => void) => {
        const listener = (_event: any, data: any) => callback(data);
        ipcRenderer.on('agent-config:changed', listener);
        return () => ipcRenderer.removeListener('agent-config:changed', listener);
      },
    },
  },

  // 技能系统 API（阶段 3 完整接入，当前为占位）
  skill: {
    list: () => ipcRenderer.invoke('skill:list'),
    invoke: (args: { skillName: string; args: Record<string, unknown>; context?: any }) =>
      ipcRenderer.invoke('skill:invoke', args),
    importFromDir: (dirPath: string) => ipcRenderer.invoke('skill:importFromDir', dirPath),
    importFromUrl: (url: string) => ipcRenderer.invoke('skill:importFromUrl', url),
    uninstall: (skillName: string) => ipcRenderer.invoke('skill:uninstall', skillName),
    getDetail: (skillName: string) => ipcRenderer.invoke('skill:getDetail', skillName),
    create: (params: { name: string; description: string; emoji?: string; body: string }) =>
      ipcRenderer.invoke('skill:create', params),
    edit: (params: { name: string; description: string; emoji?: string; body: string }) =>
      ipcRenderer.invoke('skill:edit', params),
    getPromptSnippet: () => ipcRenderer.invoke('skill:getPromptSnippet'),
  },

  // Agent 记忆检索 API
  agentMemory: {
    search: (query: {
      query: string;
      types?: string[];
      limit?: number;
      characterId?: string;
      sessionId?: string;
    }) => ipcRenderer.invoke('memory:search', query),
  },

  // ============================================================================
  // Agent 学习系统 API（Spec: implement-agent-foundation-and-fix-defects / Task 18）
  // ============================================================================
  // 11 个 IPC 通道（Task 18 完整接入）：
  //   - learning:dream                  手动触发 dreaming（短期→长期记忆摘要）
  //   - learning:cancelDream            取消正在进行的 dreaming
  //   - learning:getDreamingStatus      查询 dreaming 运行状态
  //   - learning:createGoal             创建会话目标
  //   - learning:getGoal                获取当前会话目标
  //   - learning:updateGoal             更新目标状态（complete | blocked）
  //   - learning:clearGoal              清除会话目标
  //   - learning:steer                  写入引导消息（注入下一轮 LLM 请求前）
  //   - learning:listSteer              列出 pending 引导消息
  //   - learning:recordFeedback         记录用户反馈（thumb_down/low_rating/...）
  //   - learning:runReflection          触发反馈反思（LLM 生成经验记忆）
  learning: {
    // 手动触发 dreaming（返回 { success, result?, error? }）
    dream: (args: { sessionId?: string }) => ipcRenderer.invoke('learning:dream', args),

    // 取消正在进行的 dreaming
    cancelDream: () => ipcRenderer.invoke('learning:cancelDream'),

    // 查询 dreaming 运行状态
    getDreamingStatus: () => ipcRenderer.invoke('learning:getDreamingStatus'),

    // 创建会话目标（仅用户/system 显式请求可创建）
    createGoal: (args: {
      sessionId: string;
      characterId?: string;
      objective: string;
      tokenBudget?: number;
    }) => ipcRenderer.invoke('learning:createGoal', args),

    // 获取当前会话目标（无未完成目标时返回 null）
    getGoal: (sessionId: string) => ipcRenderer.invoke('learning:getGoal', sessionId),

    // 更新目标状态（complete | blocked）
    updateGoal: (args: {
      sessionId: string;
      status: 'complete' | 'blocked';
      note?: string;
      blocker?: string;
      tokensDelta?: number;
      actor?: 'user' | 'agent' | 'system';
    }) => ipcRenderer.invoke('learning:updateGoal', args),

    // 清除会话目标（用户主动清除，标记为 complete 而非物理删除）
    clearGoal: (sessionId: string) => ipcRenderer.invoke('learning:clearGoal', sessionId),

    // 写入引导消息（source: user/system/agent）
    steer: (args: {
      sessionId: string;
      content: string;
      source: 'user' | 'system' | 'agent';
      label?: string;
    }) => ipcRenderer.invoke('learning:steer', args),

    // 列出 pending 引导消息
    listSteer: (sessionId: string) => ipcRenderer.invoke('learning:listSteer', sessionId),

    // 记录用户反馈（不触发反思）
    recordFeedback: (args: {
      sessionId: string;
      characterId?: string;
      agentResponse?: string;
      userComment?: string;
      kind: 'thumb_down' | 'low_rating' | 'comment' | 'correction';
      rating?: number;
    }) => ipcRenderer.invoke('learning:recordFeedback', args),

    // 触发反馈反思（LLM 反思 → 写回经验记忆）
    runReflection: (args: {
      sessionId: string;
      agentResponse?: string;
      userComment?: string;
    }) => ipcRenderer.invoke('learning:runReflection', args),
  },

  // ============================================================================
  // 会话管理 API（Spec: optimize-agent-interaction-from-openclaw / Task 6）
  // ============================================================================
  // 7 个 IPC 通道：
  //   - session:create       创建新会话
  //   - session:list         列出当前角色所有会话
  //   - session:switch       切换会话（更新 lastActiveAt）
  //   - session:delete       删除会话（同时删除消息历史文件）
  //   - session:rename       重命名会话标题
  //   - session:saveMessages 保存会话消息历史
  //   - session:loadMessages 加载会话消息历史
  session: {
    // 创建新会话（默认标题"新对话"）
    create: (args: { characterCardId: string; title?: string }) =>
      ipcRenderer.invoke('session:create', args),

    // 列出当前角色所有会话（按最后活跃时间降序）
    list: (characterCardId: string) =>
      ipcRenderer.invoke('session:list', { characterCardId }),

    // 切换会话（更新 lastActiveAt）
    switch: (args: { characterCardId: string; sessionId: string }) =>
      ipcRenderer.invoke('session:switch', args),

    // 删除会话（同时删除消息历史文件）
    delete: (args: { characterCardId: string; sessionId: string }) =>
      ipcRenderer.invoke('session:delete', args),

    // 重命名会话标题
    rename: (args: { characterCardId: string; sessionId: string; newTitle: string }) =>
      ipcRenderer.invoke('session:rename', args),

    // 保存会话消息历史
    saveMessages: (args: {
      characterCardId: string;
      sessionId: string;
      messages: Array<{ role: string; content: string; timestamp?: number; [key: string]: unknown }>;
    }) => ipcRenderer.invoke('session:saveMessages', args),

    // 加载会话消息历史（文件不存在时返回空数组）
    loadMessages: (characterCardId: string, sessionId: string) =>
      ipcRenderer.invoke('session:loadMessages', { characterCardId, sessionId }),
  }
});
