/**
 * 技能库系统核心类型定义
 *
 * Agent 技能库（对标 OpenClaw skill 管理体系）的类型基础。
 * 技能是结构化的可复用能力单元，高于工具（AgentTool）一层：
 * 工具是单函数调用，技能可组合多工具 + 提示词模板 + 执行逻辑。
 */

import type { AgentToolContext } from '../agentTypes'

/** 技能分类（与工具组对齐 + general） */
export type SkillCategory = 'dialogue' | 'writing' | 'worldbook' | 'general'

/** 技能实现类型 */
export type SkillType = 'prompt' | 'tool-sequence' | 'composite'

/** 技能来源 */
export type SkillSource = 'system' | 'user' | 'agent'

/** 技能清单（标准化定义） */
export interface SkillManifest {
  /** 唯一标识，kebab-case */
  id: string
  /** 显示名 */
  name: string
  /** 做什么 + 何时用（供 Agent 决策调用） */
  description: string
  category: SkillCategory
  /** semver，如 "1.0.0" */
  version: string
  author: SkillSource
  tags: string[]
  enabled: boolean

  /** 输入 schema（JSONSchema） */
  inputSchema: Record<string, any>
  /** 输出 schema（可选） */
  outputSchema?: Record<string, any>

  /** 实现类型与具体实现 */
  type: SkillType
  implementation: SkillImplementation

  /** 依赖的工具名（AgentTool name） */
  requiredTools?: string[]
  /** 依赖的其他技能 id */
  requiredSkills?: string[]

  /** 少样本示例（供 Agent 理解调用方式） */
  examples?: SkillExample[]

  /** 元数据 */
  createdAt: string
  updatedAt: string
  /** Agent 自动生成标记 */
  autoGenerated?: boolean
}

/** 技能实现 */
export interface SkillImplementation {
  /** prompt 类型：系统提示词模板（支持 {{var}} 插值） */
  prompt?: {
    systemPrompt: string
    userPromptTemplate?: string
  }
  /** tool-sequence 类型：有序步骤 */
  steps?: SkillStep[]
  /** composite 类型：代码 handler 引用名（在 skillExecutor 注册） */
  handlerRef?: string
}

/** 技能步骤（tool-sequence 类型） */
export interface SkillStep {
  /** AgentTool name */
  toolName: string
  /** 模板，可引用上一步结果 {{step.resultKey}} 或输入 {{input.xxx}} */
  argsTemplate: string
  /** 存储结果供后续步骤引用的 key */
  resultKey: string
  /** 失败是否继续（默认 false） */
  optional?: boolean
}

/** 技能示例（少样本） */
export interface SkillExample {
  input: Record<string, any>
  output: Record<string, any>
  description?: string
}

/** 技能调用结果 */
export interface SkillResult {
  success: boolean
  data?: any
  error?: string
  /** 执行轨迹（每步结果） */
  trace?: Array<{ step: string; result: any; durationMs: number }>
}

/** 技能版本历史条目 */
export interface SkillVersionEntry {
  version: string
  manifest: SkillManifest
  createdAt: string
  changeLog?: string
}

/** 技能摘要（供 Agent 发现与决策） */
export interface SkillSummary {
  id: string
  name: string
  description: string
  category: SkillCategory
  version: string
  type: SkillType
}

/** 技能调用入参 */
export interface SkillInvocation {
  id: string
  input: Record<string, any>
  context?: AgentToolContext
}
