import {
  WritingStyleResource,
  WritingStyleLearningRequest,
  WritingStyleProgress,
  CustomNovelTypeTemplate,
  CustomWritingStyleTemplate
} from '../../shared/types/writing.types';
import type {
  WritingAgentRequest,
  WritingAgentResult,
  WritingAgentStatus,
  WritingAgentEvent
} from '../../shared/types/writing-agent.types';
import type {
  PromptPolishRequest,
  PromptPolishResult
} from '../../shared/types/promptTemplate.types';
import type {
  GameIndexEntry,
  GameMeta,
  GameSaveMeta,
  GameSaveData,
  GameNarrativeMessage,
  GameTableData,
  GameTableSchema,
  GameTableEditCommand,
  GameNarrativeRequest,
  GameNarrativeChunk,
  GameNarrativeComplete,
  GameNarrativeError,
  GameTableUpdated,
  GameLocalConfig,
  GameType
} from '../../shared/types/game.types';
import type { AIEngineCapabilities } from './setting';
import type { AgentModeStatus, AgentModeOverride, AgentConfig } from '../../shared/types/agent-center.types';
import type { CharacterTraitManifestV2, CategorizedTrait, GlobalTraitCategoryDictionary, TraitCategory } from '../../shared/types/characterTrait.types';

declare global {
  interface Window {
    electronAPI: ElectronAPI;
  }
}

interface ElectronAPI {
  // 通用 invoke 方法，用于直接调用 IPC handler
  invoke: (channel: string, ...args: any[]) => Promise<any>;

  // 通用方法，用于监听 IPC 事件
  on: (channel: string, callback: (...args: any[]) => void) => void;

  off: (channel: string, callback: (...args: any[]) => void) => void;
  setting: {
    load: () => Promise<{ success: boolean; setting?: any; error?: string }>;
    save: (setting: any) => Promise<{ success: boolean; error?: string }>;
    getPath: () => Promise<{ success: boolean; path?: string; error?: string }>;
  };
  worldBook: {
    list: () => Promise<any[]>;
    read: (path: string) => Promise<any>;
    write: (path: string, data: any) => Promise<any>;
    delete: (path: string) => Promise<any>;
    import: (sourcePath: string, fileName: string) => Promise<{ success: boolean; targetPath?: string; error?: string }>;
    optimize: (path: string) => Promise<any>;
    getDirectory: () => Promise<string>;
    readTags: (path: string) => Promise<any>;
    writeTags: (path: string, data: any) => Promise<any>;
    deleteTags: (path: string) => Promise<any>;
    saveToKnowledgeBase: (data: any, fileName: string) => Promise<{ success: boolean; filePath?: string; message?: string; fileExists?: boolean; error?: string }>;
    checkFileExists: (fileName: string) => Promise<{ success: boolean; exists: boolean; filePath?: string; error?: string }>;
    vectorize: (path: string) => Promise<{
      success: boolean;
      descriptionVectorized: boolean;
      entriesVectorized: number;
      entriesFailed: number;
      error?: string;
      descriptionVectorId?: string;
      entryVectorIds: string[];
    }>;
    // Task 17.2: autoGenerated 草稿条目审阅流（世界书自驱）
    listAutoGenerated: (path: string) => Promise<{
      success: boolean;
      entries: Array<{
        uid: number | string;
        id?: number;
        name?: string;
        comment?: string;
        content?: string;
        key?: string[];
        secondaryKeys?: string[];
        keysecondary?: string[];
        tags?: string[];
        autoGenerated: boolean;
        provenance?: { source: string; runId?: string; toolName: string; timestamp: number };
        [key: string]: unknown;
      }>;
      error?: string;
    }>;
    approveAutoGenerated: (
      path: string,
      entryUid: string | number
    ) => Promise<{ success: boolean; error?: string }>;
    rejectAutoGenerated: (
      path: string,
      entryUid: string | number
    ) => Promise<{ success: boolean; error?: string }>;
    approveAllAutoGenerated: (
      path: string
    ) => Promise<{ success: boolean; approvedCount: number; error?: string }>;
  };
  // 世界书编写智能体 API（Spec: implement-worldbook-authoring-agent / Task 5.1）
  // 5 个 invoke 通道 + 2 个事件流监听器
  worldBookAgent: {
    /** 启动编写会话（入参 {userPrompt, worldBookPath, allowedWorldBookPaths, config?}） */
    run: (params: any) => Promise<any>;
    /** 取消指定会话 */
    cancel: (sessionId: string) => Promise<any>;
    /** 查询会话状态（无 sessionId 时返回所有活跃会话） */
    status: (sessionId?: string) => Promise<any>;
    /** 从断点恢复会话 */
    resume: (sessionId: string) => Promise<any>;
    /** 回答 PLANNING 阶段的澄清问题 */
    answer: (sessionId: string, answers: any) => Promise<any>;
    /** 订阅进度事件，返回取消订阅函数 */
    onProgress: (callback: (data: any) => void) => () => void;
    /** 订阅澄清问题事件（预留），返回取消订阅函数 */
    onClarify: (callback: (data: any) => void) => () => void;
  };
  character: {
    list: () => Promise<any[]>;
    read: (path: string) => Promise<any>;
    write: (path: string, data: any) => Promise<any>;
    createFromImage: (filePath: string, imageDataBase64: string, characterData: any) => Promise<{ success: boolean; error?: string }>;
    delete: (path: string) => Promise<any>;
    optimize: (path: string) => Promise<any>;
    getDirectory: () => Promise<string>;
    import: (sourcePath: string, fileName: string) => Promise<{ success: boolean; targetPath?: string; error?: string }>;
    testRead: (path: string) => Promise<any>;
    getWorldBookRelations: (path: string) => Promise<Array<{ worldBookPath: string; enabled: boolean; priority: number; filterTags?: string[] }>>;
    setWorldBookRelations: (path: string, relations: Array<{ worldBookPath: string; enabled: boolean; priority: number; filterTags?: string[] }>) => Promise<{ success: boolean; error?: string }>;
  };
  characterConfig: {
    save: (characterCardId: string, config: any) => Promise<{ success: boolean; error?: string }>;
    load: (characterCardId: string) => Promise<{ success: boolean; config: any | null }>;
  };
  avatar: {
    list: () => Promise<any[]>;
    read: (path: string) => Promise<any>;
    write: (path: string, data: any) => Promise<any>;
    delete: (path: string) => Promise<any>;
    getDirectory: () => Promise<string>;
  };
  plugin: {
    getAvailable: (forceRefresh?: boolean) => Promise<any[]>;
    getInstalled: () => Promise<any[]>;
    toggle: (pluginId: string, enabled: boolean) => Promise<{ success: boolean; error?: string }>;
    uninstall: (pluginId: string) => Promise<{ success: boolean; error?: string }>;
    getDirectory: () => Promise<string>;
    checkUpdates: () => Promise<{ success: boolean; plugins?: any[]; error?: string }>;
    updateDescriptions: (translatedPlugins: any[]) => Promise<{ success: boolean; error?: string }>;
    install: (url: string, branch?: string) => Promise<{
      success: boolean;
      plugin?: any;
      error?: string;
      displayName?: string;
      version?: string;
      author?: string;
    }>;
    uninstallById: (pluginId: string) => Promise<{ success: boolean; error?: string }>;
  };
  file: {
    selectDirectory: () => Promise<string | null>;
    selectFile: (filters: any[]) => Promise<string | null>;
    exists: (path: string) => Promise<boolean>;
    read: (path: string) => Promise<string>;
    write: (path: string, content: string) => Promise<{ success: boolean; error?: string }>;
    writeBinary: (path: string, content: string, isBase64?: boolean) => Promise<{ success: boolean; error?: string }>;
    copyFile: (sourcePath: string, targetPath: string) => Promise<{ success: boolean; error?: string }>;
    openFolder: (path: string) => Promise<{ success: boolean; error?: string }>;
    openFile: (path: string) => Promise<{ success: boolean; error?: string }>;
    validatePath: (path: string) => Promise<{ valid: boolean; exists: boolean; isDirectory: boolean; canRead: boolean; canWrite: boolean; error?: string }>;
    readJson: (fileName: string) => Promise<any>;
    readAsBase64: (path: string) => Promise<{ success: boolean; data?: string; error?: string }>;
  };
  // 文档读取 API：读取项目根目录 docs/ 下的文档文件内容
  // 主进程 docsHandlers.ts 暴露 docs:read 通道，成功返回文件内容字符串，失败返回 { success: false, error }
  docs: {
    read: (fileName: string) => Promise<string | { success: false; error: string }>;
  };
  app: {
    getVersion: () => Promise<string>;
    getPlatform: () => Promise<string>;
    openPath: (path: string) => Promise<string>;
    getRootPath: () => Promise<string>;
    getUserDataPath: () => Promise<string>;
    getUserDataSize: () => Promise<{ success: boolean; size?: number; formattedSize?: string; error?: string }>;
  };
  update: {
    check: () => Promise<{ success: boolean; message?: string; data?: { hasUpdate: boolean; currentVersion: string; latestVersion: string; commits: Array<{ hash: string; message: string; author: string; date: string }> } }>;
    pull: () => Promise<{ success: boolean; message?: string; data?: { compiled: boolean; buildOutput: string[]; changedFiles: string[] }; logs?: string[] }>;
  };
  memory: {
    // 表格模板管理
    getAllTemplates: () => Promise<any[]>;
    getTemplate: (templateId: string) => Promise<any | null>;
    createTemplate: (template: any) => Promise<any>;
    updateTemplate: (templateId: string, updates: any) => Promise<any | null>;
    deleteTemplate: (templateId: string) => Promise<boolean>;
    createTableFile: (chatId: string, templateId: string) => Promise<string>;
    readTableFile: (chatId: string) => Promise<Record<string, any[]>>;
    updateTableFile: (chatId: string, sheetName: string, data: any[]) => Promise<string>;
    getVersionHistory: (templateId: string) => Promise<string[]>;
    restoreVersion: (templateId: string, version: string) => Promise<any | null>;
    getTemplateBindingStatus: () => Promise<Record<string, boolean>>;

    // 聊天记录管理
    getChatSessions: () => Promise<any[]>;
    getChatSession: (chatId: string) => Promise<any | null>;
    getChatMessages: (chatId: string, page: number, pageSize: number) => Promise<{ messages: any[]; total: number; totalPages: number }>;
    searchChatMessages: (keyword: string, chatId?: string) => Promise<any[]>;
    filterChatMessages: (chatId: string, filters: any) => Promise<any[]>;
    processChatWithAI: (chatId: string, templateId: string, config: { apiKey: string; apiUrl: string; modelName: string }) => Promise<any[]>;
    applyAIResults: (chatId: string, results: any[]) => Promise<string>;
    deleteChatSession: (chatId: string) => Promise<boolean>;
    associateTemplate: (chatId: string, templateId: string) => Promise<void>;
    getAssociatedTemplate: (chatId: string) => Promise<string | null>;
    processChat: (chatId: string, templateId: string, selectedMessageIds?: string[], config?: { apiKey: string; apiUrl: string; modelName: string; apiMode: string }) => Promise<void>;
    processChatProgressive: (chatId: string, templateId: string, config?: { apiKey: string; apiUrl: string; modelName: string; apiMode: string }, options?: { continueFromLast?: boolean; minInterval?: number }) => Promise<{ success: boolean; processedCount: number; errorCount: number; errors: string[]; resumed: boolean }>;
    getOrganizingProgress: (chatId: string) => Promise<{ processedCount: number; totalMessages: number; lastProcessedAt?: string } | null>;
    clearOrganizingProgress: (chatId: string) => Promise<boolean>;
    clearTableData: (chatId: string) => Promise<{ success: boolean }>;
    copyTemplate: (sourceTemplateId: string, newTemplateName: string) => Promise<any>;

    // 表格数据管理
    getTableData: (chatId: string) => Promise<any>;
    saveTableData: (chatId: string, sheetName: string, sheetData: any[]) => Promise<void>;

    // 自动初始化（首次对话时自动绑定模板并创建空表格）
    autoInitializeSession: (chatId: string) => Promise<{ success: boolean; templateId: string | null }>;

    // 角色卡聊天记录向量化（读取聊天记录并重新向量化）
    vectorizeCharacterChat: (fileName: string) => Promise<{ success: boolean; messagesVectorized?: number; messagesFailed?: number; error?: string; messageVectorIds?: string[] }>;
  };
  // AI 请求 API
  ai: {
    request: (config: {
      url: string;
      method: string;
      headers: Record<string, string>;
      body: any;
      timeout?: number;
      streaming?: boolean
    }) => Promise<{
      success: boolean;
      data?: any;
      error?: string;
      details?: string
    }>;
    /** 取消当前活跃的 AI 请求（中止后端 AbortController） */
    cancel: () => Promise<{ success: boolean; error?: string }>;
    listModels: (params: { apiUrl?: string; apiKey?: string; apiKeyTransmission?: string }) => Promise<{ success: boolean; models: string[]; error?: string }>;
    /**
     * AI 辅助角色特征生成（Spec: add-asset-and-trait-management / Task 12）
     *
     * 基于角色卡 description/personality/scenario 调用 LLM 提取视觉特征 tag 列表。
     * 主进程内部复用 aiConfigProvider 读取激活 AI 引擎配置，
     * 非流式调用 /v1/chat/completions，解析逗号分隔 tag 返回。
     *
     * 错误兜底（SubTask 12.4）：
     * - AI 引擎未配置 / 调用失败 / 返回格式异常 → success=false，error 为友好信息（非堆栈）
     * - traits 可能为空数组（LLM 未从描述中提取到任何视觉特征）
     */
    generateCharacterTraits: (args: {
      characterCardId: string;
      description: string;
      personality?: string;
      scenario?: string;
      includeImage?: boolean;
    }) => Promise<{
      success: boolean;
      /** 【重点标记 - AI 自动归类增强】traits 由 string[] 升级为 CategorizedTrait[]，携带系统分类信息 */
      traits?: CategorizedTrait[];
      appearanceDescription?: string;
      error?: string;
      /**
       * RAG 标签库质检报告（含检索参考 + 生成标签验证结果）。
       * - enabled=false：RAG 未启用
       * - status≠ready：索引未就绪
       * - status=ready：含 retrievedTags（检索参考）+ tagValidation（标签验证）
       */
      ragDebug?: {
        enabled: boolean;
        status: string;
        retrievedTags: Array<{ name: string; category: number; count: number; score: number }>;
        tagValidation: Array<{
          tag: string;
          isValid: boolean;
          canonicalName?: string;
          category?: number;
          count?: number;
          /** invalid tag 跳过原因：'rating'=评级词不纠错；'no_suggestion'=无相似标签 */
          skipReason?: 'rating' | 'no_suggestion';
          /** invalid tag 的语义相似替换建议（top-3，按 score 降序） */
          suggestions: Array<{ name: string; category: number; count: number; score: number }>;
          /** 自动替换后对应的库内标签名（前端据此展示替换关系 + 撤销） */
          replacedBy?: string;
        }>;
      };
    }>;
    /**
     * AI 图片识别特征提取（Spec: add-model-capability-detection-and-image-recognition / Task 6）
     *
     * 通过多模态模型识别角色卡 PNG 图片，提取视觉特征 tag 列表。
     * 主进程内部读取角色卡图片为 base64 data URI，构建多模态 messages
     * （text + image_url），非流式调用 /v1/chat/completions，解析逗号分隔 tag 返回。
     *
     * 前置条件：当前 AI 引擎 supportsVision=true（由前端判断，主进程不重复检测）
     *
     * 错误兜底：
     * - AI 引擎未配置 / 角色卡图片读取失败 / 调用失败 / 返回格式异常 → success=false
     * - traits 可能为空数组（模型未从图片中提取到任何视觉特征）
     */
    recognizeImageTraits: (args: { characterCardPath: string; characterName?: string }) =>
      Promise<{
        success: boolean;
        /** 【重点标记 - AI 自动归类增强】traits 由 string[] 升级为 CategorizedTrait[]，携带系统分类信息 */
        traits?: CategorizedTrait[];
        appearanceDescription?: string;
        error?: string;
      }>;
    /**
     * 提示词生成（Spec: add-prompt-generation-in-asset-modal）
     *
     * 将用户在 AI 素材生成弹窗「提示词生成」面板输入的自由文本提示词
     * （如 "red hair, blue dress, forest background"），通过 LLM 解析为分类特征 tag 列表
     * （含 categoryId / translation / originalText），可直接追加到 editedTraits。
     *
     * 与 generateCharacterTraits 的区别：
     *   - 不读取角色卡图片（无需 characterCardId）
     *   - 输入是用户自由文本提示词，不是角色卡 description/personality/scenario
     *   - 不返回 appearanceDescription（用户只需要 tag）
     *
     * 审计流程与 generateCharacterTraits 完全一致（L0-L5 完整审计链）：
     *   - L0 自定义同义词映射 / L1 name / L2 alias 精确匹配
     *   - L3 颜色拆分 / L3b 否定性修饰词剥离
     *   - L4 语义 KNN 替换 / L5 AI 兜底
     *
     * 入参：
     *   - prompt：用户输入的提示词（必填非空，空/纯空白触发兜底错误）
     *   - baseTraits：当前已有特征文本（可选，逗号分隔，作为上下文避免重复生成）
     *
     * 返回：
     *   - success=true：traits 为分类特征数组（含 translation + originalText）
     *     ragDebug 为 RAG 标签库质检报告（结构与 generateCharacterTraits.ragDebug 兼容）
     *   - success=false：error 为友好错误信息（非堆栈）
     *
     * 错误场景：
     *   - 空输入：prompt 为空或纯空白 → 「请输入提示词」（不调用 LLM）
     *   - AI 引擎未配置：baseUrl / apiKey / modelName 任一缺失
     *   - 引擎参数缺失：temperature / max_tokens 未配置
     *   - 调用失败：网络 / 超时 / HTTP 错误
     *   - 解析失败：LLM 返回空内容 / 无法解析为分类 tag
     */
    generateTraitPrompts: (args: {
      /** 用户输入的提示词（如 "red hair, blue dress, forest background"），必填非空 */
      prompt: string;
      /** 当前已有特征文本（逗号分隔，作为上下文避免重复生成） */
      baseTraits?: string;
    }) => Promise<{
      success: boolean;
      /** 生成的分类特征数组（含 translation + originalText，可直接追加到 editedTraits） */
      traits?: CategorizedTrait[];
      /** 友好错误信息（success=false 时存在，非堆栈） */
      error?: string;
      /**
       * RAG 标签库质检报告（结构与 generateCharacterTraits.ragDebug 完全兼容，
       * 前端可复用 RagQualityReport 组件渲染）。
       */
      ragDebug?: {
        enabled: boolean;
        status: string;
        retrievedTags: Array<{ name: string; category: number; count: number; score: number }>;
        tagValidation: Array<{
          tag: string;
          isValid: boolean;
          canonicalName?: string;
          category?: number;
          count?: number;
          skipReason?: 'rating' | 'no_suggestion';
          suggestions: Array<{ name: string; category: number; count: number; score: number }>;
          replacedBy?: string;
          splitTags?: { colorPartTag: string; featureTag: string };
          source?:
            | 'user-map'
            | 'name'
            | 'alias'
            | 'color-split'
            | 'negation-strip'
            | 'knn'
            | 'ai-fallback';
          manuallyReplaced?: boolean;
          manualReplacement?: string;
          aiFallbackAttempted?: boolean;
          aiFallbackCandidates?: string[];
        }>;
      };
    }>;
    /**
     * 探测 AI 模型能力（Spec: add-model-capability-detection-and-image-recognition / Task 3）
     *
     * 并行探测 vision / thinking / tool-calling 等能力，供前端在连通性测试后展示徽章。
     * 主进程内部调用 aiService.probeAllCapabilities，探测失败时 success=false。
     */
    probeCapabilities: (args: { apiUrl: string; apiKey: string; apiKeyTransmission: string; modelName: string }) =>
      Promise<{ success: boolean; capabilities?: AIEngineCapabilities; error?: string }>;
  };
  // 创意数据 API
  creative: {
    load: () => Promise<{ creatives: any[]; currentCreativeId: string | null; currentEditorTarget: { type: 'character' | 'worldbook'; id: string } | null }>;
    save: (data: { creatives: any[]; currentCreativeId: string | null; currentEditorTarget: { type: 'character' | 'worldbook'; id: string } | null }) => Promise<boolean>;
    export: () => Promise<string>;
    import: (jsonData: string) => Promise<{ success: boolean; error?: string }>;
  };
  // 角色卡对话数据 API
  characterChat: {
    getTestChat: (creativeId: string, characterCardId: string) => Promise<any>;
    saveTestChat: (creativeId: string, characterCardId: string, characterCardName: string, messages: any[]) => Promise<any>;
    deleteTestChat: (creativeId: string, characterCardId: string) => Promise<boolean>;
    getAllTestChats: () => Promise<any[]>;
    clearCache: () => Promise<{ success: boolean }>;
  };
  // 通用存储 API
  storage: {
    get: (key: string) => Promise<{ success: boolean; data?: any; error?: string }>;
    set: (data: { key: string; value: any }) => Promise<{ success: boolean; error?: string }>;
    delete: (key: string) => Promise<{ success: boolean; error?: string }>;
    clear: () => Promise<{ success: boolean; error?: string }>;
    has: (key: string) => Promise<{ success: boolean; exists: boolean; error?: string }>;
    getAll: () => Promise<{ success: boolean; data?: Record<string, any>; error?: string }>;
    import: (data: string) => Promise<{ success: boolean; error?: string }>;
  };
  // 向量存储 API
  vector: {
    add: (id: string, vector: number[], metadata: Record<string, any>) => Promise<{ success: boolean; error?: string }>;
    addBatch: (items: Array<{ id: string; vector: number[]; metadata: Record<string, any> }>) => Promise<{ success: boolean; error?: string }>;
    search: (query: number[], topK: number, filter?: Record<string, any>, scopeIds?: string[]) => Promise<{ success: boolean; results?: Array<{ id: string; score: number; metadata: Record<string, any> }>; error?: string }>;
    update: (id: string, vector: number[], metadata?: Record<string, any>) => Promise<{ success: boolean; error?: string }>;
    delete: (id: string) => Promise<{ success: boolean; error?: string }>;
    count: () => Promise<{ success: boolean; count?: number; error?: string }>;
    rebuildIndex: () => Promise<{ success: boolean; error?: string }>;
    testStorage: () => Promise<{ success: boolean; mode: string; vectorCount: number; storagePath?: string; error?: string; details?: string }>;
    getStorePath: () => Promise<string>;
    getById: (id: string) => Promise<{ success: boolean; item?: any; error?: string }>;
    getAvailableScopes: () => Promise<{ success: boolean; scopes?: any[]; error?: string }>;
  };
  // 向量嵌入 API
  embedding: {
    generate: (text: string) => Promise<{ success: boolean; vector?: number[]; error?: string; dimension?: number; model?: string }>;
    testConnection: () => Promise<{ success: boolean; mode: string; dimension: number; error?: string; details?: string }>;
    setMode: (mode: string) => Promise<{ success: boolean; mode?: string; error?: string }>;
    getMode: () => Promise<{ success: boolean; mode: string; dimension: number }>;
  };
  // 知识库 API
  knowledge: {
    list: (filter?: Record<string, any>, page?: number, pageSize?: number) => Promise<{ success: boolean; items?: any[]; total?: number; error?: string }>;
    get: (id: string) => Promise<any>;
    create: (data: any) => Promise<{ success: boolean; id?: string; error?: string }>;
    createBatch: (items: any[]) => Promise<{ success: boolean; count?: number; error?: string }>;
    update: (id: string, data: any) => Promise<{ success: boolean; error?: string }>;
    delete: (id: string) => Promise<{ success: boolean; error?: string }>;
    deleteBatch: (ids: string[]) => Promise<{ success: boolean; count?: number; error?: string }>;
    search: (query: string, options?: any) => Promise<{ success: boolean; results?: any[]; error?: string }>;
    vectorize: (id: string) => Promise<{ success: boolean; error?: string }>;
    vectorizeAll: () => Promise<{ success: boolean; count?: number; error?: string }>;
    uploadDocument: (filePath: string, options?: { category?: string[]; tags?: string[]; source?: string }) => Promise<{ success: boolean; documentId?: string; knowledgeItemsCreated?: number; chunkCount?: number; error?: string; isDuplicate?: boolean }>;
    selectDocumentFile: () => Promise<string | null>;
  };
  // 上下文管理 API
  context: {
    retrieve: (conversation: Array<{ role: string; content: string }>, options: { topK?: number; minScore?: number; sources?: string[]; filter?: Record<string, any>; scopeIds?: string[] }) => Promise<{ success: boolean; items?: Array<{ id: string; source: string; content: string; score: number; metadata: Record<string, any> }>; error?: string }>;
    retrieveWithKeywords: (
      conversation: Array<{ role: string; content: string }>,
      options: { topK?: number; minScore?: number; sources?: string[]; filter?: Record<string, any>; scopeIds?: string[] },
      enableKeywordMatch?: boolean,
      scanDepth?: number,
      globalScanData?: {
        personaDescription?: string;
        characterDescription?: string;
        characterPersonality?: string;
        characterDepthPrompt?: string;
        scenario?: string;
        creatorNotes?: string;
      }
    ) => Promise<{ success: boolean; items?: Array<{ id: string; source: string; content: string; score: number; metadata: Record<string, any> }>; vectorItems?: any[]; keywordItems?: any[]; error?: string }>;
    compress: (items: Array<{ id: string; source: string; content: string; score: number }>, maxTokens: number) => Promise<{ success: boolean; compressed?: string; error?: string }>;
    retrieveWithHybrid: (query: string, options: any) => Promise<{ success: boolean; items?: Array<{ id: string; source: string; content: string; score: number; metadata: Record<string, any> }>; error?: string }>;
  };

  // 世界书关键词匹配 API
  worldbook: {
    matchKeywords: (text: string, worldBookPaths?: string[], options?: { caseSensitive?: boolean; matchWholeWords?: boolean; maxResults?: number }) => Promise<{ success: boolean; matches: Array<{ entry: any; matchedKeys: string[]; matchType: string; matchScore: number; content: string; comment?: string; name?: string }>; count: number; error?: string }>;
  };

  // 文档向量化 API
  document: {
    process: (filePath: string) => Promise<any>;
    list: () => Promise<any[]>;
    delete: (docId: string) => Promise<boolean>;
    deleteBatch: (docIds: string[]) => Promise<number>;
    getInfo: (docId: string) => Promise<any | null>;
    getChunks: (docId: string) => Promise<Array<{ index: number; text: string }>>;
    searchVectors: (queryText: string, topK: number, docId?: string) => Promise<{ success: boolean; results?: Array<{ id: string; score: number; metadata: Record<string, any> }>; error?: string }>;
    getVectorStats: () => Promise<{ totalVectors: number; documentCount: number; documents: Array<{ docId: string; fileName: string; vectorCount: number }> }>;
    generateEmbedding: (text: string) => Promise<{ success: boolean; vector?: number[]; error?: string; dimension?: number }>;
    selectFile: () => Promise<string | null>;
  };

  // 对话记录向量化 API
  chatVector: {
    vectorize: (characterId: string, messages: Array<{ role: string; content: string; name?: string; create_date?: number }>) => Promise<{
      success: boolean;
      messagesVectorized: number;
      messagesFailed: number;
      error?: string;
      messageVectorIds: string[];
    }>;
    delete: (characterId: string) => Promise<{
      success: boolean;
      deletedCount: number;
      error?: string;
    }>;
    search: (characterId: string, query: string, topK?: number) => Promise<{
      id: string;
      score: number;
      metadata: Record<string, any>;
    }[]>;
  };

  // 对话历史 RAG API（Spec: optimize-chat-ai-intelligence / Task 7.4）
  // retrieve: 检索本会话历史消息的向量相似片段，注入 system prompt"区域 2：本会话相关历史片段"
  // vectorizeIncremental: 增量向量化最近消息（跳过已向量化的 messageId），fire-and-forget
  chatHistory: {
    retrieve: (
      chatId: string,
      queryText: string,
      topK?: number,
      minScore?: number
    ) => Promise<Array<{ content: string; score: number; timestamp: number }>>;
    vectorizeIncremental: (
      chatId: string,
      messages: Array<{ role: string; content: string; id?: string; name?: string; timestamp?: number; create_date?: number }>
    ) => Promise<{ success: boolean }>;
  };

  // 写作模式 API
  writing: {
    loadProjects: () => Promise<{ success: boolean; projects: any[] }>;
    createProject: (config: any) => Promise<{ success: boolean; projectId: string }>;
    saveProject: (project: any) => Promise<{ success: boolean }>;
    deleteProject: (projectId: string) => Promise<{ success: boolean }>;
    exportProject: (projectId: string, format: string) => Promise<{ success: boolean; filePath?: string }>;
    generateOutline: (request: any) => Promise<{ success: boolean; outline?: any; outlineRaw?: string; error?: string; parseError?: string }>;
    saveProjectRaw: (projectId: string, rawContent: string) => Promise<{ success: boolean; error?: string }>;
    generateChapter: (request: any) => Promise<{ success: boolean }>;
    generateChapterChunk: (request: any) => Promise<{ success: boolean }>;
    cancelGeneration: (projectId: string) => Promise<{ success: boolean }>;
    cancelChunkGeneration: (projectId: string, chapterIndex: number, chunkIndex: number) => Promise<{ success: boolean }>;
    autoSaveChapter: (data: { projectId: string; chapterIndex: number; content: string }) => Promise<{ success: boolean }>;
    saveVersion: (data: { projectId: string; chapterIndex: number; content: string; note?: string }) => Promise<{ success: boolean }>;
    restoreVersion: (data: { projectId: string; chapterIndex: number; versionId: string }) => Promise<{ success: boolean }>;
    onStreamChunk: (callback: (data: { projectId: string; chapterIndex: number; chunk: string }) => void) => () => void;
    onStreamComplete: (callback: (data: { projectId: string; chapterIndex: number; content: string; metadata: any }) => void) => () => void;
    onStreamError: (callback: (data: { projectId: string; chapterIndex: number; error: any }) => void) => () => void;
    onChunkStart: (callback: (data: { projectId: string; chapterIndex: number; chunkIndex: number }) => void) => () => void;
    onChunkProgress: (callback: (data: { projectId: string; chapterIndex: number; chunkIndex: number; chunk: string }) => void) => () => void;
    onChunkComplete: (callback: (data: { projectId: string; chapterIndex: number; chunkIndex: number; content: string }) => void) => () => void;
    onChunkError: (callback: (data: { projectId: string; chapterIndex: number; chunkIndex: number; error: any }) => void) => () => void;
    offStreamChunk: (callback: (data: any) => void) => void;
    offStreamComplete: (callback: (data: any) => void) => void;
    offStreamError: (callback: (data: any) => void) => void;
    // 写作风格 API
    style: {
      upload: (request: WritingStyleLearningRequest) => Promise<{ success: boolean; taskId: string; error?: string }>;
      list: () => Promise<{ success: boolean; styles: WritingStyleResource[]; error?: string }>;
      get: (resourceId: string) => Promise<{ success: boolean; style: WritingStyleResource | null; error?: string }>;
      delete: (resourceId: string) => Promise<{ success: boolean; error?: string }>;
      cancel: (taskId: string) => Promise<{ success: boolean; error?: string }>;
      getActiveTasks: () => Promise<{ success: boolean; activeTaskIds: string[]; error?: string }>;
      onProgress: (callback: (data: { taskId: string; progress: WritingStyleProgress }) => void) => () => void;
      onComplete: (callback: (data: { taskId: string; resource: WritingStyleResource }) => void) => () => void;
      onError: (callback: (data: { taskId: string; error: string }) => void) => () => void;
    };
    // 表格整理 API
    table: {
      getTableData: (projectId: string) => Promise<{ sheets: string[]; headers: Record<string, string[]>; data: Record<string, Record<string, any>[]>; sheetDescriptions: Record<string, string> }>;
      saveTableData: (projectId: string, sheetName: string, sheetData: Record<string, any>[]) => Promise<void>;
      clearTableData: (projectId: string) => Promise<void>;
      updateRowInTable: (projectId: string, sheetName: string, rowIndex: number, rowData: Record<string, any>) => Promise<boolean>;
      getTableConfig: (projectId: string) => Promise<{ enabled: boolean; autoOrganize: boolean; organizeMode: 'sync' | 'async'; associatedTemplateId: string | null; associatedTemplateName: string } | null>;
      saveTableConfig: (projectId: string, config: { enabled: boolean; autoOrganize: boolean; organizeMode: 'sync' | 'async'; associatedTemplateId: string | null; associatedTemplateName: string }) => Promise<void>;
      associateTableTemplate: (projectId: string, templateId: string, templateName: string, templateSheets: Array<{ name: string; headers: string[]; description?: string }>) => Promise<{ success: boolean; error?: string }>;
      getAllTemplates: () => Promise<{ success: boolean; templates: any[]; error?: string }>;
      organizeTable: (projectId: string, modelConfig: any, chapterIndex?: number) => Promise<{ success: boolean; message: string; processedCount?: number; errorCount?: number; errors?: string[] }>;
      getOrganizeProgress: (projectId: string) => Promise<{ progress: number; status: string } | null>;
    };
    // 自定义模板管理 API
    template: {
      novelType: {
        list: () => Promise<{ success: boolean; templates: CustomNovelTypeTemplate[]; error?: string }>;
        get: (id: string) => Promise<{ success: boolean; template: CustomNovelTypeTemplate | null; error?: string }>;
        save: (template: CustomNovelTypeTemplate) => Promise<{ success: boolean; id?: string; error?: string }>;
        delete: (id: string) => Promise<{ success: boolean; error?: string }>;
      };
      writingStyle: {
        list: () => Promise<{ success: boolean; templates: CustomWritingStyleTemplate[]; error?: string }>;
        get: (id: string) => Promise<{ success: boolean; template: CustomWritingStyleTemplate | null; error?: string }>;
        save: (template: CustomWritingStyleTemplate) => Promise<{ success: boolean; id?: string; error?: string }>;
        delete: (id: string) => Promise<{ success: boolean; error?: string }>;
      };
    };
    // 写作智能体编排 API（Task 15.2: 前端"智能体写作"按钮 + 进度流 + 断点续跑）
    agent: {
      /** 启动智能体写作编排 */
      run: (request: WritingAgentRequest) => Promise<WritingAgentResult>;
      /** 取消正在运行的编排 */
      cancel: () => Promise<{ success: boolean; error?: string }>;
      /** 查询编排状态（running + checkpoint） */
      status: () => Promise<WritingAgentStatus>;
      /** 从 checkpoint 恢复编排 */
      resume: (request: WritingAgentRequest) => Promise<WritingAgentResult>;
      /** 订阅进度事件，返回取消订阅函数 */
      onProgress: (callback: (event: WritingAgentEvent) => void) => () => void;
    };
  };

  prompt: {
    getAll: () => Promise<{ success: boolean; data?: any[]; error?: string }>;
    get: (moduleId: string) => Promise<{ success: boolean; data?: any; error?: string }>;
    save: (template: any, modifiedBy: string, changeSummary: string) => Promise<{ success: boolean; data?: any; error?: string }>;
    getHistory: (moduleId: string) => Promise<{ success: boolean; data?: any[]; error?: string }>;
    rollback: (moduleId: string, version: number, modifiedBy: string) => Promise<{ success: boolean; data?: any; error?: string }>;
    clearHistory: (moduleId: string) => Promise<{ success: boolean; error?: string }>;
    build: (moduleId: string, variables: Record<string, string>) => Promise<{ success: boolean; data?: { systemPrompt: string; userPrompt: string }; error?: string }>;
    validate: (template: any) => Promise<{ success: boolean; data?: any; error?: string }>;
    reset: (moduleId: string) => Promise<{ success: boolean; data?: any; error?: string }>;
    optimize: (request: PromptPolishRequest) => Promise<{ success: boolean; data?: PromptPolishResult; error?: string }>;
  };

  // Token 计数 API（精确 cl100k_base，由主进程 TokenCountService 提供）
  token: {
    count: (text: string) => Promise<number>;
    countBatch: (messages: Array<{ id: string; text: string }>) => Promise<Array<{ id: string; count: number }>>;
  };

  // 角色卡表情管理 API（Spec: add-character-expression-system / Task 1）
  // 存储路径：{userData}/data/character-expressions/{sha256(characterCardId).slice(0,16)}/
  // 每个角色卡一个 manifest.json + 多个 {emotionKey}.png
  expression: {
    /** 读取角色卡表情包 manifest；若不存在返回空白默认 manifest */
    list: (characterCardId: string) => Promise<{
      characterCardId: string;
      version: 1;
      expressions: Record<string, { type: 'preset' | 'custom'; image: string }>;
      customEmotions: Array<{ key: string; label: string }>;
    }>;
    /** 保存表情图像（base64，可含 data URI 前缀）并更新 manifest；返回图像绝对路径 */
    saveImage: (args: {
      characterCardId: string;
      emotionKey: string;
      imageBase64: string;
      isCustom: boolean;
      label?: string;
    }) => Promise<{ success: boolean; error?: string; imagePath?: string }>;
    /** 删除指定情绪的图像文件，并从 manifest.expressions 移除（保留 customEmotions） */
    deleteImage: (args: { characterCardId: string; emotionKey: string }) => Promise<{ success: boolean; error?: string }>;
    /** 添加自定义情绪类别（key 需匹配 ^[a-z][a-z0-9_]*$） */
    addCustomEmotion: (args: { characterCardId: string; key: string; label: string }) => Promise<{ success: boolean; error?: string }>;
    /** 移除自定义情绪类别：从 customEmotions + expressions 移除，并删除图像文件 */
    removeCustomEmotion: (args: { characterCardId: string; key: string }) => Promise<{ success: boolean; error?: string }>;
    /** 获取指定情绪的图像绝对路径，不存在时返回 null */
    getImagePath: (args: { characterCardId: string; emotionKey: string }) => Promise<{ success: boolean; imagePath: string | null; error?: string }>;
  };

  // 角色特征管理 API（Spec: add-asset-and-trait-management / Task 2 + add-trait-category-grouping / Task 3）
  // 为每个角色卡持久化视觉特征清单，SD 生成素材时携带以保证角色一致性
  // v2 升级：结构化 CharacterTraitItem[] + 分类 + 组合方案，下游仅拼接 enabled=true 项
  // 存储路径：{userData}/data/character-traits/{sha256(characterCardId).slice(0,16)}/traits.json
  characterTrait: {
    /**
     * 读取角色卡视觉特征 tag 数组（v1 string[] 兼容）；文件不存在或解析失败时返回 []
     * @deprecated 改用 loadData 获取完整 v2 数据（含分类/组合/启用状态）
     */
    list: (characterCardId: string) => Promise<string[]>;
    /**
     * 覆盖保存角色卡视觉特征 tag 数组（v1 string[] 兼容，自动创建目录，原子写入 traits.json）
     * 合并去重：保留现有已分类 item，对传入 string 中新增的项追加为 uncategorized + enabled=true
     * @deprecated 改用 saveData 保存完整 v2 数据
     */
    save: (args: { characterCardId: string; traits: string[]; appearanceDescription?: string }) => Promise<{ success: boolean; error?: string }>;
    /** 读取角色卡外观描述（中文自然语言）；不存在时返回空串 */
    loadDescription: (characterCardId: string) => Promise<string>;
    /** 清除角色卡特征文件（删除 traits.json，文件不存在视为幂等成功） */
    clear: (characterCardId: string) => Promise<{ success: boolean; error?: string }>;
    /**
     * 读取角色卡完整 v2 数据（Spec: add-trait-category-grouping / Task 3）。
     * 文件不存在返回空白 v2（traits:[], customCategories:[], combinations:[], activeCombinationId:null）；
     * v1 数据自动迁移为 v2 后返回；字段缺失由 service 防御性兜底补全。
     */
    loadData: (characterCardId: string) => Promise<CharacterTraitManifestV2>;
    /**
     * 覆盖保存角色卡完整 v2 数据（version 强制为 2，含分类/组合/启用状态）。
     * 自动创建目录，原子写入 traits.json；返回 { success, error? }。
     */
    saveData: (args: { characterCardId: string; data: CharacterTraitManifestV2 }) => Promise<{ success: boolean; error?: string }>;
  };

  // 全局特征分类字典 API（Spec: fix-asset-trait-and-scene-defects / Task 3）
  // 跨角色卡共享的自定义分类字典，持久化到 {userData}/data/trait-categories.json
  // 取代 CharacterTraitManifestV2.customCategories 作为分类的唯一读取源
  // 系统分类（SYSTEM_TRAIT_CATEGORIES）仍由代码常量提供，不写入此字典
  //
  // 类型声明策略（与 characterTrait 一致）：
  //   - 主进程 `CategoryDictionaryService` 定义于 src/main/services/categoryDictionaryService.ts，
  //     渲染进程不直接引用主进程类型
  //   - 此处使用 shared 类型（GlobalTraitCategoryDictionary / TraitCategory）+ 内联返回类型签名
  categoryDictionary: {
    /**
     * 读取全局分类字典。
     * 文件不存在或损坏时返回空白字典（version=1, categories=[], updatedAt=now）。
     * 返回 `{ success: true, dictionary }`；失败时返回 `{ success: false, error }`。
     */
    load: () => Promise<{ success: boolean; dictionary?: GlobalTraitCategoryDictionary; error?: string }>;
    /**
     * 新增自定义分类（重名时返回既有分类，不创建副本）。
     * 返回 `{ success: true, category }`；name 为空时返回 `{ success: false, error }`。
     */
    add: (args: { name: string; icon?: string }) => Promise<{ success: boolean; category?: TraitCategory; error?: string }>;
    /**
     * 按 id 删除自定义分类（幂等：id 不存在视为成功）。
     * 返回 `{ success: true }` 或 `{ success: false, error }`。
     */
    delete: (args: { id: string }) => Promise<{ success: boolean; error?: string }>;
    /**
     * 按 id 重命名自定义分类。
     * newName 为空或重名时返回 `{ success: false, error }`；id 不存在视为幂等成功。
     */
    rename: (args: { id: string; newName: string }) => Promise<{ success: boolean; error?: string }>;
    /**
     * 检查全局字典中是否已存在指定名称的分类（大小写不敏感）。
     * 返回 `{ success: true, exists }`；name 为空时 exists=false。
     */
    has: (args: { name: string }) => Promise<{ success: boolean; exists?: boolean; error?: string }>;
  };

  // 角色卡 LoRA 管理 API（2026-07-29 bug 修复 - 按角色独立存储）
  // 【重点标记】原实现将 LoRA 存在全局设置中导致角色间污染，现改为按角色卡独立持久化
  // 存储路径：{userData}/data/character-loras/{sha256(characterCardId).slice(0,16)}/loras.json
  characterLora: {
    /** 读取角色卡 LoRA 模型清单；文件不存在或解析失败时返回 [] */
    list: (characterCardId: string) => Promise<Array<{ name: string; weight: number }>>;
    /** 覆盖保存角色卡 LoRA 模型清单（自动创建目录，原子写入 loras.json） */
    save: (args: {
      characterCardId: string;
      loras: Array<{ name: string; weight: number }>;
    }) => Promise<{ success: boolean; error?: string }>;
  };

  // 素材管理 API（Spec: add-asset-and-trait-management / Task 7）
  // 通用素材管理，支持 illustration / general / three-view 三种素材类型
  // 表情类型（expression）继续走 expressionService.ts，不纳入本命名空间
  // 存储路径：{userData}/data/character-assets/{sha256(characterCardId).slice(0,16)}/{assetType}/...
  //
  // 注意：assetType 在 preload 透传为 string（避免主进程 AssetType 类型泄露），
  //       实际仅接受 'illustration' | 'general' | 'three-view'，
  //       service 内部对 three-view 类型校验 assetId 是否在 front/side/back 白名单内
  asset: {
    /** 读取角色卡 × assetType 的素材包 manifest；不存在时返回默认空 manifest */
    list: (args: { characterCardId: string; assetType: string }) => Promise<{
      characterCardId: string;
      version: 1;
      assets: Record<string, {
        id: string;
        type: 'illustration' | 'general' | 'three-view';
        slot?: 'front' | 'side' | 'back' | 'front-nude' | 'side-nude' | 'back-nude';
        image: string;
        createdAt: string;
      }>;
    }>;
    /** 保存素材图像（base64，可含 data URI 前缀）并更新 manifest；返回图像绝对路径 */
    save: (args: {
      characterCardId: string;
      assetType: string;
      assetId: string;
      imageBase64: string;
      slot?: string;
    }) => Promise<{ success: boolean; error?: string; imagePath?: string }>;
    /** 删除指定素材的图像文件并从 manifest.assets 移除条目（幂等） */
    delete: (args: { characterCardId: string; assetType: string; assetId: string }) => Promise<{ success: boolean; error?: string }>;
    /**
     * 获取指定素材的图像绝对路径；不存在时 imagePath=null，success=true
     * 【重点标记 - CSP 兼容】返回的 imagePath 为磁盘绝对路径，
     * 渲染进程应通过 file.readAsBase64 转 data URL 后再用于 <img src>
     */
    getImagePath: (args: { characterCardId: string; assetType: string; assetId: string }) => Promise<{ success: boolean; imagePath: string | null; error?: string }>;
  };

  // SD 表情生成 API（Spec: add-ai-expression-generation / Task 2 + integrate-nl-driven-sd-models / Task 5）
  // 通过 SD WebUI img2img / txt2img 端点生成角色卡表情图片
  // 注意：本命名空间合并了 Task 6 的 checkStatus / getModels，并由 Task 2 追加
  //       generateExpression / generateAllExpressions / cancelGeneration 及事件监听器，
  //       Task 5 追加 generateTxt2Img（NL 驱动模型文生图）。
  // options 类型实际为 SDGenerationOptions（定义于 src/main/services/sdGenerationService.ts），
  // 因主进程类型不可直接被渲染进程引用，此处使用 any 以匹配 preload 实现
  sd: {
    /** 检查 SD WebUI API 状态（GET /sdapi/v1/options + /sdapi/v1/script-info），返回当前模型 + ADetailer 可用性 */
    checkStatus: (endpoint: string) => Promise<{
      available: boolean;
      currentModel?: string;
      adetailerAvailable?: boolean;
      error?: string;
    }>;
    /** 获取 SD WebUI 已加载的模型列表（GET /sdapi/v1/sd-models） */
    getModels: (endpoint: string) => Promise<{
      success: boolean;
      models: Array<{ title: string; model_name: string; hash?: string }>;
      error?: string;
    }>;
    /** 生成单个表情图片（内部先 extractBaseImage 再 generateExpression） */
    generateExpression: (args: {
      characterCardPath: string;
      emotionKey: string;
      prompt: string;
      negativePrompt: string;
      options?: any;
    }) => Promise<{ success: boolean; imageBase64?: string; error?: string; warning?: string }>;
    /** 文生图（txt2img），适用于 qwen-image / flux2 等 NL 驱动模型 */
    generateTxt2Img: (args: {
      endpoint: string;
      prompt: string;
      negativePrompt?: string;
      options?: any;
    }) => Promise<{ success: boolean; imageBase64?: string; error?: string; warning?: string }>;
    /** 批量生成多个表情，通过 onGenerationProgress / onGenerationComplete 推送进度 */
    generateAllExpressions: (args: {
      characterCardPath: string;
      emotions: Array<{ key: string; prompt: string; negativePrompt: string }>;
      options?: any;
    }) => Promise<{
      success: boolean;
      total: number;
      successCount: number;
      failedCount: number;
      cancelledCount: number;
    }>;
    /** 取消正在进行的批量生成任务（设置模块级取消标志） */
    cancelGeneration: () => Promise<{ success: boolean }>;
    /** 监听单个表情生成进度事件 */
    onGenerationProgress: (callback: (data: {
      current: number;
      total: number;
      emotionKey: string;
      status: 'success' | 'failed';
      error?: string;
      imageBase64?: string;
    }) => void) => void;
    /** 监听批量生成完成事件 */
    onGenerationComplete: (callback: (data: {
      total: number;
      success: number;
      failed: number;
      cancelled: number;
    }) => void) => void;
    /** 移除所有进度监听器（组件卸载时调用） */
    removeProgressListeners: () => void;
  };

  // 游戏模式 API（Spec: add-game-mode-framework / Task 5 preload 契约）
  // 命名空间由 Task 5 在 preload.ts 中实现；此处类型声明由 Task 6 提前补全以解耦渲染进程开发
  game: {
    list: () => Promise<{ success: boolean; games?: GameIndexEntry[]; error?: string }>;
    getMeta: (gameId: string) => Promise<{ success: boolean; meta?: GameMeta | null; error?: string }>;
    createGame: (meta: GameMeta) => Promise<{ success: boolean }>;
    updateGame: (gameId: string, updates: Partial<GameMeta>) => Promise<{ success: boolean }>;
    deleteGame: (gameId: string) => Promise<{ success: boolean }>;
    createSave: (params: {
      gameId: string;
      gameType: GameType;
      name: string;
      isAuto: boolean;
      tableSchema: GameTableSchema;
      initialState?: Record<string, any>;
    }) => Promise<{ success: boolean; meta?: GameSaveMeta; error?: string }>;
    loadSave: (saveId: string) => Promise<{ success: boolean; data?: GameSaveData | null; error?: string }>;
    listSaves: (gameId: string) => Promise<{ success: boolean; saves?: GameSaveMeta[]; error?: string }>;
    deleteSave: (saveId: string) => Promise<{ success: boolean }>;
    save: (
      saveId: string,
      updates: {
        narrativeLog?: GameSaveData['narrativeLog'];
        stateSnapshot?: Record<string, any>;
        currentTurn?: number | null;
        currentNodeId?: string | null;
        nodeTitle?: string | null;
        turnCount?: number;
      }
    ) => Promise<{ success: boolean }>;
    getTableData: (saveId: string) => Promise<{ success: boolean; data?: GameTableData | null; error?: string }>;
    saveTableData: (saveId: string, tableData: GameTableData) => Promise<{ success: boolean }>;
    applyTableEdits: (
      saveId: string,
      commands: GameTableEditCommand[]
    ) => Promise<{
      success: boolean;
      changes: {
        commandsExecuted: number;
        affectedSheets: string[];
        errors: string[];
      };
    }>;
    getVersionSnapshot: (saveId: string) => Promise<{ success: boolean; snapshot?: any; error?: string }>;
    confirmVersion: (saveId: string) => Promise<{ success: boolean }>;
    rollbackVersion: (saveId: string) => Promise<{ success: boolean }>;
    generateNarrative: (request: GameNarrativeRequest) => Promise<void>;
    cancelGeneration: (saveId: string) => Promise<void>;
    getConfig: (gameId: string) => Promise<{ success: boolean; config?: GameLocalConfig; error?: string }>;
    saveConfig: (gameId: string, config: GameLocalConfig) => Promise<{ success: boolean }>;
    // 事件监听器（每个返回 unsubscribe 函数）
    onNarrativeChunk: (callback: (data: GameNarrativeChunk) => void) => () => void;
    onNarrativeComplete: (callback: (data: GameNarrativeComplete) => void) => () => void;
    onNarrativeError: (callback: (data: GameNarrativeError) => void) => () => void;
    onTableUpdated: (callback: (data: GameTableUpdated) => void) => () => void;
  };

  // LoRA 模型列表 API（Spec: add-lora-model-selection / Task 3）
  // 通过 SD WebUI API 获取可用 LoRA 模型列表，含预览图 URL 和 JSON 元数据
  lora: {
    list: (endpoint: string) => Promise<{
      success: boolean;
      loras?: Array<{
        name: string;
        alias: string;
        path: string;
        previewUrl: string;
        description: string;
        activationText: string;
        preferredWeight: number;
        sdVersion: string;
        notes: string;
        category: string;
      }>;
      error?: string;
    }>;
  };

  // ============================================================================
  // Agent 智能体底座 API（Spec: implement-agent-foundation-and-fix-defects / Task 9 + Task 18）
  // ============================================================================
  // agent:run/cancel + 流式事件订阅 + skill:list/invoke + agentMemory:search + learning:*
  agent: {
    /** 启动 agent 运行 */
    run: (intent: {
      systemPrompt: string;
      messages: Array<{ role: 'user' | 'assistant'; content: string }>;
      context?: {
        sessionId?: string;
        characterId?: string;
        mode?: 'dialogue' | 'writing' | 'game' | 'worldbook';
        allowedWorldBookPaths?: string[];
      };
      maxIterations?: number;
      timeoutMs?: number;
    }) => Promise<{
      success: boolean;
      result?: {
        content: string;
        toolCallHistory: Array<{
          name: string;
          args: Record<string, unknown>;
          result: { success: boolean; content: string; continueLoop?: boolean };
          durationMs: number;
        }>;
        iterations: number;
        finishReason: 'stop' | 'length' | 'maxIterations' | 'timeout' | 'error';
        usage?: { promptTokens?: number; completionTokens?: number; totalTokens?: number };
        error?: string;
      };
      error?: string;
    }>;
    /** 取消当前 agent 运行 */
    cancel: () => Promise<{ success: boolean; error?: string }>;
    /** 订阅 token 流式事件 */
    onToken: (callback: (data: { chunk: string; timestamp: number }) => void) => () => void;
    /** 订阅工具调用事件 */
    onToolCall: (callback: (data: {
      name: string;
      args: Record<string, unknown>;
      phase: 'start' | 'end';
      result?: unknown;
      durationMs?: number;
      timestamp: number;
    }) => void) => () => void;
    /** 订阅 agent 完成事件 */
    onDone: (callback: (data: {
      finishReason: string;
      iterations: number;
      error?: string;
      timestamp: number;
    }) => void) => () => void;

    /** Agent 模式管理 API */
    mode: {
      /** 获取完整模式状态 */
      getStatus: () => Promise<{ ok: boolean; status?: AgentModeStatus; error?: string }>;
      /** 查询 Agent 模式是否激活 */
      isModeActive: () => Promise<{ ok: boolean; active?: boolean; error?: string }>;
      /** 设置覆盖开关（auto / force-on / force-off） */
      setOverride: (override: AgentModeOverride) => Promise<{ ok: boolean; status?: AgentModeStatus; error?: string }>;
      /** 订阅模式变更事件，返回取消订阅函数 */
      onModeChanged: (callback: (status: AgentModeStatus) => void) => () => void;
    };

    /** Agent 配置管理 API（Spec: add-agent-mode-management-and-center / Task 5.2） */
    config: {
      /** 列出全部智能体配置 */
      list: () => Promise<{ ok: boolean; configs?: AgentConfig[]; error?: string }>;
      /** 获取单个智能体配置 */
      get: (id: string) => Promise<{ ok: boolean; config?: AgentConfig; error?: string }>;
      /** 更新智能体配置（Partial<AgentConfig>） */
      update: (id: string, patch: Partial<AgentConfig>) => Promise<{ ok: boolean; config?: AgentConfig; error?: string }>;
      /** 切换智能体启用/禁用状态 */
      toggle: (id: string) => Promise<{ ok: boolean; config?: AgentConfig; error?: string }>;
      /** 更新技能白名单 */
      updateSkills: (id: string, skills: string[]) => Promise<{ ok: boolean; config?: AgentConfig; error?: string }>;
      /** 创建用户自定义智能体 */
      create: (config: Omit<AgentConfig, 'id' | 'createdAt' | 'updatedAt' | 'isSystem'>) => Promise<{ ok: boolean; config?: AgentConfig; error?: string }>;
      /** 删除用户自定义智能体（系统预置不可删除） */
      delete: (id: string) => Promise<{ ok: boolean; error?: string }>;
      /** 订阅配置变更事件，返回取消订阅函数 */
      onConfigChanged: (callback: (data: { agentId: string; action: 'created' | 'updated' | 'deleted' | 'toggled' | 'skills-updated' }) => void) => () => void;
    };

    /** 故障转移 API（Spec: optimize-agent-interaction-from-openclaw / Task 10） */
    failover: {
      /** 获取备用 provider 列表 */
      getProviders: () => Promise<{
        success: boolean;
        providers?: Array<{
          provider: string;
          model: string;
          apiKey: string;
          baseUrl: string;
        }>;
        error?: string;
      }>;
      /** 设置备用 provider 列表 */
      setProviders: (providers: Array<{
        provider: string;
        model: string;
        apiKey: string;
        baseUrl: string;
      }>) => Promise<{ success: boolean; error?: string }>;
      /** 订阅故障转移事件，返回取消订阅函数 */
      onFailover: (callback: (data: {
        type: 'retry' | 'switch';
        fromProvider?: string;
        toProvider?: string;
        toModel?: string;
        reason: string;
        attempt?: number;
        timestamp: number;
      }) => void) => () => void;
    };
  };

  /** 技能系统 API（Task 14） */
  skill: {
    list: () => Promise<{
      success: boolean;
      skills?: Array<{ name: string; title?: string; description?: string; emoji?: string; source?: string; userInvocable?: boolean }>;
      error?: string;
    }>;
    invoke: (args: {
      skillName: string;
      args: Record<string, unknown>;
      context?: any;
    }) => Promise<{ success: boolean; result?: any; error?: string }>;
    importFromDir: (dirPath: string) => Promise<{ success: boolean; skillName?: string; error?: string }>;
    importFromUrl: (url: string) => Promise<{ success: boolean; skillName?: string; error?: string }>;
    uninstall: (skillName: string) => Promise<{ success: boolean; error?: string }>;
    getDetail: (skillName: string) => Promise<{ success: boolean; detail?: { name: string; description: string; body: string; source: string; filePath: string }; error?: string }>;
    create: (params: { name: string; description: string; emoji?: string; body: string }) => Promise<{ success: boolean; skillName?: string; error?: string }>;
    edit: (params: { name: string; description: string; emoji?: string; body: string }) => Promise<{ success: boolean; skillName?: string; error?: string }>;
    getPromptSnippet: () => Promise<{ success: boolean; prompt: string; error?: string }>;
  };

  /** Agent 记忆检索 API（Task 8） */
  agentMemory: {
    search: (query: {
      query: string;
      types?: string[];
      limit?: number;
      characterId?: string;
      sessionId?: string;
    }) => Promise<{
      success: boolean;
      entries?: Array<{
        id: string;
        type: string;
        content: string;
        source: string;
        score?: number;
        metadata?: Record<string, unknown>;
        characterId?: string;
        sessionId?: string;
        timestamp: number;
      }>;
      error?: string;
    }>;
  };

  /** Agent 学习系统 API（Task 18: dreaming / goal / steer / feedback） */
  learning: {
    /** 手动触发 dreaming（短期→长期记忆摘要） */
    dream: (args: { sessionId?: string }) => Promise<{
      success: boolean;
      result?: {
        startedAt: number;
        finishedAt: number;
        phases: Array<{
          phase: 'light' | 'deep' | 'rem';
          processedCount: number;
          promotedCount: number;
          skippedCount: number;
          durationMs: number;
          error?: string;
        }>;
        totalPromoted: number;
      };
      error?: string;
    }>;
    /** 取消正在进行的 dreaming */
    cancelDream: () => Promise<{ success: boolean; error?: string }>;
    /** 查询 dreaming 运行状态 */
    getDreamingStatus: () => Promise<{ success: boolean; running: boolean }>;
    /** 创建会话目标（仅用户/system 显式请求可创建） */
    createGoal: (args: {
      sessionId: string;
      characterId?: string;
      objective: string;
      tokenBudget?: number;
    }) => Promise<{
      success: boolean;
      goal?: {
        id: string;
        sessionId: string;
        characterId?: string;
        objective: string;
        status: 'pending' | 'in_progress' | 'complete' | 'blocked';
        tokenBudget?: number;
        tokensUsed?: number;
        note?: string;
        blocker?: string;
        consecutiveBlockerCount?: number;
        createdAt: number;
        updatedAt: number;
      };
      error?: string;
    }>;
    /** 获取当前会话目标 */
    getGoal: (sessionId: string) => Promise<{
      success: boolean;
      goal: any | null;
      error?: string;
    }>;
    /** 更新目标状态（complete | blocked，blocked 需同 blocker 连续 3 次才生效） */
    updateGoal: (args: {
      sessionId: string;
      status: 'complete' | 'blocked';
      note?: string;
      blocker?: string;
      tokensDelta?: number;
      actor?: 'user' | 'agent' | 'system';
    }) => Promise<{ success: boolean; goal?: any; error?: string }>;
    /** 清除会话目标（标记 complete，保留审计记录） */
    clearGoal: (sessionId: string) => Promise<{ success: boolean; error?: string }>;
    /** 写入引导消息（注入下一轮 LLM 请求前） */
    steer: (args: {
      sessionId: string;
      content: string;
      source: 'user' | 'system' | 'agent';
      label?: string;
    }) => Promise<{ success: boolean; id?: string; error?: string }>;
    /** 列出 pending 引导消息 */
    listSteer: (sessionId: string) => Promise<{
      success: boolean;
      messages: Array<{ id: string; promptPreview: string }>;
      error?: string;
    }>;
    /** 记录用户反馈（thumb_down / low_rating / comment / correction） */
    recordFeedback: (args: {
      sessionId: string;
      characterId?: string;
      agentResponse?: string;
      userComment?: string;
      kind: 'thumb_down' | 'low_rating' | 'comment' | 'correction';
      rating?: number;
    }) => Promise<{ success: boolean; id?: string; error?: string }>;
    /** 触发反馈反思（LLM 反思 → 写回经验记忆） */
    runReflection: (args: {
      sessionId: string;
      agentResponse?: string;
      userComment?: string;
    }) => Promise<{
      success: boolean;
      result?: {
        status: 'cooldown' | 'empty' | 'complete';
        learning?: string;
        followUp?: boolean;
        userMessage?: string;
        memoryId?: string;
      };
      error?: string;
    }>;
  };

  // 网络搜索 API（Spec: add-agent-web-search-tool / Task 8）
  webSearch: {
    /** 测试连接（设置面板"测试连接"按钮调用） */
    test: (config: { provider: string; apiKey: string; endpoint: string }) => Promise<{
      ok: boolean;
      data?: { resultCount: number; sampleResult?: { title: string; snippet: string; url: string; source: string } };
      error?: string;
    }>;
    /** 直接搜索（读取已保存的 webSearch 配置） */
    search: (args: { query: string; maxResults?: number }) => Promise<{
      ok: boolean;
      data?: Array<{ title: string; snippet: string; url: string; source: string }>;
      error?: string;
    }>;
  };

  // 标签自动推荐 API（Spec: implement-local-tag-autocomplete / Task 3）
  // 4 个 IPC 通道：tag:search / tag:getLoadStatus / tag:reload / tag:setCsvPath
  // 渲染进程通过 window.api.tag.* 调用，主进程由 tagAutocompleteService 单例处理
  tag: {
    /** 查询标签库（子串匹配 + 排序，返回最多 50 条结果） */
    search: (args: {
      query: string;
      sortBy?: 'relevance' | 'count' | 'alphabetical';
      limit?: number;
    }) => Promise<{
      success: boolean;
      results: Array<{
        name: string;
        category: number;
        count: number;
        aliases: string[];
        matchType: 'prefix' | 'includes' | 'alias';
      }>;
      total: number;
      error?: string;
      loading?: boolean;
    }>;
    /** 获取加载状态（设置面板展示 csvPath / 总数 / 错误用） */
    getLoadStatus: () => Promise<{
      loaded: boolean;
      loading: boolean;
      totalCount: number;
      csvPath: string;
      error?: string;
    }>;
    /** 重新加载标签库（不传 csvPath 沿用当前路径；传入则切换路径并重新加载） */
    reload: (args?: { csvPath?: string }) => Promise<{
      success: boolean;
      totalCount: number;
      error?: string;
    }>;
    /** 设置新 CSV 路径并重新加载（语义等同于 reload 传 csvPath） */
    setCsvPath: (args: { csvPath: string }) => Promise<{
      success: boolean;
      totalCount: number;
      error?: string;
    }>;
  };

  // RAG 标签库 API（Spec: rag-tag-library-for-ai-trait-generation / Task 8）
  // 5 个 IPC 通道 + 1 个进度事件订阅，调用 tagRagService 单例
  // 用途：将 31.7 万 Danbooru/e621 标签向量化后语义检索，
  //       在 AI 生成特征时注入「标签库参考」段落，防止生成标签库以外的新 tag
  tagRag: {
    /**
     * 获取当前状态快照。
     * - status: idle（未向量化）/ vectorizing（向量化中）/ ready（就绪）/ error（失败）/ stale（索引过期）
     * - 调用时会懒校验 csvHash/dimension/model 是否变更，变更则降级为 'stale'
     */
    getStatus: () => Promise<{
      status: 'idle' | 'vectorizing' | 'ready' | 'error' | 'stale';
      current: number;
      total: number;
      failedCount: number;
      startedAt?: number;
      finishedAt?: number;
      lastError?: string;
      meta: {
        csvHash: string;
        dimension: number;
        model: string;
        totalTags: number;
        vectorizedCount: number;
        failedCount: number;
        lastVectorizedAt: number;
        durationMs: number;
        status: 'ready' | 'error';
      } | null;
    }>;

    /**
     * 启动向量化（异步长任务，本 Promise 在向量化完成时 resolve）。
     * 进度通过 onProgress 实时推送，无需轮询 getStatus。
     * 并发去重：vectorizeAll 期间再次调用复用同一 Promise。
     * @param args.force 强制重新向量化（即使索引就绪且指纹匹配）
     */
    startVectorization: (args?: { force?: boolean }) => Promise<{
      success: boolean;
      vectorized: number;
      failed: number;
      durationMs?: number;
      error?: string;
    }>;

    /** 取消进行中的向量化（在当前批次结束后生效；已写入向量保留） */
    cancelVectorization: () => Promise<{
      success: boolean;
      message?: string;
    }>;

    /**
     * 语义检索相关标签。
     * 降级返回空数组的条件：tagRag.enabled=false / status!=='ready' / query 为空 / embedding 失败。
     * @param args.query 查询文本（角色描述 / 自然语言指令等）
     * @param args.topK 返回结果数量（默认 40，从配置读取）
     * @param args.minScore 最低相似度阈值（默认 0.15，cosine similarity）
     * @param args.categoryFilter Danbooru 分类过滤（如 [0, 5] 仅返回 general + meta）
     */
    search: (args: {
      query: string;
      topK?: number;
      minScore?: number;
      categoryFilter?: number[];
    }) => Promise<{
      success: boolean;
      results: Array<{
        name: string;
        category: number;
        count: number;
        aliases: string[];
        score: number;
      }>;
      error?: string;
    }>;

    /** 清空索引（删除向量数据文件 + meta 文件；vectorizing 中需先 cancel） */
    clearIndex: () => Promise<{
      success: boolean;
      error?: string;
    }>;

    /**
     * 订阅向量化进度事件（主进程 → 渲染进程单向广播）。
     * @returns 取消订阅函数（组件卸载时调用，避免内存泄漏）
     */
    onProgress: (
      callback: (event: {
        phase: 'starting' | 'embedding' | 'storing' | 'finalizing' | 'done' | 'error' | 'cancelled';
        current: number;
        total: number;
        percentage: number;
        eta?: number;
        failedCount: number;
        message?: string;
        error?: string;
      }) => void
    ) => () => void;

    // ====== 多轮标签审计扩展（Spec: add-multi-round-tag-audit / Task 1.3） ======
    // 用户自定义同义词映射表 IPC：用于末轮人工审核入口持久化用户指定的替换映射
    //   - getUserSynonymMap：读取全部映射（key 小写 → 替换词）
    //   - addUserSynonymMapping：末轮人工审核替换时写入（original → replacement）
    //   - removeUserSynonymMapping：撤销手动替换时删除对应映射
    // 持久化到 {userData}/data/user-synonym-map.json，下次 validateTagsAgainstLibrary L0 首轮命中

    /** 读取用户自定义同义词映射表（key 小写 → 替换词；文件不存在/损坏返回空对象） */
    getUserSynonymMap: () => Promise<{
      success: boolean;
      map: Record<string, string>;
      error?: string;
    }>;

    /**
     * 新增/更新一条用户自定义同义词映射。
     * @param args.original 原始 tag（如 "B-cup"）
     * @param args.replacement 替换 tag（如 "medium_breasts"）
     */
    addUserSynonymMapping: (args: {
      original: string;
      replacement: string;
    }) => Promise<{ success: boolean; error?: string }>;

    /**
     * 删除一条用户自定义同义词映射（按 original，大小写不敏感，幂等）。
     * @param args.original 原始 tag
     */
    removeUserSynonymMapping: (args: {
      original: string;
    }) => Promise<{ success: boolean; error?: string }>;
  };

  /** 会话管理 API（Task 6: 会话管理后端） */
  session: {
    /** 创建新会话（默认标题"新对话"） */
    create: (args: { characterCardId: string; title?: string }) => Promise<{
      success: boolean;
      session?: {
        sessionId: string;
        characterCardId: string;
        title: string;
        createdAt: number;
        lastActiveAt: number;
        messageCount: number;
        metadata?: Record<string, unknown>;
      };
      error?: string;
    }>;
    /** 列出当前角色所有会话（按最后活跃时间降序） */
    list: (characterCardId: string) => Promise<{
      success: boolean;
      sessions?: Array<{
        sessionId: string;
        characterCardId: string;
        title: string;
        createdAt: number;
        lastActiveAt: number;
        messageCount: number;
        metadata?: Record<string, unknown>;
      }>;
      error?: string;
    }>;
    /** 切换会话（更新 lastActiveAt） */
    switch: (args: { characterCardId: string; sessionId: string }) => Promise<{
      success: boolean;
      session?: {
        sessionId: string;
        characterCardId: string;
        title: string;
        createdAt: number;
        lastActiveAt: number;
        messageCount: number;
        metadata?: Record<string, unknown>;
      };
      error?: string;
    }>;
    /** 删除会话（同时删除消息历史文件） */
    delete: (args: { characterCardId: string; sessionId: string }) => Promise<{
      success: boolean;
      session?: {
        sessionId: string;
        characterCardId: string;
        title: string;
        createdAt: number;
        lastActiveAt: number;
        messageCount: number;
        metadata?: Record<string, unknown>;
      };
      error?: string;
    }>;
    /** 重命名会话标题 */
    rename: (args: { characterCardId: string; sessionId: string; newTitle: string }) => Promise<{
      success: boolean;
      session?: {
        sessionId: string;
        characterCardId: string;
        title: string;
        createdAt: number;
        lastActiveAt: number;
        messageCount: number;
        metadata?: Record<string, unknown>;
      };
      error?: string;
    }>;
    /** 保存会话消息历史 */
    saveMessages: (args: {
      characterCardId: string;
      sessionId: string;
      messages: Array<{ role: string; content: string; timestamp?: number; [key: string]: unknown }>;
    }) => Promise<{
      success: boolean;
      session?: {
        sessionId: string;
        characterCardId: string;
        title: string;
        createdAt: number;
        lastActiveAt: number;
        messageCount: number;
        metadata?: Record<string, unknown>;
      };
      error?: string;
    }>;
    /** 加载会话消息历史（文件不存在时返回空数组） */
    loadMessages: (characterCardId: string, sessionId: string) => Promise<{
      success: boolean;
      messages?: Array<{ role: string; content: string; timestamp?: number; [key: string]: unknown }>;
      error?: string;
    }>;
  };

  // ============================================================================
  // 缩略图管线 API（Spec: optimize-system-rendering-performance / Task 7）
  // ============================================================================
  // 类型镜像 preload.ts 的 thumbnail 命名空间；主进程实现见
  // src/main/ipc/handlers/thumbnailHandlers.ts 与 src/main/services/thumbnailService.ts。
  // 供渲染进程 <LazyImage>（Task 6.1）+ imageCache（Task 8.1）走 IPC 取压缩缩略图。
  thumbnail: {
    /**
     * 生成或读取指定源图片的缩略图 dataUrl。
     * @param args.sourcePath 源图片绝对路径
     * @param args.size       缩略图最大边长（256 | 384，默认 256）
     * @returns 成功：{ dataUrl, mime, fromCache }；失败：{ error }
     *          dataUrl 可直接用于 <img src>（CSP 兼容）
     */
    get: (args: { sourcePath: string; size?: 256 | 384 }) => Promise<
      | { dataUrl: string; mime: string; fromCache: boolean; error?: undefined }
      | { error: string; dataUrl?: undefined }
    >;
    /** 粗粒度清空全部缩略图缓存（内存 LRU + 磁盘 thumbnails 目录内容） */
    invalidate: () => Promise<{ ok: boolean; error?: string }>;
  };
}

export { ElectronAPI };
