/**
 * 世界书 autoGenerated 草稿条目待审阅区（Task 17.2 SubTask 17.2）。
 *
 * 来源：spec §二 Task 17.2（autoGenerated 待审阅区 UI）
 * 决策：自研。世界书自驱的审阅流是本项目特有业务。
 *
 * 职责：
 *  - 当用户打开某本世界书时，可点击"待审阅"按钮打开本 Modal
 *  - 列出该世界书中所有 autoGenerated=true 的草稿条目（由 agent 通过
 *    createEntry / expandFromContext 工具写入）
 *  - 每条草稿可单独「批准」（转为正式条目）或「拒绝」（删除）
 *  - 支持「全部批准」批量操作
 *  - 显示写溯源（provenance）：来源 agent / 工具名 / 时间
 *
 * 设计约束（spec §5.1 双轨并行 + §5.4 安全）：
 *  - 审阅区是只读 + 审批操作，不改动现有手动 CRUD 路径
 *  - 批准/拒绝通过 IPC 调用 worldBookService，由服务层保证文件一致性
 *  - 操作后刷新列表 + 通知父组件（onChanged 回调）
 */

import React, { useState, useEffect, useCallback } from 'react';
import { Modal, Button, Table, Tag, Space, message, Empty, Tooltip, Typography, Popconfirm } from 'antd';
import {
  CheckOutlined,
  CloseOutlined,
  ReloadOutlined,
  CheckCircleOutlined,
  ClockCircleOutlined,
  RobotOutlined,
  SafetyCertificateOutlined,
} from '@ant-design/icons';
import type { ColumnsType } from 'antd/es/table';

const { Paragraph, Text } = Typography;

interface AutoGeneratedEntry {
  uid: number | string;
  id?: number;
  name?: string;
  comment?: string;
  content?: string;
  key?: string[];
  secondaryKeys?: string[];
  keysecondary?: string[];
  tags?: string[];
  autoGenerated: boolean;
  provenance?: {
    source: string;
    runId?: string;
    toolName: string;
    timestamp: number;
  };
  [key: string]: unknown;
}

interface WorldBookAutoGeneratedReviewProps {
  /** 世界书文件绝对路径 */
  worldBookPath: string | null;
  /** Modal 是否打开 */
  open: boolean;
  /** 关闭 Modal 回调 */
  onClose: () => void;
  /** 审阅操作完成后回调（父组件可据此刷新世界书内容） */
  onChanged?: () => void;
  /** 应用主题 */
  appTheme?: 'light' | 'dark';
  /** 审核草稿条目（打开审核 Modal） */
  onAuditEntry?: (entry: AutoGeneratedEntry) => void;
}

const WorldBookAutoGeneratedReview: React.FC<WorldBookAutoGeneratedReviewProps> = ({
  worldBookPath,
  open,
  onClose,
  onChanged,
  appTheme,
  onAuditEntry,
}) => {
  const [entries, setEntries] = useState<AutoGeneratedEntry[]>([]);
  const [loading, setLoading] = useState(false);
  const [operatingUid, setOperatingUid] = useState<string | number | null>(null);

  /** 加载草稿条目列表 */
  const loadEntries = useCallback(async () => {
    if (!worldBookPath) {
      setEntries([]);
      return;
    }
    setLoading(true);
    try {
      const result = await window.electronAPI.worldBook.listAutoGenerated(worldBookPath);
      if (result.success) {
        setEntries(result.entries as AutoGeneratedEntry[]);
      } else {
        message.error(`加载待审阅条目失败: ${result.error || '未知错误'}`);
        setEntries([]);
      }
    } catch (err) {
      message.error(`加载待审阅条目异常: ${err instanceof Error ? err.message : String(err)}`);
      setEntries([]);
    } finally {
      setLoading(false);
    }
  }, [worldBookPath]);

  // 打开 Modal 时自动加载
  useEffect(() => {
    if (open && worldBookPath) {
      loadEntries();
    } else if (!open) {
      // 关闭时清空状态，避免下次打开闪烁旧数据
      setEntries([]);
      setOperatingUid(null);
    }
  }, [open, worldBookPath, loadEntries]);

  /** 批准单个草稿条目 */
  const handleApprove = useCallback(
    async (uid: string | number) => {
      if (!worldBookPath) return;
      setOperatingUid(uid);
      try {
        const result = await window.electronAPI.worldBook.approveAutoGenerated(worldBookPath, uid);
        if (result.success) {
          message.success('已批准该条目，转为正式条目');
          await loadEntries();
          onChanged?.();
        } else {
          message.error(`批准失败: ${result.error || '未知错误'}`);
        }
      } catch (err) {
        message.error(`批准异常: ${err instanceof Error ? err.message : String(err)}`);
      } finally {
        setOperatingUid(null);
      }
    },
    [worldBookPath, loadEntries, onChanged]
  );

  /** 拒绝（删除）单个草稿条目 */
  const handleReject = useCallback(
    async (uid: string | number) => {
      if (!worldBookPath) return;
      setOperatingUid(uid);
      try {
        const result = await window.electronAPI.worldBook.rejectAutoGenerated(worldBookPath, uid);
        if (result.success) {
          message.success('已拒绝并删除该草稿条目');
          await loadEntries();
          onChanged?.();
        } else {
          message.error(`拒绝失败: ${result.error || '未知错误'}`);
        }
      } catch (err) {
        message.error(`拒绝异常: ${err instanceof Error ? err.message : String(err)}`);
      } finally {
        setOperatingUid(null);
      }
    },
    [worldBookPath, loadEntries, onChanged]
  );

  /** 批量批准所有草稿条目 */
  const handleApproveAll = useCallback(async () => {
    if (!worldBookPath || entries.length === 0) return;
    setOperatingUid('all');
    try {
      const result = await window.electronAPI.worldBook.approveAllAutoGenerated(worldBookPath);
      if (result.success) {
        message.success(`已批量批准 ${result.approvedCount} 个草稿条目`);
        await loadEntries();
        onChanged?.();
      } else {
        message.error(`批量批准失败: ${result.error || '未知错误'}`);
      }
    } catch (err) {
      message.error(`批量批准异常: ${err instanceof Error ? err.message : String(err)}`);
    } finally {
      setOperatingUid(null);
    }
  }, [worldBookPath, entries.length, loadEntries, onChanged]);

  /** 格式化溯源信息 */
  const formatProvenance = (p?: AutoGeneratedEntry['provenance']): React.ReactNode => {
    if (!p) return <Text type="secondary">未知来源</Text>;
    const time = p.timestamp ? new Date(p.timestamp).toLocaleString('zh-CN') : '未知时间';
    return (
      <Tooltip
        title={
          <div>
            <div>来源: {p.source}</div>
            <div>工具: {p.toolName}</div>
            {p.runId ? <div>运行 ID: {p.runId}</div> : null}
            <div>时间: {time}</div>
          </div>
        }
      >
        <Space size={4}>
          <RobotOutlined />
          <Text type="secondary" style={{ fontSize: 12 }}>
            {p.toolName} · {time}
          </Text>
        </Space>
      </Tooltip>
    );
  };

  /** 表格列定义 */
  const columns: ColumnsType<AutoGeneratedEntry> = [
    {
      title: 'UID',
      dataIndex: 'uid',
      key: 'uid',
      width: 70,
    },
    {
      title: '名称',
      dataIndex: 'name',
      key: 'name',
      width: 180,
      render: (name: string, record) => name || record.comment || `Entry ${record.uid}`,
    },
    {
      title: '主关键词',
      dataIndex: 'key',
      key: 'key',
      width: 200,
      render: (keys: string[]) =>
        keys && keys.length > 0 ? (
          <Space size={4} wrap>
            {keys.map((k, i) => (
              <Tag color="blue" key={`${k}-${i}`}>
                {k}
              </Tag>
            ))}
          </Space>
        ) : (
          <Text type="secondary">（无）</Text>
        ),
    },
    {
      title: '次关键词',
      dataIndex: 'secondaryKeys',
      key: 'secondaryKeys',
      width: 160,
      render: (keys: string[]) =>
        keys && keys.length > 0 ? (
          <Space size={4} wrap>
            {keys.map((k, i) => (
              <Tag color="cyan" key={`${k}-${i}`}>
                {k}
              </Tag>
            ))}
          </Space>
        ) : (
          <Text type="secondary">（无）</Text>
        ),
    },
    {
      title: '内容预览',
      dataIndex: 'content',
      key: 'content',
      render: (content: string) => (
        <Paragraph
          ellipsis={{ rows: 3, expandable: true, symbol: '展开' }}
          style={{ marginBottom: 0, maxWidth: 400 }}
        >
          {content || '（无内容）'}
        </Paragraph>
      ),
    },
    {
      title: '来源',
      dataIndex: 'provenance',
      key: 'provenance',
      width: 200,
      render: (_: unknown, record) => formatProvenance(record.provenance),
    },
    {
      title: '操作',
      key: 'action',
      width: 220,
      fixed: 'right',
      render: (_: unknown, record) => (
        <Space size={8}>
          <Button
            size="small"
            icon={<SafetyCertificateOutlined />}
            onClick={() => onAuditEntry?.(record)}
          >
            审核
          </Button>
          <Button
            type="primary"
            size="small"
            icon={<CheckOutlined />}
            loading={operatingUid === record.uid}
            onClick={() => handleApprove(record.uid)}
          >
            批准
          </Button>
          <Popconfirm
            title="确认拒绝该草稿条目？"
            description="拒绝将从世界书中永久删除此草稿条目，此操作不可撤销。"
            okText="拒绝删除"
            cancelText="取消"
            okButtonProps={{ danger: true }}
            onConfirm={() => handleReject(record.uid)}
          >
            <Button
              danger
              size="small"
              icon={<CloseOutlined />}
              loading={operatingUid === record.uid}
            >
              拒绝
            </Button>
          </Popconfirm>
        </Space>
      ),
    },
  ];

  return (
    <Modal
      title={
        <Space>
          <ClockCircleOutlined />
          <span>AI 自动生成条目 · 待审阅</span>
          {entries.length > 0 && <Tag color="orange">{entries.length} 条待审</Tag>}
        </Space>
      }
      open={open}
      onCancel={onClose}
      width={1100}
      getContainer={() => document.body}
      zIndex={3000}
      maskStyle={{ zIndex: 3000 }}
      footer={
        <Space>
          <Button icon={<ReloadOutlined />} onClick={loadEntries} loading={loading}>
            刷新
          </Button>
          <Button
            type="primary"
            icon={<CheckCircleOutlined />}
            onClick={handleApproveAll}
            disabled={entries.length === 0}
            loading={operatingUid === 'all'}
          >
            全部批准
          </Button>
          <Button onClick={onClose}>关闭</Button>
        </Space>
      }
      style={{
        backgroundColor: 'var(--bg-container, #1f1f1f)',
        color: 'var(--text-primary, #ffffff)',
        zIndex: 2000,
      }}
    >
      <div style={{ marginBottom: 12, color: 'var(--text-secondary, #999)' }}>
        <Typography.Paragraph type="secondary" style={{ marginBottom: 8 }}>
          智能体通过 <Text code>createEntry</Text> /{' '}
          <Text code>expandFromContext</Text> 工具自动生成的条目会在此待审阅。
          批准后转为正式条目，拒绝则永久删除。
        </Typography.Paragraph>
      </div>

      {entries.length === 0 && !loading ? (
        <Empty
          description="暂无待审阅的 AI 生成条目"
          image={Empty.PRESENTED_IMAGE_SIMPLE}
        />
      ) : (
        <Table
          columns={columns}
          dataSource={entries}
          rowKey={(record) => String(record.uid)}
          loading={loading}
          size="small"
          pagination={entries.length > 10 ? { pageSize: 10 } : false}
          scroll={{ x: 1100, y: 500 }}
          rowClassName={() => (appTheme === 'dark' ? 'wb-ag-row-dark' : '')}
        />
      )}
    </Modal>
  );
};

export default WorldBookAutoGeneratedReview;
