/**
 * 世界书编写智能体共享类型定义（SSOT）
 *
 * 来源：spec §二 Task 1 / `implement-worldbook-authoring-agent`
 *
 * 设计理念（借鉴 openclaw，spec §设计理念）：
 *  1. 任务驱动行为模型：智能体始终围绕显式 `AuthoringGoal` 行动，而非自由对话
 *  2. 多轮对话上下文管理：`AuthoringSession` 持久化到 MemoryStore，进程重启可恢复
 *  3. 自主决策与任务切换：PLANNING / AUTHORING / AUDITING 三阶段自主决策
 *  4. steer 行为引导：复用 `learning/steerEngine`，偏离质量标准时注入 steer 消息
 *  5. goal 目标追踪：复用 `learning/goalTracker`，追踪编写目标完成度
 *  6. 防失控调度：复用 `learning/pacing` + `stagger`，自驱循环间隔钳位
 *
 * 设计约束（对齐 `writing-agent.types.ts` / `learning/types.ts`）：
 *  - 类型可序列化（落库到 SQLite agent_memory.metadata JSON 或单独列）
 *  - 跨进程 IPC 安全：避免 Map/Set/Date 等不可序列化字段，统一用 number 时间戳
 *  - 该文件为共享类型真源（single source of truth）：
 *    · 主进程 `src/main/services/agent/worldbook/worldbookAuthoringTypes.ts` re-export 本文件类型
 *    · 渲染进程通过 `src/renderer/types/electron.d.ts` 引用本文件类型
 *
 * 字段标准对齐：
 *  - 条目必填字段：`key` 非空数组 / `content` 非空 / `comment` 或 `name` 非空
 *    （对齐 `worldBookService.migrateEntry` 标准化输出）
 *  - 草稿区机制：agent 生成的条目均标记 `autoGenerated: true`，经用户审批才转正式
 *    （对齐 `worldbookTools.buildAutoGeneratedEntry`）
 */

// ==================== 1. 状态机 ====================

/**
 * 世界书编写智能体五状态机。
 *
 * 状态转移图（spec §ADDED Requirements 三阶段启发式工作流）：
 *   PLANNING → AUTHORING → AUDITING → AWAITING_REVIEW → COMPLETE
 *
 * 各状态语义：
 *  - PLANNING        ：规划阶段。分析用户初始提示，识别设定维度，提出 2-4 个澄清问题，
 *                      综合用户回答生成 `AuthoringPlan`。
 *  - AUTHORING       ：自驱编写阶段。按 `AuthoringPlan` 逐维度调用 worldbookTools 生成条目，
 *                      每 3-5 条触发微型审计，发现问题注入 steer 消息自我修正。
 *  - AUDITING        ：审计闭环阶段。调用 `worldbookAuditService.runFullAudit` 执行三维度
 *                      质量把控（完整性 / 一致性 / 符合度），小问题自动修复，大问题汇总报告。
 *  - AWAITING_REVIEW ：等待用户审阅。所有草稿条目已写入待审阅区，用户审批后转正式条目。
 *  - COMPLETE        ：编写完成。会话终止，审计报告与编写过程记忆持久化到 MemoryStore。
 *
 * 状态转移条件由 `worldbookAuthoringService` 编排服务负责判定。
 */
export type AuthoringState =
  | 'PLANNING'
  | 'AUTHORING'
  | 'AUDITING'
  | 'AWAITING_REVIEW'
  | 'COMPLETE';

// ==================== 2. 设定维度 ====================

/**
 * 设定维度分类（spec §ADDED Requirements 自驱扩展能力）。
 *
 * 用于 `AuthoringDimension.category` 字段，标识维度所属的设定类别。
 * 与 `worldbookTools` / `world-book.*` 提示词模板中的维度分类保持一致。
 */
export type AuthoringDimensionCategory =
  | 'worldview' // 世界观（地理 / 历史 / 时代背景 / 宇宙法则）
  | 'faction' // 势力（组织 / 派系 / 国家 / 阶级）
  | 'character' // 人物（主要角色 / 次要角色 / 群像）
  | 'location' // 地点（城市 / 建筑 / 场景）
  | 'item' // 物品（道具 / 武器 / 科技产物）
  | 'event' // 事件（历史事件 / 剧情事件 / 战争）
  | 'rule' // 规则（魔法体系 / 物理法则 / 社会制度）
  | 'other'; // 其他（无法归类的补充维度）

/**
 * 维度来源（spec §ADDED Requirements 主动扩展内容维度）。
 *
 *  - user            ：用户在初始提示中明确要求
 *  - agent-suggested ：智能体识别到完整性必要而主动建议补充
 */
export type AuthoringDimensionSource = 'user' | 'agent-suggested';

/**
 * 关键词策略（spec §二 Task 1 / AuthoringPlan 关键词策略）。
 *
 * 指导 `worldbookTools.generateKeywords` 工具为该维度下的条目生成关键词时的策略。
 */
export interface KeywordStrategy {
  /** 策略类型：extractive（从内容抽取）/ generative（语义生成）/ hybrid（混合） */
  mode: 'extractive' | 'generative' | 'hybrid';
  /** 每条目目标关键词数量（主关键词 + 次关键词总数，默认 5） */
  keywordsPerEntry?: number;
  /** 主关键词与次关键词比例（默认 0.6，即 60% 主关键词） */
  primaryRatio?: number;
  /** 是否启用语义扩展（同义词 / 相关词，默认 true） */
  enableSemanticExpansion?: boolean;
  /** 额外约束（如"避免与已有条目关键词冲突""优先使用专有名词"） */
  constraints?: string[];
}

/**
 * 设定维度（spec §二 Task 1 / AuthoringPlan 维度清单单元）。
 *
 * 一个 `AuthoringDimension` 描述世界书中需要覆盖的一类设定（如"赛博朋克城市地理"），
 * 是 `AuthoringPlan` 与 `AuthoringGoal` 的核心组成单元。
 */
export interface AuthoringDimension {
  /** 维度唯一 ID（UUID 或 slug，跨会话稳定） */
  id: string;
  /** 维度名称（人类可读，如"地下势力"） */
  name: string;
  /** 维度分类 */
  category: AuthoringDimensionCategory;
  /** 该维度的目标条目数（受 `AuthoringConfig.maxEntriesPerDimension` / `minEntriesPerDimension` 钳位） */
  targetEntryCount: number;
  /** 维度来源：用户明确要求 vs 智能体建议补充 */
  source: AuthoringDimensionSource;
  /** 关键词生成策略（可选，未指定时由 `worldbookPlanningService` 推断默认值） */
  keywordStrategy?: KeywordStrategy;
  /** 维度描述（说明该维度应覆盖哪些内容，指导 AUTHORING 阶段生成） */
  description?: string;
  /** 该维度下已生成的条目 UID 列表（运行时填充，便于断点续跑与审计） */
  generatedEntryUids?: Array<number | string>;
}

// ==================== 3. 编写目标与计划 ====================

/**
 * 澄清问题（spec §ADDED Requirements 主动提出澄清问题）。
 *
 * 在 PLANNING 阶段，智能体识别到提示中的模糊点或缺失关键信息时，提出 2-4 个结构化
 * 澄清问题。每问题附"为什么需要这个信息"的说明。用户可选择回答或跳过；跳过的问题
 * 由智能体自主决定默认值并标注"智能体推断"。
 */
export interface ClarifyingQuestion {
  /** 问题唯一 ID */
  id: string;
  /** 问题内容（如"故事发生在哪个年代？"） */
  question: string;
  /** 为什么需要这个信息（如"年代影响科技水平与社会结构设定"） */
  why: string;
  /** 用户回答（未回答时为 undefined） */
  answer?: string;
  /** 是否被用户跳过（跳过的问题由智能体推断默认值） */
  skipped: boolean;
  /** 智能体推断的默认值（skipped=true 时由 `worldbookPlanningService` 填充） */
  inferredDefault?: string;
  /** 预设解决方案选项（至少 3 个，供用户在问答弹窗中选择） */
  options?: string[];
}

/**
 * 编写目标（spec §设计理念 §1 任务驱动行为模型）。
 *
 * 智能体始终围绕一个显式 `AuthoringGoal` 行动。目标包含：世界书主题、目标维度清单、
 * 目标条目总数、质量门槛。目标一旦确定，在整个会话期间不变（除非用户主动修改）。
 */
export interface AuthoringGoal {
  /** 世界书主题（用户初始提示的核心，如"一部赛博朋克侦探小说"） */
  theme: string;
  /** 目标维度清单（用户要求 + 智能体建议补充） */
  dimensions: AuthoringDimension[];
  /** 总目标条目数（各维度 targetEntryCount 之和，冗余字段便于快速校验） */
  targetTotalEntries: number;
  /** 质量门槛 [0, 1]：审计综合分低于此值时阻止进入 AWAITING_REVIEW 状态 */
  qualityThreshold: number;
}

/**
 * 编写计划（spec §ADDED Requirements 用户初始提示触发规划阶段）。
 *
 * PLANNING 阶段的产出物。综合用户初始提示、澄清问题回答、智能体维度扩展，
 * 生成结构化的 `AuthoringPlan`，作为 AUTHORING 阶段的执行蓝图。
 */
export interface AuthoringPlan {
  /** 编写目标（包含主题、维度清单、目标条目数、质量门槛） */
  goal: AuthoringGoal;
  /** 澄清问题列表（含用户回答 / 跳过标记 / 智能体推断默认值） */
  clarifyingQuestions: ClarifyingQuestion[];
  /** 用户回答汇总（便于 AUDITING 阶段 `evaluateConformance` 引用） */
  userAnswers: Array<{
    /** 对应的澄清问题 ID */
    questionId: string;
    /** 用户原始回答，或智能体推断的默认值 */
    answer: string;
    /** 是否为智能体推断（true 表示用户跳过了该问题） */
    inferred: boolean;
  }>;
  /** 计划创建时间戳（ms） */
  createdAt: number;
}

// ==================== 4. 会话状态 ====================

/**
 * 世界书编写会话（spec §设计理念 §2 多轮对话上下文管理）。
 *
 * `AuthoringSession` 持久化到 MemoryStore，进程重启后可恢复。包含会话全量状态：
 * 当前状态机位置、编写目标、计划、已完成维度、已生成条目 ID、审计报告。
 *
 * 落库到 agent_memory 表（type='agent', metadata.kind='worldbook-authoring-session'）。
 */
export interface AuthoringSession {
  /** 会话唯一 ID（UUID，跨进程引用） */
  id: string;
  /** 主世界书文件绝对路径（agent 写入的主目标） */
  worldBookPath: string;
  /**
   * 沙盒白名单（spec §ADDED Requirements 与现有底座集成 / 复用 Task 17 沙盒机制）。
   *
   * agent 仅能写入此白名单内的世界书路径；越权写入 → SANDBOX_VIOLATION 错误。
   * 通常包含 `worldBookPath` 本身，可扩展到关联的子世界书。
   */
  allowedWorldBookPaths: string[];
  /** 当前状态机位置 */
  state: AuthoringState;
  /** 编写目标（PLANNING 阶段完成后填充） */
  goal?: AuthoringGoal;
  /** 编写计划（PLANNING 阶段产出物） */
  plan?: AuthoringPlan;
  /** 已完成维度 ID 列表（AUTHORING 阶段运行时更新） */
  completedDimensions: string[];
  /** 已生成条目 UID 列表（草稿区，autoGenerated=true） */
  generatedEntryIds: Array<number | string>;
  /** 审计报告（AUDITING 阶段产出物，未审计时为 undefined） */
  auditReport?: AuditReport;
  /** 创建时间戳（ms） */
  createdAt: number;
  /** 最后更新时间戳（ms，每次状态转移后更新） */
  updatedAt: number;
  /** 是否被用户主动取消（取消后已生成草稿保留，等待用户审批或批量删除） */
  aborted?: boolean;
  /** 取消原因（aborted=true 时填充，如"用户主动取消"/"LLM 调用超时"） */
  abortReason?: string;
}

// ==================== 5. 审计报告 ====================

/**
 * 审计严重级别（spec §ADDED Requirements 编写过程审计机制）。
 *
 * 用于 `ConsistencyIssue.severity` / `AuditAutoFix.severity` / `AuditUserDecision.severity`。
 *
 *  - info     ：信息性提示（不影响通过）
 *  - warning  ：警告（建议修复，可自动修复）
 *  - error    ：错误（影响通过，需修复或用户决策）
 *  - critical ：严重错误（阻塞进入 AWAITING_REVIEW，必须用户决策）
 */
export type AuditSeverity = 'info' | 'warning' | 'error' | 'critical';

/**
 * 缺失字段记录（`CompletenessReport.missingFields` 单元）。
 *
 * 字段标准对齐 `worldBookService.migrateEntry`：必填字段为
 * `key`（非空数组）/ `content`（非空）/ `comment` 或 `name`（非空）。
 */
export interface MissingField {
  /** 条目 UID */
  entryUid: number | string;
  /** 缺失的字段名（如 'key' / 'content' / 'comment'） */
  field: string;
  /** 缺失原因（如 'key is empty array' / 'content is empty string'） */
  reason: string;
}

/**
 * 未达标维度记录（`CompletenessReport.underfilledDimensions` 单元）。
 *
 * 当某维度的实际条目数未达到目标条目数的 80%（spec §ADDED Requirements 内容完整性校验）
 * 时，记录到 `underfilledDimensions`。
 */
export interface UnderfilledDimension {
  /** 维度 ID */
  dimensionId: string;
  /** 维度名称 */
  dimensionName: string;
  /** 目标条目数 */
  targetCount: number;
  /** 实际条目数 */
  actualCount: number;
  /** 达标率 [0, 1]（actualCount / targetCount） */
  achievementRate: number;
}

/**
 * 完整性报告（spec §ADDED Requirements 内容完整性校验）。
 *
 * 由 `worldbookAuditService.validateCompleteness(plan, entries)` 产出。
 * 校验三维度：必填字段、维度覆盖、条目数达标（80% 阈值）。
 */
export interface CompletenessReport {
  /** 缺失字段列表（必填字段校验失败的条目） */
  missingFields: MissingField[];
  /** 未覆盖维度（plan 中存在但无任何条目的维度） */
  uncoveredDimensions: Array<{
    dimensionId: string;
    dimensionName: string;
  }>;
  /** 未达标维度（条目数未达到目标 80% 的维度） */
  underfilledDimensions: UnderfilledDimension[];
  /** 是否通过（无缺失字段 + 无未覆盖维度 + 无未达标维度） */
  passed: boolean;
}

/**
 * 一致性问题（spec §ADDED Requirements 逻辑一致性检查）。
 *
 * 由 `worldbookAuditService.checkConsistency(entries)` 产出。
 * 检测三维度：关键词冲突（同 key 触发语义矛盾）、设定矛盾（LLM 对比 content）、
 * 关系图无环（relations 字段校验）。
 */
export interface ConsistencyIssue {
  /** 冲突条目 UID 对（2 个或以上） */
  entryIds: Array<number | string>;
  /** 问题描述（如"条目A说'城市在地下'，条目B说'摩天大楼林立'"） */
  description: string;
  /** 严重级别 */
  severity: AuditSeverity;
  /** 问题类型（如 'keyword_conflict' / 'setting_contradiction' / 'relation_cycle'） */
  kind: 'keyword_conflict' | 'setting_contradiction' | 'relation_cycle' | 'other';
}

/**
 * 一致性报告（spec §ADDED Requirements 逻辑一致性检查）。
 */
export interface ConsistencyReport {
  /** 一致性问题列表 */
  issues: ConsistencyIssue[];
  /** 是否通过（无 error / critical 级别问题） */
  passed: boolean;
}

/**
 * 偏离条目记录（`ConformanceReport.deviatedEntries` 单元）。
 *
 * 由 `worldbookAuditService.evaluateConformance(userPrompt, clarifications, entries)` 产出。
 * 用户初始提示 + 澄清回答向量化，与每个条目做 cosine 相似度检索，低相似度条目标记为偏离。
 */
export interface DeviatedEntry {
  /** 条目 UID */
  entryUid: number | string;
  /** 条目名称 */
  entryName?: string;
  /** 与用户设定的 cosine 相似度分数 [0, 1] */
  score: number;
  /** 偏离原因（LLM 分析的简短说明） */
  reason?: string;
}

/**
 * 符合度报告（spec §ADDED Requirements 设定符合度评估）。
 */
export interface ConformanceReport {
  /** 符合度条目数（score >= auditThreshold 的条目数） */
  conformantCount: number;
  /** 总条目数 */
  totalCount: number;
  /** 偏离条目列表（score < auditThreshold 的条目） */
  deviatedEntries: DeviatedEntry[];
  /** 是否通过（conformantCount / totalCount >= auditThreshold） */
  passed: boolean;
}

/**
 * 自动修复建议（spec §ADDED Requirements 审计闭环阶段自动修复或提示）。
 *
 * 小问题（warning / 部分 error）由智能体自动修复（调用 worldbookTools 更新条目）；
 * 修复建议记录到 `AuditReport.autoFixes`，便于追溯。
 */
export interface AuditAutoFix {
  /** 修复目标条目 UID */
  entryUid: number | string;
  /** 修复字段（如 'content' / 'key' / 'comment'） */
  field: string;
  /** 原始值（修复前） */
  oldValue: string;
  /** 修复后值 */
  newValue: string;
  /** 修复原因（对应的一致性问题 / 缺失字段） */
  reason: string;
  /** 严重级别 */
  severity: AuditSeverity;
  /** 是否已应用（true=已写入；false=建议但未应用，需用户确认） */
  applied: boolean;
}

/**
 * 需用户决策项（spec §ADDED Requirements 审计闭环阶段自动修复或提示）。
 *
 * 大问题（critical / 部分 error）由智能体汇总报告提示用户决策，不自动修复。
 */
export interface AuditUserDecision {
  /** 决策项 ID */
  id: string;
  /** 关联条目 UID 列表 */
  entryIds: Array<number | string>;
  /** 问题描述 */
  description: string;
  /** 严重级别 */
  severity: AuditSeverity;
  /** 可选决策选项（如 ['删除条目B', '修改条目A', '忽略']） */
  options: string[];
  /** 用户选择的选项（未决策时为 undefined） */
  chosenOption?: string;
}

/**
 * 审计报告（spec §ADDED Requirements 编写过程审计机制 三维度聚合）。
 *
 * 由 `worldbookAuditService.runFullAudit(plan, entries, userPrompt, clarifications)` 产出，
 * 聚合完整性 / 一致性 / 符合度三维度报告，附自动修复建议与需用户决策项。
 */
export interface AuditReport {
  /** 完整性报告（必填字段 + 维度覆盖 + 条目数达标） */
  completeness: CompletenessReport;
  /** 一致性报告（关键词冲突 + 设定矛盾 + 关系图无环） */
  consistency: ConsistencyReport;
  /** 符合度报告（与用户初始提示 + 澄清回答的语义一致性） */
  conformance: ConformanceReport;
  /** 综合是否通过（三维度全部 passed） */
  overallPassed: boolean;
  /** 综合分数 [0, 1]（三维度加权平均，低于 `AuthoringGoal.qualityThreshold` 阻止进入 AWAITING_REVIEW） */
  overallScore: number;
  /** 自动修复建议列表（已应用 + 未应用） */
  autoFixes: AuditAutoFix[];
  /** 需用户决策项列表（大问题，不自动修复） */
  userDecisions: AuditUserDecision[];
  /** 审计时间戳（ms） */
  createdAt: number;
  /**
   * 编写过程元数据（可选，由编排服务在审计完成后填充）。
   *
   * Spec: add-agent-web-search-tool §Requirement: 世界书编写智能体集成。
   * `webSearchUsed` 标记本次编写是否成功使用了网络搜索补充上下文
   * （至少一次搜索调用成功返回即 true；未启用 / 全部失败为 false）。
   */
  metadata?: {
    webSearchUsed?: boolean;
  };
}

// ==================== 6. 进度事件 ====================

/**
 * 编写进度事件（spec §ADDED Requirements 进度回调与事件流）。
 *
 * 通过 IPC 事件流 `worldbookAgent:progress` 推送到渲染进程，
 * 前端 `useWorldBookAuthoring` hook 订阅事件流更新 UI（进度条 + 事件日志 + 当前活动提示）。
 */
export interface AuthoringProgressEvent {
  /** 当前阶段（与 `AuthoringState` 对齐，含子阶段细分） */
  phase:
    | 'planning_analyzing' // PLANNING：分析用户提示
    | 'planning_researching' // PLANNING：网络搜索补充上下文（Spec: add-agent-web-search-tool）
    | 'planning_clarifying' // PLANNING：等待用户回答澄清问题
    | 'planning_building' // PLANNING：构建计划
    | 'authoring_generating' // AUTHORING：生成条目中
    | 'authoring_mini_audit' // AUTHORING：微型审计
    | 'authoring_fixing' // AUTHORING：自我修正
    | 'auditing_full' // AUDITING：完整审计
    | 'auditing_fixing' // AUDITING：自动修复
    | 'awaiting_review' // AWAITING_REVIEW：等待用户审阅
    | 'complete' // COMPLETE：完成
    | 'cancelled' // 取消
    | 'error'; // 错误
  /** 当前维度名称（AUTHORING 阶段填充，如"地下势力"） */
  currentDimension?: string;
  /** 总维度数 */
  totalDimensions?: number;
  /** 已完成维度数 */
  completedDimensions?: number;
  /** 已生成条目数 */
  entriesGenerated: number;
  /** 目标条目数 */
  targetEntries: number;
  /** 当前活动描述（如"正在生成'黑帮组织'条目"/"检测到关键词冲突，注入 steer 消息"） */
  currentActivity: string;
  /** 人类可读消息（推送至事件日志） */
  message?: string;
  /** 错误信息（phase='error' 时存在） */
  error?: string;
  /**
   * 会话 ID（运行时附带）。
   *
   * 用于解决 sessionId 时序问题：`worldbookAgent:run` IPC 为阻塞调用，
   * sessionId 仅在返回时才设置到 React state，但澄清问题在运行期间通过
   * progress 事件到达，此时 state.sessionId 仍为 null。主进程在每次
   * emitProgress 时自动附带 sessionId，渲染进程 handleProgressEvent
   * 据此提前建立 sessionId 映射。字段可选以保持向后兼容。
   */
  sessionId?: string;
  /**
   * 最近生成的条目列表（可选）。
   *
   * 在条目生成完成时推送，携带最近生成的条目名称和内容摘要，
   * 供前端进度面板展示实际生成内容。最多 5 条，content 截断到 200 字符。
   */
  generatedEntries?: Array<{ name: string; content: string }>;

  /**
   * 审计结果详情（可选）。
   *
   * 在微型审计或完整审计完成时推送，携带审计结果摘要，
   * 供前端进度面板展示审计过程和结果。
   */
  auditDetail?:
    | {
        type: 'mini';
        /** 审计的维度名 */
        dimension: string;
        /** 完整性问题数 */
        completenessIssues: number;
        /** 一致性问题数 */
        consistencyIssues: number;
        /** 关键问题列表（最多 5 条） */
        issues: Array<{ description: string; entryIds: string[] }>;
      }
    | {
        type: 'full';
        /** 综合是否通过 */
        overallPassed: boolean;
        /** 综合分数 [0, 1] */
        overallScore: number;
        /** 完整性结果摘要 */
        completeness: string;
        /** 一致性结果摘要 */
        consistency: string;
        /** 符合度结果摘要 */
        conformance: string;
        /** 已自动修复数 */
        autoFixesApplied: number;
        /** 需用户决策项列表（最多 5 条） */
        userDecisions: Array<{ description: string; severity: string }>;
      };

  /**
   * 思考步骤（可选）。
   *
   * 当事件携带 thoughtStep 时，前端将其追加到思考时间线，
   * 用于展示 AI 的微观思考过程（LLM 调用目的、输入输出摘要、耗时）。
   */
  thoughtStep?: ThoughtStep;
  /** 事件时间戳（ms） */
  timestamp: number;
}

/**
 * 思考步骤 —— 记录 AI 在编写过程中的每一次关键思考。
 *
 * 用于思考过程可视化，展示从初始构思到最终输出的演变轨迹。
 * 每个步骤对应一次 LLM 调用、数据解析或策略决策。
 */
export interface ThoughtStep {
  /** 步骤类型 */
  type: 'llm_call' | 'parse' | 'decision' | 'tool_call';
  /** 步骤目的（人类可读，如"分析用户提示"、"生成「势力」维度条目"） */
  purpose: string;
  /** 输入摘要（截断到 300 字符） */
  inputSummary?: string;
  /** 输出摘要（截断到 300 字符） */
  outputSummary?: string;
  /** 耗时 ms */
  durationMs: number;
  /** 是否成功 */
  success: boolean;
  /** 关联的阶段（与 AuthoringProgressEvent.phase 对齐） */
  phase?: AuthoringProgressEvent['phase'];
  /** 时间戳 ms */
  timestamp: number;
}

// ==================== 7. 配置 ====================

/**
 * 世界书编写智能体配置（spec §设计理念 §6 防失控调度 + §ADDED Requirements）。
 *
 * 默认值参考 spec §设计理念 §6：
 *  - pacing 钳位：min 2s / max 30s（自驱编写循环每轮间隔）
 *  - 审计阈值：0.8（综合分低于此值阻止进入 AWAITING_REVIEW）
 *  - 单维度条目数：min 2 / max 5（默认范围）
 *
 * 主进程专用配置 `WorldBookAuthoringConfig` 在此基础上扩展 llmConfig / agentCoreConfig
 * （见 `src/main/services/agent/worldbook/worldbookAuthoringTypes.ts`）。
 */
export interface AuthoringConfig {
  /** 单维度最大条目数（默认 5，钳位 `AuthoringDimension.targetEntryCount` 上限） */
  maxEntriesPerDimension: number;
  /** 单维度最小条目数（默认 2，钳位 `AuthoringDimension.targetEntryCount` 下限） */
  minEntriesPerDimension: number;
  /** 审计阈值 [0, 1]（默认 0.8，低于此值阻止进入 AWAITING_REVIEW） */
  auditThreshold: number;
  /** 自驱循环最小间隔 ms（默认 2000，对齐 spec §设计理念 §6 pacing min 2s） */
  pacingMinMs: number;
  /** 自驱循环最大间隔 ms（默认 30000，对齐 spec §设计理念 §6 pacing max 30s） */
  pacingMaxMs: number;
  /** 是否启用自动修复（默认 true，warning / 部分 error 自动修复） */
  enableAutoFix: boolean;
  /**
   * 是否启用网络搜索补充（默认 false）。
   *
   * Spec: add-agent-web-search-tool §Requirement: 世界书编写智能体集成。
   * 启用后，PLANNING 阶段（analyzePrompt 前）与 AUTHORING 阶段（generateEntriesForDimension 前）
   * 会调用 webSearch 获取相关资料作为 LLM 上下文。字段可选以保持向后兼容
   * （既有测试/调用方未设置时视为 false）。`WorldBookAuthoringConfig` 通过继承获得此字段。
   */
  enableWebSearch?: boolean;
  /**
   * 网络搜索结果最大条数（默认 5）。
   *
   * 透传给 `WebSearchService.search` 的 `options.maxResults`。
   * 字段可选以保持向后兼容，未设置时由编排服务使用默认值 5。
   */
  webSearchMaxResults?: number;
}

/**
 * 默认配置常量（参考 `learning/types.ts` 的 `DEFAULT_DREAMING_CONFIG` 模式）。
 *
 * 各字段默认值对齐 spec §设计理念 §6 与 §ADDED Requirements。
 */
export const DEFAULT_AUTHORING_CONFIG: AuthoringConfig = {
  maxEntriesPerDimension: 5,
  minEntriesPerDimension: 2,
  auditThreshold: 0.8,
  pacingMinMs: 2000,
  pacingMaxMs: 30000,
  enableAutoFix: true,
  // Spec: add-agent-web-search-tool — 网络搜索默认关闭，用户需在 Modal 中显式开启
  enableWebSearch: false,
  webSearchMaxResults: 5,
};

// ==================== 7.5 严重级别工具 ====================

/**
 * 严重级别排序值（参考 `writing-agent.types.ts` 的 `SEVERITY_ORDER` 模式）。
 *
 * 用于过滤自动修复：仅修复 severity 排序值 >= 阈值的问题。
 */
export const AUDIT_SEVERITY_ORDER: Record<AuditSeverity, number> = {
  info: 1,
  warning: 2,
  error: 3,
  critical: 4,
};

/**
 * 判断审计问题严重级别是否满足最低阈值。
 *
 * @param severity 问题严重级别
 * @param minSeverity 最低严重级别阈值
 * @returns 是否满足阈值（severity 排序值 >= minSeverity 排序值）
 */
export function meetsAuditSeverityThreshold(
  severity: AuditSeverity,
  minSeverity: AuditSeverity
): boolean {
  const sevValue = AUDIT_SEVERITY_ORDER[severity] ?? 0;
  const minValue = AUDIT_SEVERITY_ORDER[minSeverity] ?? 0;
  return sevValue >= minValue;
}

// ==================== 8. 渲染进程别名 ====================

/**
 * 渲染进程使用的会话类型别名（与主进程 `AuthoringSession` 一致）。
 *
 * 参照 `writing-agent.types.ts` 的 `WritingAgentRequest` / `WritingAgentEvent` 别名模式，
 * 为渲染进程提供语义清晰的导入名。
 */
export type WorldBookAuthoringSession = AuthoringSession;

/**
 * 渲染进程使用的进度事件类型别名（与主进程 `AuthoringProgressEvent` 一致）。
 */
export type WorldBookAuthoringProgressEvent = AuthoringProgressEvent;

/**
 * 渲染进程使用的审计报告类型别名（与主进程 `AuditReport` 一致）。
 */
export type WorldBookAuthoringAuditReport = AuditReport;

/**
 * 渲染进程使用的编写计划类型别名（与主进程 `AuthoringPlan` 一致）。
 */
export type WorldBookAuthoringPlan = AuthoringPlan;
